### ISSUE TITLE
Search Grid

### ISSUE THREAD

**Issue by dylanpiera** [gustavnavar/Grid.Blazor#1]
**Describe the solution you'd like**
Would it be possible to implement a Search feature on the grid, searching all entries much like how [DataTables](https://datatables.net/examples/basic_init/zero_configuration.html) does it?

**Comment by gustavnavar** [comment]
You can filter text columns using "Contains" type of filter. But currently you have to do it column by column.

Number, boolean and datetime columns will require to convert values to strings in the back-end side before the "Contains" type of filter can be used. I think that there will  be a performance impact searching those columns in the case of grid with a large number of items. I will check the performance impact in this case.

**Comment by gustavnavar** [comment]
I've added searching functionality to the grid component. 

Keep in mind that searching can have a big impact on performance because the resulting database queries are long and complex. So enabling searches can force us to enable query client evaluation on EF Core

**Comment by gustavnavar** [comment]
Performance for searching has been improved. In the majority of cases it is not required to enable query client evaluation on EF Core.
