### ISSUE TITLE
How to display data not from a database?

### ISSUE THREAD

**Issue by win32nipuh** [gustavnavar/Grid.Blazor#101]
There is described how to use grid for working with EF->database.

How I can display data not from a databases? 

For example: I want to show list of files in some folder in file system?
Or to display S3 storage: to show keys on some bucket:

keyName1 Size1 LastModified1
keyName2 Size2 LastModified2
...
keyNameN SizeN LastModifiedN

The structure is simple but you use EF in your examples. How to work with data like I wrote?

**Comment by timbze** [comment]
All you need is `IEnumerable<Model>`. Hopefully this example will help you:

```csharp
IEnumerable<ItemModel> itemList = new List<ItemModel>() { new ItemModel(), new ItemModel() };
var server = new GridServer<ItemModel>(itemList, new QueryCollection(query), true, gridName, columns);
```
