### ISSUE TITLE
Filter with conditions combined?

### ISSUE THREAD

**Issue by pcecamacho** [gustavnavar/Grid.Blazor#102]
Hello
Is it possible to build a custom filter using more than one condition? For sample:
Column1 = "A1" OR Column1 = "A2" OR (Column1 <> "A1" AND Column1 = "A2" AND Column1 = "A3")
Where I have the following data:
A1,A2,A3,A4,A5
my result should be: A1, A2, A4, A5

I saw that the condition is inserted as:
filters.Add(GridFilterType.Condition.ToString("d"), this.condition);

Thank you in advance.

**Comment by gustavnavar** [comment]
No, one condition per column filter is the maximum currently supported. Having more than one condition per column requires major changes on the filtering processor.
