### ISSUE TITLE
There is an error in example?

### ISSUE THREAD

**Issue by Oleg26Dev** [gustavnavar/Grid.Blazor#103]
It seems there should be ;

https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Quick_start.md

4. Create a razor page to render the grid. The page file must have a .razor extension. An example of razor page is:
...
            var client = new GridClient<Order>(q => orderService.GetOrdersGridRows(columns, q), **query, false, "ordersGrid", columns)**
            _grid = client.Grid;

**Comment by gustavnavar** [comment]
It's fixed now.
Thanks !
