### ISSUE TITLE
A way to select a row with code

### ISSUE THREAD

**Issue by phisakel** [gustavnavar/Grid.Blazor#105]
I would like to select a row with a method like SelectRow(index))
E.g. to call this method from a custom cell component that is clicked

**Comment by gustavnavar** [comment]
I will try to add this feature for the next release

**Comment by gustavnavar** [comment]
GridBlazor 1.3.23 suports the ```SelectRow``` method for the ```GridComponent``` class:

```c#
    <GridComponent @ref="_gridComponent" T="Order" Grid="@_grid"></GridComponent>
    ....
    private GridComponent<Order> _gridComponent;
    ....
    _gridComponent.SelectRow(i);
```

**Comment by gustavnavar** [comment]
GridBlazor 1.3.23 suports the ```SelectRow``` method for the ```GridComponent``` class:

```c#
    <GridComponent @ref="_gridComponent" T="Order" Grid="@_grid"></GridComponent>
    ....
    private GridComponent<Order> _gridComponent;
    ....
    _gridComponent.SelectRow(i);
```

**Comment by gustavnavar** [comment]
GridBlazor 1.3.23 suports the ```SelectRow``` method for the ```GridComponent``` class:

```c#
    <GridComponent @ref="_gridComponent" T="Order" Grid="@_grid"></GridComponent>
    ....
    private GridComponent<Order> _gridComponent;
    ....
    _gridComponent.SelectRow(i);
```

**Comment by phisakel** [comment]
It worked thanks :)
I noticed that I had to set .Selectable(true) in grid options
