### ISSUE TITLE
A way to show page 1 by default

### ISSUE THREAD

**Issue by timbze** [gustavnavar/Grid.Blazor#108]
Is there a way to show page 1 by default? When I set `WithPaging(10)` and 12 items are in dataset, it will show the last 2 items on loading. I would like for it to show the first 10.

**Comment by gustavnavar** [comment]
By default it should show the 1st page.

If the second page is shown, you have defined something like this on your page:
```c#
    var query = new QueryDictionary<StringValues>();
    query.Add("grid-page", "2");
``` 

In that case you have to remove this line:
```c#
    query.Add("grid-page", "2");
```

**Comment by timbze** [comment]
Thanks! I guess from code that I copied and hadn't checked what that option was for.
