### ISSUE TITLE
Filter widget location when on side of screen

### ISSUE THREAD

**Issue by timbze** [gustavnavar/Grid.Blazor#110]
I don't know if it would be possible or easy to change filter widget position for columns that are close to edge of screen, for example see screenshot below. When I click filter button, I have to then scroll right in window so that I can enter filter criteria.
![image](https://user-images.githubusercontent.com/35117769/75371062-b8105d00-588b-11ea-9306-736e65c5f678.png)

**Comment by gustavnavar** [comment]
Blazor 1.3.24 includes a fix for this issue

**Comment by timbze** [comment]
It works when browser uses full screen space (maximised), but still does not work when browser takes up less than full screen size
