### ISSUE TITLE
How to show message after crud operation.

### ISSUE THREAD

**Issue by matteoventuri7** [gustavnavar/Grid.Blazor#112]
Hi,
i am trying to show a success message after crud operation like insert or update.
I tryed to insert my code into blazor OnAfterRender method but it does not fire after a crud operation.
I also tryed to override blazor method ShouldRender but no luck.

Any idea?

Thanks.

**Comment by gustavnavar** [comment]
I think it will require new events for AfterInsert, etc.

**Comment by matteoventuri7** [comment]
pull request #116

**Comment by gustavnavar** [comment]
GridBlazor 1.3.27  implements the After* events
