### ISSUE TITLE
QueryCollection 

### ISSUE THREAD

**Issue by faina09** [gustavnavar/Grid.Blazor#114]
I try to use generic class for Services and Repositories (if I success, I would like to share this with you and the community)
I work with an up-to-date git version of Grid.Blazor & dependencies, on .net core 3.1.1 

I have an issue loading  `public ItemsDTO<T> GetItemsGridRows(Action<IGridColumnCollection<T>> columns, QueryDictionary<StringValues> query)` where T is a Model class.
It reports:

> Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

I kown that a TypeLoadException usually means that there's some kind of binary-mismatch, and found that GridMvcCore is referencing `Microsoft.AspNetCore.Http, Version=2.2.0.0`

Do you think it is possible for me try to build a GridMvcCore with version 3.1.1? 

Thank you

**Comment by gustavnavar** [comment]
```QueryCollection``` was moved from ```Microsoft.AspNetCore.Http.Internal``` namespace in .Net Core 2.x to ```Microsoft.AspNetCore.Http``` namespace in .Net Core 3.x.

I continue using references to ```Microsoft.AspNetCore.xxx 2.2.0``` in the GridMvcCore package to avoid any issue. 

I've not tried to build it with new assemblies. I think it's possible but it can take some time finding new packages required for 3.x

**Comment by faina09** [comment]
thank you for you fast and helpful answer; I will try to find the packages, or will try to reference the ver 2.2.0 in .net core 3.x if possible.

**Comment by PeteJobi** [comment]
How do we fix this when using the nuget package? I've been stumped on this error for 3 straight hours.
