### ISSUE TITLE
Restrict “Show Items” field to positive numbers

### ISSUE THREAD

**Issue by maqines** [gustavnavar/Grid.Blazor#115]
**Describe the bug**
The “Show Item” field displays all the existing items in the grid if the number you enter is negative.

**To Reproduce**

1.	Fill the “Show Items” field using a negative number. (e.g. -1)
2.	Notice that the All Items are displayed.

**Expected behavior**
The "Show Items" should accept only positive numbers and show the same quantity in the grid as rows otherwise it should show an error message.

**Screenshots**
![image](https://user-images.githubusercontent.com/23421584/75715530-f058d680-5ca3-11ea-9e2b-bad5870d4783.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - The version of Grid Blazzor [e.g. 1.3.19]

**Comment by gustavnavar** [comment]
GridBlazor 1.3.28 has a fix for this bug
