### ISSUE TITLE
Why Sort does not work?

### ISSUE THREAD

**Issue by win32nipuh** [gustavnavar/Grid.Blazor#118]
When I click on column header it changes: the arrow appears Up or Down. It is correct. But grid does not sort. 
But when I DnD the column header to the Grouping control and then click there - sort in the grid works fine.
How to catch the reason why it does not work?

**Comment by gustavnavar** [comment]
Could you debug your project and share the exception trace?

**Comment by win32nipuh** [comment]
I do not see any exceptions in a console logs and VS Output window.
Another question: I do not use EF because I populate and display the AWS S3 storage. May be Grid uses EFSet sort? 

That is my function: 
```

protected override async Task OnParametersSetAsync()
    {
        var locale = CultureInfo.CurrentCulture;
        SharedResource.Culture = locale;

        Action<IGridColumnCollection<S3Library2>> columns = c =>
        ColumnCollections.S3Library2ColumnsWithEdit(c, "editrows");
        var query = new QueryDictionary<StringValues>();
        var client = new GridClient<S3Library2>(q => S3Service.GetS3LibraryGridRows(columns, q), query, false, "libGrid", columns, locale)
          .Sortable()
          .Filterable()
          .ClearFiltersButton(true)
          .Selectable(true, true)
          .Groupable(true)
          .Searchable(true, false, false)
          .SetStriped(true)
          .ChangePageSize(true)
          .WithMultipleFilters()
          .WithGridItemsCount();

        _grid = client.Grid;
        _task = client.UpdateGrid();
        await _task;
    }
```

**Comment by timbze** [comment]
I don't use EF and my sort works. Make sure you have set `.Sortable()` for your GridServer<> code

**Comment by win32nipuh** [comment]
Yes, thnx, now it works! :-)
