### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by win32nipuh** [gustavnavar/Grid.Blazor#119]
I enter text to the Search control and press <Enter> or click button - nothing changed.
How to understand why search does not work?

**Comment by gustavnavar** [comment]
Could you debug your project and share the exception trace?

**Comment by timbze** [comment]
One thing to check, make sure you have set `.Searchable()` for your `GridServer<>` code

**Comment by win32nipuh** [comment]
Thank you, it was the reason.
