### ISSUE TITLE
Consider changing ItemsToDisplay to a function instead of property

### ISSUE THREAD

**Issue by dazinator** [gustavnavar/Grid.Blazor#121]
**Is your feature request related to a problem? Please describe.**
Feature will help eliminate potential source of bugs.

In my `controller`, I was adjusting some pager settings before returning the results:

```csharp
  var pager = server.ItemsToDisplay?.Pager;
            if(pager != null)
            {
                pager.ItemsCount = journals.total.GetValueOrDefault();
                pager.CurrentPage = query.PageNumber ?? 1;
                pager.PageSize = pageSize;
            }           
         
            return Ok(server.ItemsToDisplay);
```

It seems that `ItemsToDisplay` has side-effects and is not a simple property, rather, everytime you access it you get a potentially new result.

So in my case above, doing this:

```
 var pager = server.ItemsToDisplay?.Pager;
            if(pager != null)
            {
                pager.ItemsCount = journals.total.GetValueOrDefault();
                pager.CurrentPage = query.PageNumber ?? 1;
                pager.PageSize = pageSize;
            }           

```

has no impact on the ItemsToDisplay dto that get's returned on the following line, as it has modified seperate copy of it

```
  return Ok(server.ItemsToDisplay);
```
**Describe the solution you'd like**
Perhaps consider changing the `ItemsToDisplay` property, from a property to a method such as `GetItemsToDisplay()` to make it more obvious that it's going to return you a new instance each time it's called.

**Describe alternatives you've considered**
None, I just wanted to document something that caused me an issue, with a possible suggestion for an enhancement.

**Additional context**

**Comment by gustavnavar** [comment]
If you want to change paging info, you must do it before calling the ```UpdateGrid``` method of the ```GridComponent```. 

Any change you do after calling this method shouldn't have any impact on the data you will get, and ```ItemsToDisplay``` overrides all changes on pager information send to the client grid.

**Comment by dazinator** [comment]
> If you want to change paging info, you must do it before calling the `UpdateGrid` method of the `GridComponent`.

I'm adjusting the paging info from the server side not directly from the client side where the grid component is. This is because when data is loaded from the server, I am not using the GridServer to obtain the data, instead I am handling the filtering, sorting, and paging myself with a request to an external API based on parsing the query string sent from the grid client side. Once I have my records I was passing them into GridServer which now thinks there is only 1 page of data because I have already done the paging. I'm adjusting the total again on the paging model so that when the model is sent to the client it displays a page still. It seems to work but yeah ItemsToDisplay is not a simple property and it caught me out when treating it like one on the server side.

If you are happy to leave it as a property I will close this issue.

**Comment by gustavnavar** [comment]
Yes, I prefer to leave it as a property.
