### ISSUE TITLE
CRUD does not work with AutoGenerateColumns()

### ISSUE THREAD

**Issue by faina09** [gustavnavar/Grid.Blazor#122]
I try to use CRUD with **AutoGenerateColumns()**.
I have defined the key in the model using the attribute `[Key]`
Clicking on the pencil calls  `Get(params object[] keys) ` but the object keys is null.
I found that in `GridMvc\SGrid.cs` the method AutoGenerateColumns() ignores that attribute. 
I tried to fix this but again GridBlazor.DataAnnotations.GridAnnotationsProvider is ignoring most of the attributes and also [key]
My final target is to **use only attributes in model class** and NOT the `ColumnCollections` class

To reproduce simply use the GridClient<Model> constructor with no columns and with .AutoGenerateColumns() and try to edit an item.

**Comment by gustavnavar** [comment]
CRUD only works with ```ColumnCollections``` definitions now. I think that make it work also with annotations will require considerable effort, as new attributes in the model class are needed to provide the same information that ```ColumnCollections``` does. This is even more important now that subforms are suppported in CRUD forms.

**Comment by faina09** [comment]
Yes I agree, subforms are surely more important.
I have had a look to implement usage of attributes from model class, and I agree again: it seems to need a lot of code. 
But If I have time I'll try to do some steps: as a first try I would like to implement just **key attribute**.
Am I on the right way working on both `GridMvc\SGrid.cs` method `AutoGenerateColumns()` and in `GridBlazor\DataAnnotations\GridAnnotationsProvider.cs` methods?

**Comment by faina09** [comment]
I implemented some little changes to manage the [key] attribute from the model.
I would like to submit a pull request if you want.

**Comment by gustavnavar** [comment]
Yes, please.
