### ISSUE TITLE
How to fix Grid width?

### ISSUE THREAD

**Issue by win32nipuh** [gustavnavar/Grid.Blazor#124]
How to fix grid width?
For example: 
I have a grid
Id, Name, Modified
I sort the grid by Name, it refreshes and longer or shorter names  appears first and Grid changes width.
I'd like to avoid this size playing. How can I fix a grid width?

**Comment by gustavnavar** [comment]
You can use ```SetWidth``` method in the column definition:

https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Custom_columns.md#column-settings
