### ISSUE TITLE
How to process subGrid row click?

### ISSUE THREAD

**Issue by win32nipuh** [gustavnavar/Grid.Blazor#126]
I have Grid
          SubGrid

For master grid I can process the row click event: 

`<GridComponent @ref="S3GridComponent" T="S3Library22" Grid="@_grid" OnRowClicked="@S3ItemDetails" CustomFilters="@_customFilters"></GridComponent>`

But how I can call a function on subgrid row click?

**Comment by gustavnavar** [comment]
This feature is not supported

**Comment by Oleg26Dev** [comment]
Can you include it to the features plan? It will be very useful.

**Comment by gustavnavar** [comment]
GridBlazor 1.3.30 implements ```OnRowClickActions``` to allow row click for all subgrids.

You can look at this sample https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorServerSide/Pages/GridSample.razor

You have to create a ```List<Action<object>>()``` and add all row click method for nested subgrids in the same order they are nested:

```c#
    _rowClickActions = new List<Action<object>>();
    _rowClickActions.Add(OrderInfo);
    _rowClickActions.Add(OrderDetailInfo);
```
And finally you have to pass the list as parameter of the ```GridComponent```:

```c#
    <GridComponent T="Order" Grid="@_grid" OnRowClickedActions="@_rowClickActions" />
```

**Comment by win32nipuh** [comment]
Thanx! I will try it, it seems it can solve the problem.

**Comment by gustavnavar** [comment]
The ```OrderDetailInfo(object item)``` action parameter is the clicked item on the subgrid.
