### ISSUE TITLE
Crud - Delete unique (last) row , grid not emptied.

### ISSUE THREAD

**Issue by alvisemion** [gustavnavar/Grid.Blazor#129]
I'm using a crud subgrid in blazor wasm, web assembly client project.
When i delete the last row, GridClient call my web service that return 404, no rows found.
The result is that the last (and unique) row stay displayed on grid.

**Expected behavior**
Method `Task UpdateGrid()` in CGrid.cs should manage 404 not as error but  as empty result.

![image](https://user-images.githubusercontent.com/36442664/76230358-e09d3d00-6223-11ea-8139-05ba98d5b92f.png)

I've modified my web service to serve 200 status code with no response instead of 404 status code but with same result, last row stays in grid.

![image](https://user-images.githubusercontent.com/36442664/76231993-55717680-6226-11ea-9214-fb0bd8f6cd1b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Google Chorme
 - Version 80.0.3987.132

**Comment by gustavnavar** [comment]
You should use the ```UpdateGrid()``` method of the ```GridComponent``` instead of ```CGrid```: https://github.com/gustavnavar/Grid.Blazor/issues/70#issuecomment-574610823

**Comment by alvisemion** [comment]
I stil didn't find how invoke Component.UpdateGrid.

My razor page use GridComponent
```
@if (_task.IsCompleted)
{
    <div class="row">
        <div class="col-md-12">
            <GridComponent @ref="Component" T="Ente" Grid="@_grid"></GridComponent>
        </div>
    </div>
}
```
In code section, in "Task OnParametersSetAsync()" method i call client.UpdateGrid()
```
protected override async Task OnParametersSetAsync()
  {
   ...
  _grid = client.Grid;
  _task = client.UpdateGrid();
  await _task;
}

```	
Where and when should i use Component.UpdateGrid()?
Thanks for support.

**Comment by gustavnavar** [comment]
You can use an ```AfterDelete``` event (https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Events.md#events-and-crud-validation)

Something similar to:
```c#
    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            Component.AfterDelete += AfterDelete;
        }
    }

    private async Task AfterDelete(GridDeleteComponent<Order> component, Order item)
    {
        Component.UpdateGrid();
    }
```
