### ISSUE TITLE
Highlight the sorted column with a different color in the column name.

### ISSUE THREAD

**Issue by pcecamacho** [gustavnavar/Grid.Blazor#131]
Currently we have the arrow up and down to identify the column sorted including the ascendant or descendant form.

Is it possible include a color for the column sorted?, could be just on the column name (no remove the arrow).

Thank you

**Comment by faina09** [comment]
you can simply use css. For example to have a bg color to evidentiate the arrow, try adding this:

```
.grid-header-title.sorted.sorted-asc .grid-sort-arrow { background-color: #b6ff00; padding-right: 10px; padding-left: 10px }
.grid-header-title.sorted.sorted-desc .grid-sort-arrow { background-color: #ffd800; padding-right: 10px; padding-left: 10px}
```

**Comment by pcecamacho** [comment]
Thank you!
