### ISSUE TITLE
custom CRUD Razor Logic issues

### ISSUE THREAD

**Issue by garberlog** [gustavnavar/Grid.Blazor#132]
**Describe the bug**
When using a Custom CRUD Component for a CRUD grid, an issue occurs where built in Razor C# Logic like that described in [this tutorial](https://www.w3schools.com/asp/razor_cs_logic.asp) no longer functions.

**To Reproduce**
1.  Create a CRUD grid inside a Blazor project
2. Create a CustomCreateComponent Create.razor with the code: 
`
@if (test) {
  <label>failed</label>
} else {
  <label>Succeeded</label>
}

@code { 
  bool test = true; 
  protected override async Task OnInitializedAsync() { await Task.Delay(
    TimeSpan.FromSeconds(1));
    test = false; 
  }
}
`
3. When you run the program and go to the create a new item with your custom CRUD component it will show failed even after the test variable is turned false to switch to succeeded.
4. Now go back and switch the Nuget package to 1.3.29 and the program will work as intended.

**Expected behavior**
When this works the program will automatically switch between the conditions of the if statement when the result of the condition changes.

**Screenshots**
My code running on GridBlazor Nuget package 1.3.29
![image](https://user-images.githubusercontent.com/9215932/76554079-9c9c7900-646b-11ea-80ad-feb53f06aa5a.png)

My code running on GridBlazor Nuget package 1.3.30
![image](https://user-images.githubusercontent.com/9215932/76554074-973f2e80-646b-11ea-98a3-9a4ed6370e57.png)

**Desktop:**
 - OS: Windows
 - All Browsers

**Additional context**
This issue only exists in the newest nuget package for GridBlazor (1.3.30), when using 1.3.29 there is no issue.

To make sure my instructions worked I made my own version of the project for testing and decided to put it on github so you can test it quicker. [Click Here](https://github.com/garberlog/GridBlazor-Issue-Test)

**Comment by gustavnavar** [comment]
The last version of CRUD components control UI refreshing as explained here: https://docs.microsoft.com/ca-es/aspnet/core/blazor/lifecycle?view=aspnetcore-3.1#suppress-ui-refreshing

If you want to refresh CRUD forms you can use something similar to:

```c#
@inherits GridCreateComponent<WeatherForecast>
@using BugTest.Data
<h3>Create</h3>

@if (test) {
    <label>failed</label>
} else {
    <label>Succeeded</label>
}
@code {
    bool test = true;
    private bool _shouldRender = false;

    protected override bool ShouldRender()
    {
        return _shouldRender;
    }

    protected override async Task OnInitializedAsync() {
        await Task.Delay(TimeSpan.FromSeconds(1));
        _shouldRender = true;
        test = false;
    }

    protected override void OnAfterRender(bool firstRender)
    {
        _shouldRender = false;
    }
}
```

**Comment by garberlog** [comment]
Thank you for the quick response, I was able to change my system to use this method and it works fine. 

PS: I also just wanted to thank you for the exceptional work that you've done on this project, this component has been very useful and the documentation is excellent.
