### ISSUE TITLE
Question: FilterChanged Event

### ISSUE THREAD

**Issue by dazinator** [gustavnavar/Grid.Blazor#133]
Question relates to the FilterChanged event on the client side: https://github.com/gustavnavar/Grid.Blazor/blob/f40f809349c30730daead1259fc16f9ed20218ab/docs/blazor_client/Events.md

Suppose a filter is added, removed, or updated. Does this event fire after the grid has loaded new data from the server (i.e the http request) or does it fire prior to this happening?

I need to detect when the filters have changed so that I can reset the page back to 1 before the grid queries for its data. The reason being, say you are on page 5, and then you add a filter - if the query gets sent to the server, it will now be asking for page 5 of a newly filtered result set - of which there may only now be 3 pages, resulting in empty results.

So i'd like to be able to detect when the filters are changed, prior to the grid querying the server, and then reset the page number to 1..

**Comment by gustavnavar** [comment]
It's fired after the grid has been updated.

Following your example, if you are on page 5 and a new filter is applied, the server returns the 3rd page and the front-end shows that page. After that, the event is fired.

**Comment by dazinator** [comment]
> Following your example, if you are on page 5 and a new filter is applied, the server returns the 3rd page and the front-end shows that page. After that, the event is fired.

I am seeing that, if you are on page 5, and a new filter is applied, the request sent to the server includes pagenumber = 5 as a query string param as well as the filters.

I am having to manually parse the query string params on the server in order to build a query to a third party API, and that API takes pageNumber as a param, as well as filters. In this case I pass pageNumber = 5 and the query params. The service responds with 0 results because with the filters i'm now sending there are only 3 pages worth of results and I am requesting page 5. I am honestly not sure whether you could consider that a bug in the third party API or not (i.e should it then just return Max page number rather than 0 results?) however without that bug being fixed, I have to assume that whenever a filter is changed, I need the client grid to reset back to page 1 so it sends pageNumber=1 in its request to the server. I was hoping to find an event to let me do that but it doesn't like this is it. Any suggestions?

**Comment by gustavnavar** [comment]
The ```GridPager``` object in the ```GridMvcCore``` package calculates the number of pages after filters are applied and compares it with the ```CurrentPage``` value. If the ```CurrentPage``` value is greater than the number of pages, the back-end returns the last page:

```c#
    PageCount = (int) (Math.Ceiling(ItemsCount/(double) PageSize));
    if (CurrentPage > PageCount)
        CurrentPage = PageCount;
```

You should so something similar in your back-end, but returning the first page. You can do this in your back-end or in the service that queries your back-end.

**Comment by dazinator** [comment]
Thanks for this, we will aim to do something similar.
