### ISSUE TITLE
How to populate Grid from large database table?

### ISSUE THREAD

**Issue by win32nipuh** [gustavnavar/Grid.Blazor#134]
I have a db table with 100 000 rows.
Are there any advices or tricks how to populate a Grid by records from large table?
In case I do not use EF and do reading using my DBService.
May be it is possible to read by parts but how to? And how to re-read from the db?

**Comment by gustavnavar** [comment]
You have to pass an ```IQueriable<>``` object to the ```GridServer``` constructor.

All queries are managed by the ```SGrid``` object on the back-end. It builds Linq queries on top of the ```IQueriable<>``` object that you provide, and finally executes them. So only the items to be shown on the screen are retrieved from the database.

Of course it you have indexes on the database table, queries will execute faster.

**Comment by Oleg26Dev** [comment]
It is my starting Blazor app, I do not use any ORM for now, do all queries "manually". I am porting the old WinForms+PostgreSQL client->server app. May be later I will use EF but will see.

**Comment by gustavnavar** [comment]
My recommendation is to use a ORM, preferiably ER. I don't see any efficient way to to write all queries manually.

**Comment by win32nipuh** [comment]
Hi Gustavo, I have used your advice and I switched to EF and grid works fine. Thanx!

**Comment by prabhakarreddy1234** [comment]
So, is it mandatory to use ORM ? I'm using Cosmos SQL API and passing IEnumerable<Entity> to GridServer Constructor. Filtering, Sorting, Search doesn't work.  Is there a way i can switch off on-demand db data fetching and load all the data initially?

**Comment by gustavnavar** [comment]
You could try the EF Core provider for Cosmos:
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.Cosmos/

**Comment by prabhakarreddy1234** [comment]
Thanks. I will give it a try but is there a way i can make all features work without ORM ?

**Comment by gustavnavar** [comment]
It's necessary some component that will apply Linq to the database. If you want that this be executed on the database an ORM is mandatory.

The other option is to provide a full ```List<T>``` to the ```GridServer<T>``` constructor. Take a look at
this sample https://gridblazor.azurewebsites.net/comparer

**Comment by prabhakarreddy1234** [comment]
I passed full `List<T>` to `GridServer` but no luck. While sorting the arrows turns up and down but data doesn't refresh. I see that a call is being made to server to fetch the data and `query` object has all the query params correctly but somehow the queries are not applied to the Collection. 

I raised a bug on this with Client and Server Setup. Can you please take a look and see if you find something wrong there.

**Comment by gustavnavar** [comment]
Could you share the source code of your project?
