### ISSUE TITLE
Initial grouping?

### ISSUE THREAD

**Issue by Oninaig** [gustavnavar/Grid.Blazor#137]
Currently it is very simple to set up an initial filtering for a given column, but does that some functionality exist for grouping or do you have to currently manually add your grouping to the current query and refresh the grid?

Also, can initial filtering be done via AddQueryParameter as well? I ask because I get "parameter name cannot be grid-filter" when doing the following:

`_grid.AddQueryString("grid-filter", filter);`

What I am trying to do is "preserve" the current filters between navigations, and I see that there is an 
`AddFilter(IGridColumn column, FilterCollection y)` method, but when this code runs the grid on the "new" page that you are navigating to isn't finished being created yet. Everything for the grid is defined, but I have not yet called `_grid.UpdateGrid()` to execute the actions that define each column. Because of this, I don't really have any columns yet that I could pass into that `AddFilter` method, I only have `Action<MyColumnType>`

**Comment by gustavnavar** [comment]
You can use the following code for initial settings of filtering and grouping:
````c#
        var query = new QueryDictionary<StringValues>();
        query.Add("grid-filter", "Customer.Country__1__usa");
        query.Add("grid-sorting", "Customer.CompanyName__0__1");

        var client = new GridClient<Order>( ...
```
