### ISSUE TITLE
GridBlazor leaks bundleconfig.json into dependent project

### ISSUE THREAD

**Issue by IvanJosipovic** [gustavnavar/Grid.Blazor#14]
**Describe the bug**
GridBlazor 1.0.0 leaks bundleconfig.json into dependent project

**To Reproduce**
- Create new Blazor Project
- Add GridBlazor 1.0.0 Nuget package
- "bundleconfig.json" will now be visible in the project

**Expected behavior**
"bundconfig.json" shouldn't be added to the depended project

**Screenshots**
![image](https://user-images.githubusercontent.com/9521987/65737856-b819f000-e094-11e9-8496-13677b526e27.png)

**Comment by gustavnavar** [comment]
I've uploaded new nuget packages to fix it:
- GridBlazor 1.0.1
- GridMvcCore 2.8.9

You have to upgrade both packages.
