### ISSUE TITLE
Guidance on Select All, Unselect All, and Select each item

### ISSUE THREAD

**Issue by dazinator** [gustavnavar/Grid.Blazor#140]
**Is your feature request related to a problem? Please describe.**
I'm using the wasm version of the grid on a blazor page.

I'd like to add a checkbox called "Select All" - most likely directly in the column header of a "checkbox column". The checkbox column will display a checkbox for each row in the grid, and allows that row to be "Selected" or not by the user. For now, I've placed the "Select All" checkbox directly above / outside the grid and it's not in the column header of the checkbox IsSelected column.

I have started on this by adding an "IsSelected" property to my data items that the grid is bound to, and using a checkbox cell / column with the checkbox bound to the items' "IsSelected" property.

There are some touch points though that I am still thinking through and would love any guidance you had to offer so that I can achieve this with decent performance and using the grid properly.

1. When I click the select checkbox for an individual row, this sets the IsSelected property on the data item  (because its bound to that property). However when all items / rows currently displayed have been selected (i.e I click on the last remaining unselected row to select it), I want to update my "Select All" checkbox so that it also now becomes checked. Likewise if a then de-select any individual rows by clicking on a select checkbox to uncheck it, I want to update the "Select All" checkbox to be unchecked. 
2. When the user clicks the "Select All" checkbox to check it, I need to set the checkbox for each item in the grid to checked. I assume this is just a case of looping through all the underlying data items and setting IsSelected to true - however I am not 100% sure at this time whether I will then need to call UpdateGrid() and StateHasChanged in the parent page to force the grid to re-render. Is there any advice how to best handle getting the grid to re-render from the data items, with minimal overhead I'd be interested. For example - I'd like to re-render the rows for the grid without it performing any more backend requests etc - is it just a case of calling grid.UpdateGrid() and StateHasChanged() on the page?

3. When a user unchecks the "Select All" checkbox, i'd need to do the same as above but setting each row to unchecked.

I raise this because it's functionality I have seen fairly commonly before, and not sure if you already have features to enable this kind of thing or if there is a sample, or suggested pattern for achieving it etc before I go my own way!

Thanks

**Comment by dazinator** [comment]
I could also see this manifesting a potential feature whereby you don't need to extend the underlying data item to include a "Select" experience - i.e whether an item is selected or not could be governed by metadata and API's such as:

- Grid.AllowMultiSelect
- Grid.SelectedItems
- Grid.ShowSelectColumn

etc.

**Comment by dazinator** [comment]
I discovered the grids native row selection functionality: https://github.com/gustavnavar/Grid.Blazor/blob/cd27dad52290a360fec36e47782d30249161f7ed/docs/blazor_client/Selecting_row.md

However I think as I need to display a checkbox column, I wasn't really sure how best to adapt it, instead I have used my own mechansims.

**Comment by gustavnavar** [comment]
Maybe these functionality can help you:
https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/Button_components.md

**Comment by gustavnavar** [comment]
I've added a new functionality for checkbox columns in GridBlazor version 1.4.1:
https://gridblazor.azurewebsites.net/checkbox

The documentation is [here](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/Selecting_row.md#setcheckboxcolumn-method)
