### ISSUE TITLE
Exclude cell from selecting row

### ISSUE THREAD

**Issue by martinscholz83** [gustavnavar/Grid.Blazor#142]
When selecting a row in grid i'm showing a Bootstrap Modal window. In on cell i have a custom button which navigates to a details page. When not hit the button exactly in the middle, the modal shortly pops up before the navigation. Is there any way to tell a cell that it's excluded for selecting. Or maybe to check in the click event what cell was the sender and cancel the event?

**Comment by gustavnavar** [comment]
Are you using ```@onclick:stopPropagation``` in the button element?

**Comment by martinscholz83** [comment]
<img width="429" alt="Bildschirmfoto 2020-04-14 um 11 11 57" src="https://user-images.githubusercontent.com/19551763/79207258-c406ad00-7e40-11ea-9d99-e3483a529e8f.png">
