### ISSUE TITLE
Client side grid when adding an empty filter - prevent http reqeust

### ISSUE THREAD

**Issue by dazinator** [gustavnavar/Grid.Blazor#144]
Our desired flow for client side grid usage, is that a user "adds a filter" first to the grid, and then they can edit the filter value afterwards, whilst its added.

So we have some UI where a user clicks a button to add a filter:
```
FilterCollection filters = new FilterCollection(GridFilterType.Condition.ToString("d"), null);
 await _grid.AddFilter(selectedColumn.Item, filters);
```

as you can see, at this point, we have just a default filter collection without any value for the filter.

We then display an editable UI for the filter value, where the user can enter and change the value.

The issue we have is that as soon as we call 
```
 await _grid.AddFilter(selectedColumn.Item, filters);

```

To add an empty filter, this causes a request to hit the server. Ideally we'd like to prevent the request from being sent to the server until the user edits the filter value.

Is there anyway we could have some overload of: ` await _grid.AddFilter(selectedColumn.Item, filters);` that allows us to prevent the inital requery to the server?

**Comment by gustavnavar** [comment]
Maybe you could the filter to the ```CGrid<T>``` object using  its ```AddFilterParameter(column, filters)``` method.

And when you want to activate the filter you could use the ```UpdateGrid``` method of the ```GridComponent```.
