### ISSUE TITLE
How to return to the grid state?

### ISSUE THREAD

**Issue by Oleg26Dev** [gustavnavar/Grid.Blazor#147]
I have a webpage with grid and button <Edit>. 

I select Nth  grid's page and Mth grid row.
On click I get selected grid row and navigate to the edit page

```
 <button @onclick="EditCustomerForm" class="btn btn-primary">Edit</button>
...
 async Task EditCustomerForm()
    {
        string ReturnUrl = @"customers";
 NavigationManager.NavigateTo($"/editcustomer/{CustomerItem.Id.ToString()}/{ReturnUrl}/{GridState}");

```

When I click <Save> or <Back> on EditCusomer form I'd like to return to the page Customers with grid to the same Nth  grids page and Mth grid row should be selected. But  every time the 1st grids page and the 1st row selected. How to return to the same grid state (page and row)?

**Comment by DSBhogal** [comment]
Have your component that contains the grid accept a string parameter like so:

`@page "/pagename/{gridstate}"` - Page directive
`[Parameter] public string GridState { get; set; }` - Parameter

You'll need to split off your code that creates the grid into separate methods for this to work:

![Grid Blazor methods](https://user-images.githubusercontent.com/33750091/82441030-33ea0200-9a95-11ea-8e77-125d4f4a9042.JPG)

As you can see above I use the GridState parameter every time the method is ran. As long as you pass the gridstate back to the index after edit/create etc. you should return to same grid state
