### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by balajipitchumani** [gustavnavar/Grid.Blazor#15]
Is it possible to add a tooltip to a column value?

**Comment by gustavnavar** [comment]
Yes, you can have tooltips or other components in a column cell. You have to use the RenderComponentAs method when you create the column grid. But you must also use a tooltip blazor component such as MatBlazor or BlazorStrap

I´ve just uploaded some samples where the Date column has tooltips using BlazorStrap:
http://gridblazor.azurewebsites.net/

The source code of the Razor Component is:
https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorClientSide.Client/Pages/TooltipCell.razor

And the column definition is:
c.Add(o => o.OrderDate, "OrderCustomDate").Titled("Date")
            .SetWidth(120).RenderComponentAs<TooltipCell>();

**Comment by balajipitchumani** [comment]
MANY MANY THANKS...great work.
