### ISSUE TITLE
Updating grid after delete

### ISSUE THREAD

**Issue by DSBhogal** [gustavnavar/Grid.Blazor#151]
**Question/Potential Issue**
I have implemented a delete button within the cell of my grid. On delete of a record, instead of going to a new page a sweet alert modal appears to confirm/cancel the delete. When I confirm the delete, I call the UpdateGrid() function from the CGrid parameter I have within my button component. 

The grid does not refresh and record remains in the grid until I refresh the page. It's probably an issue with the way I'm doing this or using the UpdateGrid() function. I have seen related issues/questions, I tried creating a reference of my component and passing that through as an object to my button component but it comes in as null.

How would you recommenced I update the the items in the grid after deleting record when I'm on the same page as the grid?

*Grid Index*
![GridIndex](https://user-images.githubusercontent.com/33750091/79955201-5a0c8a00-8476-11ea-9708-bbb20f5842a1.JPG)

*Delete Button*
![DeleteButton](https://user-images.githubusercontent.com/33750091/79955200-5973f380-8476-11ea-96cb-5dd03e4f55d9.JPG)

**Comment by gustavnavar** [comment]
The ```UpdateGrid``` method of the ```Grid``` object requeries the grid, but not refreshes the component. You must use the ```UpdateGrid``` method of the ```GridComponent``` to do both.

Fist you must use a reference to the component:
```c#
    <GridComponent @ref="Component" T="Order" Grid="@_grid"></GridComponent>
```
and then call its ```UpdateGrid``` method:
```c#
    await Component.UpdateGrid();
```

**Comment by DSBhogal** [comment]
I have since fixed the issue I had stated above. Whether this is the best way to achieve what I wanted I'm unsure. I did reference the component and call update grid but that didn't work

**FIX**

I changed the button to pass my delete action through to the button component

![Button](https://user-images.githubusercontent.com/33750091/79974451-44f12480-8491-11ea-8a04-9f5f9922ba53.JPG)

Using the action passed through I invoke the method within the OnClick function

![ButtonComponent](https://user-images.githubusercontent.com/33750091/79974457-4589bb00-8491-11ea-9d05-c7c213d7191a.JPG)

Once the method has been called, it does the delete. Calls a method to refetch the grid, once that has done this.StateHasChanged() rerenders the component. Please note StateHasChanged does not work alone, this. is required. Finally a toast is shown to notify the user

![DeleteMethod](https://user-images.githubusercontent.com/33750091/79974460-46225180-8491-11ea-9aec-d2f2d104b12d.JPG)
