### ISSUE TITLE
Search on hidden columns not working

### ISSUE THREAD

**Issue by martinscholz83** [gustavnavar/Grid.Blazor#152]
**Describe the bug**
I have some hidden columns like this
```
c.Add(true).RenderValueAs(setting => string.Join(",", setting.Values.Select(o => o.Meaning ?? "").ToArray()));
```
where i just add some extra data to be searchable. When trying to search for rows with that hidden fields nothing is shown.
**To Reproduce**

**Expected behavior**
Rows with the hidden column should be searchable.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.5.1

**Comment by martinscholz83** [comment]
It seems that its only not working when you have columns which don't have a base model. For columns like `c.Add(o => o.Component, true);` it is working.

**Comment by gustavnavar** [comment]
Yes, it works only for connected columns (e.g. ```c.Add(o => o.Component, true)```) because filtering is done in the database.

But it doesn't for non connected columns (e.g. ```c.Add().RenderAs...```)

**Comment by martinscholz83** [comment]
That make sense. So let me try to explain what i want to achieve. See the following Model
```
public class Value
    {
        public int ID { get; set; }
        public string StringValue { get; set; }
        public string IntValue { get; set; }
        public string Meaning { get; set; }
        public string Reference { get; set; }
        public Setting Setting { get; set; }
        public int SettingID { get; set; }
    }

public class Setting
    {        
        public int ID { get; set; }
        ...
        public ICollection<Value> Values { get; set; }
        ...
    }
```
Is there any way to make all values a setting can have searchable in the grid?

**Comment by gustavnavar** [comment]
The best option is to use "keyless entities": https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types

The SQL View can be as follows:

```SQL
SELECT s.*,
(SELECT STRING_AGG( ISNULL(Meaning, ' '), ',') FROM [Value] WHERE  SettingID =  s.ID) AS Meanings
FROM [Setting] AS s
```
For more info, this subject was discussed here: #39

**Comment by martinscholz83** [comment]
Thx. I will give it a try.

**Comment by memerson** [comment]
Are there other alternatives?

For my use case, I'm basically using the grid to display the contents of arbitrary spreadsheets. I don't know what the columns will be until runtime. I need the columns to reflect whatever columns are defined in the spreadsheet and then be able to filter and search the data.
