### ISSUE TITLE
Filter, Search, Sort doesn't apply in Blazor Server app

### ISSUE THREAD

**Issue by prabhakarreddy1234** [gustavnavar/Grid.Blazor#153]
**Describe the bug**
Filter, Search, Sort are not applying on the server data.

I'm Using  `Grid.Blazor` in my blazor server application. `Paging` works fine but `Filter, Sort, Search` doesn't work at all. Always returned the same data back to the client.

**Server Side:**
```
    var server = new GridServer<ExerciseList>(exercises, new QueryCollection(query),
                true, "QuickExerciseGrid")
                .Selectable(true)
                 .Searchable(true,true)
                .Sortable(true)
                .Filterable(true)
                .WithPaging(pageSize)
                .WithGridItemsCount("Exercises")
                .ClearFiltersButton(true);

                return server.ItemsToDisplay;
```
**Client Side:**
  ```
var client = new GridClient<ExerciseList>(async q => await ExerciseService.GetQuickExcerciseLists("", columns, q, 10), query, false, "QuickExerciseGrid", columns)
        .Selectable(true)
        .SetStriped(true)
        .Filterable(true)
        .Sortable(true)
        .Searchable(true,true)
        .WithPaging(10)
        .WithGridItemsCount("Exercises")
        .ClearFiltersButton(true);

        _grid = client.Grid;

        // Set new items to grid
        _task = client.UpdateGrid();
        await _task;
```
I'm sure i'm missing something obvious but spent few hours on it. Any pointer is highly appreciated.
I confirm that `exercises` object is `IEnumerable`. Initially grid loads fine but when filter,sort or search performed then nothing happens.

**Comment by win32nipuh** [comment]
Check these issues
https://github.com/gustavnavar/Grid.Blazor/issues/119
https://github.com/gustavnavar/Grid.Blazor/issues/118

**Comment by prabhakarreddy1234** [comment]
Thanks. But i looked at those issues already. My Client and Server configurations have `Searchable()`, `Sortable()`, `Filterable()` and still it doesn't work.

After debugging, i see that `BeforeItems` and `AfterItems` are same. So something is skipping the filters.

**Comment by prabhakarreddy1234** [comment]
It's working now. Closing It.

Somehow i needed to initialise a new collection in the repository and add data to it and return it back.
