### ISSUE TITLE
Scrollable Grid

### ISSUE THREAD

**Issue by prabhakarreddy1234** [gustavnavar/Grid.Blazor#157]
Is there a way to apply `vertical scrolling` to the grid with fixed header and fixed rowcount field at the bottom. It would be really useful if it's not possible as of now.

Please point me to the link if it's already possible with BlazorGrid.Server.

**Comment by gustavnavar** [comment]
Grid is based on html ```table``` element. All tests I've done adding scrolling to the table body doesn't line up the cells in ```thead``` with the ones in ```tbody```.

**Comment by prabhakarreddy1234** [comment]
Does it work if we apply style to `tbody` to scroll.

**Comment by gustavnavar** [comment]
I've have not found a pure css solution for this issue.

When applaying style to ```tbody``` for scrolling is when cell alignment issues appear between ```thead```and ```tbody```.

If you run the demo projects including these lines in the ```site.css``` file:
```css
thead, tbody {
    display: block;
}

tbody {
    height: 400px;
    overflow-y: auto;
    overflow-x: hidden;
}
```

you will get these wrong alignments:
![Captura (114)](https://user-images.githubusercontent.com/30131949/82924239-593aac80-9f7c-11ea-8a2e-279df6879278.png)

![Captura (115)](https://user-images.githubusercontent.com/30131949/82924327-766f7b00-9f7c-11ea-83a4-c9758ca4d883.png)

I see 2 options here:
- apply scrolling to the full table
- add code (javascript?) to calculate all columns' width for the header and the body.

**Comment by mathi82** [comment]
Hi @gustavnavar , 

Can you not move the header/footer outside of the table? 
Either nested table where parent has header/foot and nested table has the rows or wrap the able with divs?
This would allow the entire table to scroll (table has no header) while the grid headers will remain in place.

**Comment by prabhakarreddy1234** [comment]
So there is no way to fix the header and scroll only the body ?

**Comment by rdavi10471a2** [comment]
I am also looking how to do this particularly when there are stacked headers

**Comment by gustavnavar** [comment]
GridBlazor 2.1.0 supports  table dimensions configuration and scrolling:
- https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/Grid_dimensions.md
- https://gridblazor.azurewebsites.net/autogeneratedcolumns
