### ISSUE TITLE
Checkbox column disable

### ISSUE THREAD

**Issue by timbze** [gustavnavar/Grid.Blazor#159]
It would be nice to be able to disable the Checkbox column based on  a value from the T item.

For example, SetCheckboxColumn has this for parameter 2.
`expression: it's a Func<T, bool> to define the initial value of the checkbox for each row`

It would be good to have optional parameter 3 like this:
`readonly: a Func<T, bool> to define whether the checkbox can be changed or not`

**Comment by gustavnavar** [comment]
The package GridBlazor 1.5.4 includes this feature
