### ISSUE TITLE
Extending Sorting

### ISSUE THREAD

**Issue by balajipitchumani** [gustavnavar/Grid.Blazor#16]
Is it possible to provide a custom c# code while doing the sorting on a column - for ex: if column contains nulls, then sort only the not-null rows and then add null rows at the end in the grid. Similarly for blank strings as well as for null dates etc.

**Comment by gustavnavar** [comment]
Sorting is executed by  the database.  This is done by performance reasons. We can not force how ordering is done  in the back-end by each database engine.

This is how the component works. The component gets the expression used to create each column (e.g. column.Add(o => o.OrderDate)) and applies one of OrderBy or OrderByDescending methods to the query (e.g. OrderBy(o => o.OrderDate)). This query is send to the back-end project that manages the database. So it´s finally the Entity Framework provider that the back-end project uses  the one that will perform the ordering.

**Comment by balajipitchumani** [comment]
Understand the rationale now. In my previous code behind or razor pages, used to handle manually and hence was trying to find similar solution in blazor also.

Let me find the database way of doing these..

**Comment by balajipitchumani** [comment]
Is it possible to somehow know the currently clicked sorting column and the current order required and get handle to event whenever sortable column header is clicked?

**Comment by gustavnavar** [comment]
You can get the sorted column name with this string parameter cgrid.Settings.SortSettings.ColumnName.

And the direction with this Enum parameter cgrid.Settings.SortSettings.Direction. The possible values are GridSortDirection.Ascending and GridSortDirection.Descending.
