### ISSUE TITLE
IGridColumn<T> ToolTip(string tooltip);

### ISSUE THREAD

**Issue by alvisemion** [gustavnavar/Grid.Blazor#160]
Each column can be titled:
IGridColumn<T> Titled(string title);

Each column could be "tooltiped"?
A tooltip is an optional text, visible, for example, on hover on grid column header or on hover on (read,edit,delete)view's column label 
This text could be useful to describe behaviour of column for the business logic.
This way column title could be compacted

**Comment by timbze** [comment]
Gives me another idea about cell tooltip. Sometimes I render truncated text if it's a long string, but having tooltip when certain condition is met (in this case string is longer than x amount of chars) would be something I'd use. But not very important for me.

**Comment by gustavnavar** [comment]
You can use a tooltip component as as MatBlazor or BlazorStrap. It was discussed in a earlier issue:
https://github.com/gustavnavar/Grid.Blazor/issues/15

And you can fix the row height and use ellipsis for text overflow, discused here:
https://github.com/gustavnavar/Grid.Blazor/issues/141

**Comment by alvisemion** [comment]
That's great, but my idea was a tooltip on hover of grid header, not on every grid cell.
The same tooltip could be shown on hover of crud autogenerated forms field's label; or, even, could be shown below the form group "as text-muted".

![image](https://user-images.githubusercontent.com/36442664/81393260-5b011500-9120-11ea-8b85-046907a3e81d.png)

![image](https://user-images.githubusercontent.com/36442664/81392674-4b350100-911f-11ea-80cd-b6ca43b33e2c.png)

**Comment by gustavnavar** [comment]
Package version 1.6.5 supports this feature. More info [here](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Custom_columns.md#header-tooltip)

**Comment by alvisemion** [comment]
It works like a charm. 
Thanks!
