### ISSUE TITLE
export to excel or csv

### ISSUE THREAD

**Issue by faina09** [gustavnavar/Grid.Blazor#161]
I realized a simple **exporter to csv or excel** (using DocumentFormat.OpenXml) that writes all the records from a grid to a file when the user push the 'export' button in the razor page.

Now I would like to add to the exported recordset the same filters that are applied to the Grid, i.e. I want to use `_grid.Query` and apply the conditions to the `IQueryable<T> items` in `context.<T>`.

I can manually convert each KeyValuePar contained in `GridShared.Utility.QueryDictionary<StringValues>` to have a where clause, but I am sure that already exists a method to do this; can you help me?

If interested I can share my exporter.

Thank you

**Comment by timbze** [comment]
Not sure if I can help you, but just a hint. Do you need all data exported? CGrid.Items has list of items that are displayed only, if your aim is just to export filtered results. Not sure how exactly this would work with pagination though.

**Comment by faina09** [comment]
@timbze  tnx, but this does not work on my solution, I redirect to a MVC page using as parameters the table name and the query to exctact filtered items

**Comment by gustavnavar** [comment]
Package 1.6.1 has new functionality to export the grid to an excel file.

The documentation is here: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Excel_export.md

**Comment by faina09** [comment]
great! thank you a lot!
