### ISSUE TITLE
SubGridComponent OnParametersSetAsync() is called twice

### ISSUE THREAD

**Issue by timbze** [gustavnavar/Grid.Blazor#162]
I successfully set up a subgrid, but I notice that OnParametersSetAsync() of SubGridComponent.razor.cs is called twice every time a subgrid is loaded. This causes the data to load twice. Because of the way my db connection is set up, it caused an issue but I can do a work around so that it works for me. But it looks like it's an issue that should be fixed.

Here's the relevant code, and both times it runs CreateSubGridComponent()
```csharp
protected override async Task OnParametersSetAsync()
{
    if (GridPosition < GridComponent.IsSubGridVisible.Length 
        && GridPosition < GridComponent.InitSubGrid.Length)
    {
        _visible = GridComponent.IsSubGridVisible[GridPosition];
        _init = GridComponent.InitSubGrid[GridPosition];

        if (_visible && (_grid == null || _init))
        {
            GridComponent.InitSubGrid[GridPosition] = false;
            _grid = await GridComponent.Grid.SubGrids(Values.Values.ToArray());
            _grid.FixedValues = Values;
            _subGridRender = CreateSubGridComponent();
        }
    }
}
```

**Comment by gustavnavar** [comment]
The second time that ```OnParametersSetAsync``` is called either the ```_grid``` object should be not null or ```_init``` variable should be false. So the ```CreateSubGridComponent``` shouldn't be called twice. Could you verify that this is how it works for you?

**Comment by gustavnavar** [comment]
Package 1.6.1 should call  ```OnParametersSetAsync``` only once.

**Comment by timbze** [comment]
Thank you! It works now
