### ISSUE TITLE
Nullref in TotalsGridItemsProcessor

### ISSUE THREAD

**Issue by memerson** [gustavnavar/Grid.Blazor#165]
I'm trying to provide my own implementations of GridShared.GridColumns.IGridColumn and hitting a nullref because the framework assumes that columns provided to the grid column collection inherit from the column base classes you provided. Here's the code from TotalsGridItemsProcessor (lines 30 - 38):

```
GridColumnBase<T> gridColumn = column as GridColumnBase<T>;
if (gridColumn == null || gridColumn.Totals == null)
{
    gridColumn.IsSumEnabled = false;
    gridColumn.IsAverageEnabled = false;
    gridColumn.IsMaxEnabled = false;
    gridColumn.IsMinEnabled = false;
    continue;
}
```

If gridColumn doesn't inherit from GridColumnBase<T> then it's a guaranteed nullref.

Maybe you can save me some time if I'm barking up the wrong tree: is this framework really intended to be extensible by providing my own implementations of the interfaces it uses, or would you suspect I'm going to hit a lot problems like this?

**Comment by gustavnavar** [comment]
Package version 1.6.4 should work for you.

You will have to create your own column builder implementing the ```IColumnBuilder<T>``` interface.

Then you can use the new column builder as a parameter of ```GridClient``` and ```GridServer``` constructors.

**Comment by memerson** [comment]
Thanks a ton!
