### ISSUE TITLE
Is there a way to set checkbox column programatically?

### ISSUE THREAD

**Issue by timbze** [gustavnavar/Grid.Blazor#168]
Right now I can set initial value for checkbox component. Is it possible to change the value programmatically? I've been hacking around with the code but can't make something work properly yet, but maybe just missing something.

**Comment by gustavnavar** [comment]
The GridComponent object has a property to control checkbox values:
```c#
public QueryDictionary<List<int>> CheckedRows { get; internal set; }
```
But it's currently defined as internal.

**Comment by timbze** [comment]
I tried almost a whole day to get it working but this specific way did not come to my mind, so I ended up implementing my own checkbox component. Not sure if I'll be back to trying to use it or not, but probably won't be happening right now. It's up to you if you want to leave it open till someone implements it or to close it.

**Comment by gustavnavar** [comment]
GridBlazor 1.6.2 should work for you. Take a look at the [sample](https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorClientSide.Client/Pages/Checkbox.razor)

**Comment by timbze** [comment]
Awesome!

**Comment by gustavnavar** [comment]
There is a change on the configuration since version 1.6.7. It's mandatory to identify the columns that are primary keys for the grid. You must do it using the SetPrimaryKey(true) method for the primary key columns' definitions:

```c#
    c.Add("CheckboxColumn").SetCheckboxColumn(true, o => o.Customer.IsVip);
    c.Add(o => o.OrderID).SetPrimaryKey(true);
```
