### ISSUE TITLE
CRUD - Bool property always false

### ISSUE THREAD

**Issue by alvisemion** [gustavnavar/Grid.Blazor#169]
I'm using CRUD with autogenerated form.
I've used version 1.5.5 with no problems.
I've update to latest 1.6.2.
With this version every crud insert or update send always to **false every bool property**, even if checked true on the form.
Same problem with 1.6.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, FireFox 
 - Version 1.6.1

I've reverted to 1.5.5 and bool property now works fine.
Revert to 1.5.5 also causes this revert:
![image](https://user-images.githubusercontent.com/36442664/82336644-224c2000-99eb-11ea-814b-eba6954741f8.png)

**Comment by gustavnavar** [comment]
Version 1.6.3 should work for you

**Comment by alvisemion** [comment]
Works fine.
Really thanks.
