### ISSUE TITLE
Stacking CSS

### ISSUE THREAD

**Issue by balajipitchumani** [gustavnavar/Grid.Blazor#17]
Is it possible to add multiple CSS to a given column in a stacking manner?

**Comment by gustavnavar** [comment]
Please could you explain what you need in more detail?

**Comment by balajipitchumani** [comment]
Apologies for being cryptic earlier. Lets say I want to apply 2 different CSS for a given columns...roughly like 

SetCellCssClassesContraint(o => o.OrderDate.HasValue && o.OrderDate.Value >= DateTime.Parse("1997-01-01") ? "red" : "").SetCellCssClassesContraint(o => o.OrderDate.HasValue ? "left" : "right")

**Comment by gustavnavar** [comment]
You must use the SetCellCssClassesContraint only once per column because it overwrites the class attribute.

So you have to use a more complex lambda expression like the following one:
.SetCellCssClassesContraint(o => {
                string css = "";
                css += o.OrderDate.HasValue && o.OrderDate.Value >= DateTime.Parse("1997-01-01") ? "red " : "";
                css += o.OrderDate.HasValue ? "left" : "right";
                return css;
            })
