### ISSUE TITLE
Select all rows when using ‘Selectable’ method on server side Blazor

### ISSUE THREAD

**Issue by DSBhogal** [gustavnavar/Grid.Blazor#171]
Is there currently a way to select all rows? If not is this a feature that will be coming in a future update?

**Comment by gustavnavar** [comment]
It's  not possible to select all rows with the ```Selectable``` method. 

But you can do it with code. Take a look at this (issue)[https://github.com/gustavnavar/Grid.Blazor/issues/105]

**Comment by DSBhogal** [comment]
When getting checked rows, is there a way to get the actual object of each row using the key? if not is there a way to change the key of each to the id of the object?
