### ISSUE TITLE
Need header checkbox to select ALL rows when paging is active

### ISSUE THREAD

**Issue by sjoko** [gustavnavar/Grid.Blazor#172]
First of all … compliments to your work so far. A really good grid already, and I suspect there's more to come  :-)

But … I’m using the SetCheckBoxColumn to select one or more rows, and I want to select ALL rows by ticking the header checkbox. Currently, only the rows on the current page are selected when the header box is ticked. Also, after visiting another page all row boxes are cleared yet the header box remains ticked.

Any suggestion how I could select all rows (and preserve their state?

**Comment by DSBhogal** [comment]
I'm having the same issue when filtering and searching on the grid

**Comment by gustavnavar** [comment]
Package version 1.6.7 implements this feature

**Comment by gustavnavar** [comment]
There is a change on the configuration. It's mandatory to identify the columns that are primary keys for the grid. You must do it using the SetPrimaryKey(true) method for the primary key columns' definitions:

```c#
    c.Add("CheckboxColumn").SetCheckboxColumn(true, o => o.Customer.IsVip);
    c.Add(o => o.OrderID).SetPrimaryKey(true);
```

**Comment by sjoko** [comment]
Thanks very much ... works like a charm!

**Comment by wowraam** [comment]
need help with selecting all rows. Tried below code and I don't see any checkbox in the header. Tried using a custom select for each row which is working but looking for a select all checkbox with paging. Here is my existing code.
![Screenshot 2024-05-28 003021](https://github.com/gustavnavar/Grid.Blazor/assets/93916157/154a79b4-1aed-48bd-b8c2-beb416d1a5ad)


                        @await Html.Grid(Model.Verifications).Columns(columns =>
                                 {
                                     columns.Add("CheckboxColumn").SetCheckboxColumn(true, o => o.IsChecked).Css("form-check-input");
                                     columns.Add(o => o.Id).SetPrimaryKey(true);
                                     // columns.Add().Encoded(false).Sanitized(false).Titled("Select All")
                                     // .RenderValueAs(o =>
                                     // {
                                     //     var _link = $"<input type='checkbox' name='CheckedIds' value={o.Id} class='dt-checkboxes form-check-input'>";
                                     //     return _link;
                                     // });
                                     columns.Add(x => x.FullName).Titled("Name");
                                     columns.Add().Encoded(false).Sanitized(false).RenderValueAs(o =>
                                     {
                                         return "Status: " + o.Status + "<br />" + "Submitted On: " + o.SubmittedDate.ToString("dd-MMM-yyyy") + "<br />" + "Approved On: " + o.ApprovedDate.ToString("dd-MMM-yyyy");
                                     }).Titled("Details");
                                     columns.Add().Encoded(false).Sanitized(false).Titled("Action")
                                     .RenderValueAs(o =>
                                     {
                                         var verifyProfileLink = $"<a class='btn btn-xs btn-outline-success' href='/User/ReviewRequest/{o.Id}'> Review Request </a>";
                                         var docLink = $"<a class='btn btn-xs btn-outline-info' href='/User/GeneratePDFs/{o.Id}'> Generate Documents </a>";
                                         var modalLink = $"<button type = 'button' class='btn btn-xs btn-primary' data-bs-toggle='modal' data-bs-target='#divModal' data-id={o.id}> Upload </button>";
                                         return verifyProfileLink + docLink + modalLink;
                                     });
                                 }).Searchable(true, false, true).SetStriped(true).ChangePageSize(true).WithGridItemsCount().WithPaging(20).RenderAsync()

**Comment by gustavnavar** [comment]
Hi,

from your code I think that you are using ASP.NET MVC. 

Selecting rows  with a checkbox column is supported on .NET Blazor. So, you can switch to a Blazor project, or, if you want to continue using a MVC project, you can embed a Blazor component on a MVC view. This is described in the following documentation link: https://github.com/gustavnavar/Grid.Blazor/assets/30131949/26f50d45-e566-46a8-8407-3543b06a2261

The project GridMvc.Demo includes a sample of a Blazor component on a MVC view:
- MVC view sample: https://github.com/gustavnavar/Grid.Blazor/blob/master/GridMvc.Demo/Views/Home/BlazorComponentView.cshtml
- Grid Blazor component sample: https://github.com/gustavnavar/Grid.Blazor/blob/master/GridMvc.Demo/Components/OrdersViewComponent.cs
-
