### ISSUE TITLE
Reset filters shows results from another page on page 1

### ISSUE THREAD

**Issue by DSBhogal** [gustavnavar/Grid.Blazor#175]
As an example if I'm on page three and I filter results. Once I've filtered the results if I hit the 'Clear all filters' button it clears the filters and sets me back to page 1 however it shows me the records that are on page 3 on page 1. Screenshots below to give you a visual:

### Page 3 (Without filtering)
![image](https://user-images.githubusercontent.com/33750091/84995915-7d854580-b144-11ea-8db0-76e8b5644bfe.png)

### Page 3 (Filtered)

![image](https://user-images.githubusercontent.com/33750091/84996177-d3f28400-b144-11ea-822c-2017c26af250.png)

### Page 1 (After clearing all filters)

![image](https://user-images.githubusercontent.com/33750091/84996227-e2d93680-b144-11ea-928f-84edb32c02aa.png)

**Comment by gustavnavar** [comment]
Package version 1.6.9 fix this issue
