### ISSUE TITLE
Allow only one checkbox to be selected in the checkbox

### ISSUE THREAD

**Issue by prabhakarreddy1234** [gustavnavar/Grid.Blazor#176]
Currently we can select multiple checkboxes or all checkboxes(through header) in a grid `Checkboxcolumn`. It would be useful if there is flag to make the grid allow selecting only one checkbox at anytime and then already selected checkebox will be unchecked.

**Comment by gustavnavar** [comment]
Package version 1.6.10 has a new method for this: [SetSingleCheckboxColumn](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Selecting_row.md#setsinglecheckboxcolumn-method)
