### ISSUE TITLE
Checkboxes resetting on page change

### ISSUE THREAD

**Issue by timbze** [gustavnavar/Grid.Blazor#178]
In docs [here](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Selecting_row.md#setcheckboxcolumn-method) it is mentioned that `Blazor pages using checkboxes may require to use the ShouldRender method to suppress UI refreshing.`

I'm trying to figure out in the code how I can avoid this, but can not figure out why CheckboxComponent keeps reloading on every `StateHasChanged()'. Is there a way to avoid this or why is this issue there? With this work-around it becomes almost impossible to do anything else on the page while still keeping the checkbox states.

**Comment by gustavnavar** [comment]
It's not mandatory to use the ShouldRender method on a Blazor page contaning a grid with checboxes. 

If the page is rendered for whatever reason, all CheckboxComponents will be reloaded. In older versions checked rows were managed by rowid and a page rerender forced to reinitialize checkboxes's information. But in version 1.6.9 they are managed by row keys and a page rerender will not reinitialize checkboxes's information. 

So you can avoid using the ShouldRender method now.
