### ISSUE TITLE
CRUD fields customization

### ISSUE THREAD

**Issue by faina09** [gustavnavar/Grid.Blazor#182]
I need to manage a CRUD field in insert/edit that return a very long` IEnumerable<SelectItem>`
A good example may be a cities list:
I have e.g. the main class with some Anagraphics and a CityCode that point to the class with all the cities allowed, having the fields Code and Name.
In this case defining in ColumCollection the field like this:

```
    c.Add(o => o.CityCode).Titled("City")
                .SetWidth(250).RenderValueAs(o => o.CityCode == null ? "" : o.CityCodeNavigation.Name)
                .SetSelectField(true, o => o.CityCode == null ? "" : o.CityCodeNavigation.Name, h);
```

works but returns a very long `<select>` that takes too long to be shown and select by the user.

I solved for a single field using an input box near the `<InputSelect>`:

```
<InputSelect @bind-Value="Anagraphics.City">
   @foreach (var item in SelectedItems)
   {
       <option value="@item.Value"> @item.Title </option>
   }
</InputSelect>
```

on value changes it triggers a method that return the City containing the SearchTerm:

```
public override IEnumerable<SelectItem> GetSelectedItems(string searchTerm)
{
    return _myRepository.GetAll().Where(o => o.Name.Contains(searchTerm))
        .Select(r => new SelectItem(r.Code, r.Name))
        .ToList();
}
```

My question is: how can I customize a grid field this way? Is there more generally a way to define a custom field?

**Comment by faina09** [comment]
I investigated further and I think that a method like  `.EditComponentAs<>` to edit/insert, similar to the existing `.RenderComponentAs<>` to list/display may be very useful for my purposes.

**Comment by faina09** [comment]
I solved adding `.RenderCrudComponentAs<RlstCom>()` to the desided column and the following RlstCom.razor

```
@using BlazorStrap
@using MyApp.Areas.AnagArea.Models
@using GridShared.Columns
@implements ICustomGridComponent<Anagraphics>
@*see Grid.Blazor\GridBlazor\Pages\GridTabComponent.razor*@
<select id="City" name="City" class="form-control" value="@selectedValue" @onchange="(e) => ChangeValue(e)">
    <option value="">select...</option>
    @foreach (var selectItem in SelectedItems)
    {
        if (selectItem.Value == selectedValue)
        {
            <option value="@selectItem.Value" selected="selected">@selectItem.Title</option>
        }
        else
        {
            <option value="@selectItem.Value">@selectItem.Title</option>
        }
    }
</select>
<div class="col-md-5">search City: <input class="form-control " @bind="SearchTerm" /></div>

@code {
    [Parameter]
    public Anagraphics Item { get; set; }

    [Inject]
    ICitiesService<Cities> RlstService { get; set; }

    public IEnumerable<SelectItem> SelectedItems;
    public string selectedValue;
    private string searchTerm;
    public string SearchTerm
    {
        get { return searchTerm; }
        set { searchTerm = value; OnStartChange(); }
    }

    protected override async Task OnParametersSetAsync()
    {
        selectedValue = Item.City ?? "";
        SearchTerm = Item.CityNavigation == null? "" : Item.CityNavigation?.City?.Trim();
    }

    public void OnStartChange()
    {
        SelectedItems = RlstService.GetSelectedItems(searchTerm);
    }

    private void ChangeValue(ChangeEventArgs e)
    {
        var value = e.Value.ToString();
        Item.City = value;
    }

}
```

**Comment by faina09** [comment]
Are there more examples about the method `.RenderCrudComponentAs<>`? 

I have seen the source in `Grid.Blazor\GridBlazor\Columns\GridColumnBase.cs` 
and the method has the possibility to use various parameters, but I cannot find how to read for example `CrudObject` defined here in my `.RenderCrudComponentAs<>` implementation?

My intention is to have new types of columns to suite many different needs in CRUD.
Thank you

**Comment by gustavnavar** [comment]
I've added more documentation [here](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Render_button_checkbox_etc_in_a_grid_cell.md)

**Comment by faina09** [comment]
great! now all is clear!!
Just a consideration: using the divs in around the code `@_renderFragments.Get(column.Name) ` in `Grid[Update/Read]Component.razor` creates a style for custom columns in edit/read/update that is different from that of the other columns.
This seems not nice to me and I would like to remove it (not possible using styles): if needed the user always can apply his/her own style.
Thank you
