### ISSUE TITLE
: 'Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.2.0

### ISSUE THREAD

**Issue by PeteJobi** [gustavnavar/Grid.Blazor#183]
**Describe the bug**
I followed the [docs](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Documentation.md) to setup Grid.Blazor for server side. The way I implemented my services was a little different. When I try to run, I get the error:
`System.TypeLoadException: 'Could not load type 'Microsoft.AspNetCore.Http.Internal.QueryCollection' from assembly 'Microsoft.AspNetCore.Http, Version=3.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'`

![QueryCollection error](https://user-images.githubusercontent.com/45200292/86607984-e02e6c00-bfa1-11ea-9081-366d72d59561.png)

**Expected behavior**
I expect the grid to render without issues.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 10

**Additional context**
I'm using .NET Core 3.1 and the latest versions of `Grid.Blazor` and `GridMvcCore`

I saw from a closed issue #114  that it's a conflict between versions. Please how do I resolve this?

**Comment by gustavnavar** [comment]
GridBlazor 1.6.11 and GridMvcCore 3.0.0 should work for you
