### ISSUE TITLE
Modify Resource text

### ISSUE THREAD

**Issue by Ksantacr** [gustavnavar/Grid.Blazor#184]
**Is your feature request related to a problem? Please describe.**
Is not clear how modify resources from https://github.com/gustavnavar/Grid.Blazor/blob/79069aa90ca03c532ba8ad58699de5d24ee50279/GridBlazor/Resources/Strings.es.resx

**Describe the solution you'd like**
If is possible add a description about it

**Describe alternatives you've considered**
General example

**Additional context**
Nothing

**Comment by gustavnavar** [comment]
If you want to add a new locale you can send me the following [words](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Localization.md#additional-languages) translated to your language and I will add a new file for it.

**Comment by Ksantacr** [comment]
> If you want to add a new locale you can send me the following [words](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Localization.md#additional-languages) translated to your language and I will add a new file for it.

Hello, @gustavnavar thanks for your response. I checked it but I don't just want to change language. I'd like to change the text in a specific language for example. 

`<data name="CreateItem" xml:space="preserve">
    <value>Create item</value>
  </data>`

[GridBlazor/Resources/Strings.resx](https://github.com/gustavnavar/Grid.Blazor/blob/79069aa90ca03c532ba8ad58699de5d24ee50279/GridBlazor/Resources/Strings.resx)

instead of 'Create Item', show 'Create element'
It's possible?

**Comment by gustavnavar** [comment]
Yes, you can change all string values. You can publish the GridBlazor project and get your own nuget package.
