### ISSUE TITLE
Does this support Right to Left RTL and the unicode characterset for Arabic language?

### ISSUE THREAD

**Issue by sodapopzs** [gustavnavar/Grid.Blazor#187]
Does this support Right to Left RTL and the unicode characterset for Arabic language?

**Comment by gustavnavar** [comment]
RTL is not supported yet. 

But I don´t see any problem to use Arabic language. If you want to include all labels in Arabic just send me all the words translated: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/dotnetcore/Localization.md#additional-languages

**Comment by gustavnavar** [comment]
GridBlazor 1.8.0 supports RTL. 

You can look at the [documentation](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Localization.md#right-to-left-direction)

If you want to add grid labels translations in Arabic you can send them to me and I will add it in a new release.
