### ISSUE TITLE
Question - when not using an IQueryable DataSource

### ISSUE THREAD

**Issue by dazinator** [gustavnavar/Grid.Blazor#19]
I'm looking to implement a Grid where the query operations are sent to the backend (asp.net core api) for processing.

However on the backend, I need to formulate a call to a REST service to get the data - i'm not querying a local database.

Is it possible to use this grid in such a mannor? I guess I am interested in recieving data sent from the front end, but rather than having it expressed as an IQueryable, I realy need to access the raw data model sent form the client, so I can build my own rest calls to the data provider.

Many Thanks

**Comment by gustavnavar** [comment]
You can use any IEnumerable<T>.

The controller that you use should similar to:
```c#
    public ActionResult GetOrdersGrid()
    {
            List<Order> list = new List<Order>();
            list.Add(...);
            ...
            IGridServer<Order> server = new GridServer<Order>(list, Request.Query,
                true, "ordersGrid", ColumnCollections.OrderColumns)
                    .WithPaging(10)
                    .Sortable()
                    .Filterable()
                    .WithMultipleFilters()
                    .WithGridItemsCount();

            var items = server.ItemsToDisplay;
            return Ok(items);
        }
```

**Comment by gustavnavar** [comment]
I forgot to tell you that the previous option will work if you can download all records to the back-end server. 

But if you can not do that, you can develop a back-end REST webservice implementing the API described here:
https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/API.md

**Comment by dazinator** [comment]
@gustavnavar thank you that was the info I needed.
