### ISSUE TITLE
Translations for swedish localization

### ISSUE THREAD

**Issue by hellb0rg** [gustavnavar/Grid.Blazor#190]
Here are the translations required for the addition of localization for sweden.

    Add : Lägg till                                                                                
    And : Och
    Apply : Tillämpa
    Average : Medel
    Back : Tillbaka
    No : Nej
    Yes : Ja
    Clear all filters : Rensa alla filter
    Clear filter : Rensa filter
    Contains : Innehåller
    Create item : Skapa objekt
    There are no items to display : Det finns inga objekt att visa
    Delete : Ta bort
    Delete item : Ta bort objekt
    Edit : Redigera
    Ends with : Slutar med
    Equals : Är lika med
    Drop columns here for column extended sorting : Släpp kolumner här för utökad sortering av kolumner
    Filter this column : Filtrera denna kolumn
    Type : Typ
    Value : Värde
    Greater than : Större än
    Greater than or equals : Större eller lika med
    Drop columns here for column grouping : Släpp kolumner här för gruppering av kolumner
    Is null : Är tom
    Is not null : Är inte tom
    Items : Objekt
    Less than : Mindre än
    Less than or equals : Mindre eller lika med
    Max : Max
    Min : Min
    Not equals : Inte lika med
    Or : Eller
    Read item : Visa objekt
    Save : Spara
    Search for ... : Sök efter ...
    --- Select an item --- : --- Välj ett objekt ---
    Show : Visa
    Starts with : Börjar med
    Sum : Summa
    Update item : Uppdatera objekt
    View  : Visa
    There was an error creating the new item : Det uppstod ett fel vid skapandet av ett nytt objekt
    There was an error deleting this item  : Det uppstod ett fel vid raderingen av detta objekt
    There was an error updating this item  : Det uppstod ett fel vid uppdatering av detta objekt

**Comment by gustavnavar** [comment]
GridBlazor 1.8.0 supports Swedish localization
