### ISSUE TITLE
Filter on entity having a subset

### ISSUE THREAD

**Issue by faina09** [gustavnavar/Grid.Blazor#191]
I have a primary table with subrecords in a secondary tables.
I would like to show in the grid only the records in the primary table having at least one record in the secondary.
I kwon I can do this adding into the `IQueryable<> GetAll()` method in the Repository a clause like this:

`.Where(r=>r.MySubSet.Count>0);`

but is there a way to do this by filtering? In this way I can show all the records OR only records with subset.

Thank you!

**Comment by gustavnavar** [comment]
I've added a sample for Blazor Server and Blazor Wasm applications:
- https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorServerSide/Pages/Count.razor
- https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorClientSide.Client/Pages/Count.razor

**Comment by faina09** [comment]
Thank you,  this *displays* the number of records contained in the subset.
I think I can use this info to show only the main records with this count>0, but I not sure how to do...

**Comment by gustavnavar** [comment]
You can add a  "greater than 0" filter to this column

**Comment by faina09** [comment]
I used this code to add a predefined filter when the user checks a checkbox:
```` c# 
protected async void OnlyWithSubSetClicked(object checkedValue)
{
	var _filterValue = "0";
	var GridHeaderComponent = _gridComponent.HeaderComponents["SubSet.Count"];
	if ((bool)checkedValue)
	{
		await GridHeaderComponent.AddFilter(new GridShared.Filtering.FilterCollection(GridShared.Filtering.GridFilterType.GreaterThan.ToString("d"), _filterValue));
	}
	else
	{
		await GridHeaderComponent.RemoveFilter();
	}
}
````

that works but presents the filter popup to user, that may be annoying. 
Is there any way to avoid this?

**Comment by gustavnavar** [comment]
You should use ```GridComponent```methods instead of ```GridHeaderComponent``` ones:

```c#
protected async void OnlyWithSubSetClicked(object checkedValue)
{
	var _filterValue = "0";
	var column= Grid.Columns.GetByName("SubSet.Count");
	if ((bool)checkedValue)
	{
		await _gridComponent.AddFilter(column, new GridShared.Filtering.FilterCollection(GridShared.Filtering.GridFilterType.GreaterThan.ToString("d"), _filterValue));
	}
	else
	{
		await _gridComponent.RemoveFilter(column);
	}
}
```

**Comment by faina09** [comment]
thank you, this works fine.
