### ISSUE TITLE
All CRUD Buttons in grid Header

### ISSUE THREAD

**Issue by borisdj** [gustavnavar/Grid.Blazor#194]
Is there an option to configure Read/Update/Delete buttons position to be in the header of grid next to the Add button.
Because repeating same buttons in every row is redundant, also takes extra space.
And they should work on selected row (Delete could be for multiple selected rows).
If there is not config for this yet, can it be added as a feature. and how could it be custom programmed in the meantime, any example?

Btw, great library.

**Comment by gustavnavar** [comment]
Package version 1.8.1 supports buttons on the header:
- Documentation: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Crud.md#crud-buttons-on-the-grid-header
- Sample: https://gridblazor.azurewebsites.net/headercrudbuttons

**Comment by borisdj** [comment]
Thx for the info.
