### ISSUE TITLE
Translations for serbian localization

### ISSUE THREAD

**Issue by borisdj** [gustavnavar/Grid.Blazor#197]
Following Link has serbian translations:
https://docs.google.com/spreadsheets/d/1O3pC_k_JY8XGC7MZpOOS1siNc3kn8PGpegITS7xDifQ/view

There are 4 main types with ISO-codes:
1. sr-Latn-RS (Latinic-Serbia) / Ekavian
2. sr-Latn-BA (Latinic-BosniaAndHerzegovina) / Ijekavian
3. sr-Cyrl-RS (Cyrillic-Serbia) / Ekavian
4. sr-Cyrl-BA (Cyrillic-BosniaAndHerzegovina) / Ijekavian

since serbian language has Digraphia - 2 Alphabets:[Latinic, Cyrilic] and also 2 Dialects:[Ekavian, Ijekavian], depending on country and region.

**Comment by gustavnavar** [comment]
Package version 1.8.2 includes Serbian locale

**Comment by borisdj** [comment]
@gustavnavar I've noticed that there are 5 new labels added, so I have added their translation into the same sheet linked in first post. I have marked them with number **2** in first col. **_V_**
If you would like I could make a pull request, or if it's easier for you just to copy them.
Thx again.
