### ISSUE TITLE
ItemsCount incorrect when enabled

### ISSUE THREAD

**Issue by jcageman** [gustavnavar/Grid.Blazor#2]
**Describe the bug**
When using client.WithGridItemsCount(); the count always shows -1.

**Additional context**
I think the bug is in CGrid.cs the ItemCount is never updated and is kept at -1.

**Comment by gustavnavar** [comment]
ok, I will fix it for next release

**Comment by gustavnavar** [comment]
I've just  added a new version that fixes this issue
