### ISSUE TITLE
Grid has large margin left and right

### ISSUE THREAD

**Issue by martinscholz83** [gustavnavar/Grid.Blazor#200]
**Describe the bug**
I don't know if it's a bug. But on a widescreen (MacBook Pro) the grid has a very large margin left and right. In dev console it has property `max-width: 1140px;`. I got this after upgrading to `1.8.4`. Is this by design?

**To Reproduce**
https://gridblazor.azurewebsites.net/

**Expected behavior**
No margin.
**Screenshots**
<img width="1679" alt="Bildschirmfoto 2020-08-17 um 09 16 32" src="https://user-images.githubusercontent.com/19551763/90368510-6d1d1880-e06a-11ea-9f28-e0a8240101c8.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by martinscholz83** [comment]
You should give the [grid](https://github.com/gustavnavar/Grid.Blazor/blob/4dc982722dd29a85aa707b4f3610387fa9bf3283/GridMvc/Views/Shared/_Grid.cshtml#L56) `container-fluid`.

**Comment by timbze** [comment]
Just got this also. I added css as a work-around, but not sure why the change
```css
.grid-wrap.container{
    margin-right: inherit;
    margin-left: inherit;
}
```

**Comment by gustavnavar** [comment]
GridBlazor 1.8.8 has a fix for this bug
