### ISSUE TITLE
Adding Fa Locale to Grid.Blazor

### ISSUE THREAD

**Issue by GhazalehSalehi** [gustavnavar/Grid.Blazor#205]
**Is your feature request related to a problem? Please describe.**
Localization for culture Fa (Farsi)

**Describe the solution you'd like**
I'd like you add this locale to Resources of Grid Blazor

**Describe alternatives you've considered**
I've Translated Keywords to Farsi and Attached the excel 
[String-Fa-IR.xlsx](https://github.com/gustavnavar/Grid.Blazor/files/5212530/String-Fa-IR.xlsx)
file for you to add Fa Locale

**Additional context**
We're in a hurry so I'd be so grateful if you add this culture ASAP.

**Comment by gustavnavar** [comment]
GridBlazor 1.8.7 includes Farsi locale
