### ISSUE TITLE
Grid is not updating the database values

### ISSUE THREAD

**Issue by AllenIt** [gustavnavar/Grid.Blazor#206]
I am having issues with updating the table, after editing and saving the table, the edited values reflect on the grid in UI but it doesn't save the value in the database. I am using the below code for the grid. Let me know if something is wrong with the code.

@code
{

    protected CGrid<Employee> _grid;
    private GridComponent<Employee> Component;
    private Task _task;

    [Parameter]
    public string OnEmployeeEditJS { get; set; } = "postEmployeeChange";

    protected override async Task OnParametersSetAsync()
    {
        Action<IGridColumnCollection<Employee>> columns = c =>
        {

            c.Add(e => e.EmployeeID, true).SetPrimaryKey(true).SetCrudHidden(true);
            c.Add(e => e.WebStatus).Titled("STATUS").Filterable(false).Sortable(true).SetSelectField(true, e => e.SelectedStatus.StatusLabel, empService.GetStatusList).Css("status");
            c.Add(e => e.LastName).Titled("LAST NAME").Filterable(true).Sortable(true);
            c.Add(e => e.FirstName).Titled("FIRST NAME").Filterable(true).Sortable(true);
            c.Add(e => e.DOB).Format("{0:MM/dd/yyyy}").Css("headr dob").Filterable(true).Sortable(true);
            c.Add(e => e.Gender).Css("headr gender").Titled("GENDER").Css("text-center1 headr").Filterable(true).Sortable(true).SetSelectField(true, e => e.SelectedGender.GenderLabel, empService.GetGenderList);
            c.Add(e => e.EmployeeNo).Titled("EMP NO").Filterable(true).Sortable(true);
            c.Add(e => e.HireDate).Titled("HIRE DATE").Format("{0:MM/dd/yyyy}").Filterable(true).Sortable(true).Css("hire");
            c.Add(e => e.DepartmentNo).Titled("DEPT").Filterable(true).Sortable(true);
            c.Add(e => e.NoiseID).Titled("NOISE ID").SetSelectField(true, e=>e.SelectedNoise.NoiseLabel, empService.GetNoiseList).Css("noise");
            c.Add(e => e.PFT).SetSelectField(true, e=>e.PFTValue, empService.GetPFTList);
            c.Add(e => e.FIT).SetSelectField(true, e=>e.FITValue, empService.GetFITList);
            c.Add(e => e.Language, true).SetSelectField(true, e => e.SelectedLanguage.LanguageName, empService.GetLanguageList);
            c.Add(e => e.SelectedLanguage.LanguageName).Titled("LANGUAGE").SetCrudHidden(true);
        };

        var query = new QueryDictionary<StringValues>();

        var client = new GridClient<Employee>(q => empService.GetNameListGridRows(columns, q), query, false, "empGrid", columns)
                        .ChangePageSize(true)
                        .Searchable(true, false)
                        .SetStriped(true)
                        .WithMultipleFilters()
                        .ClearFiltersButton(false)
                        // .SetReadComponent<EmployeeView>()
                        .WithGridItemsCount("Employees found: ")
                        .Crud(true, false, true, false, empService);

        _grid = client.Grid;       

        _task = client.UpdateGrid();

        await _task;
    }

**Comment by gustavnavar** [comment]
Can you show thar ```EmpService``` class (and the repository class if you use this pattern) ?

**Comment by AllenIt** [comment]
This the EmpService class code. 

      public ItemsDTO<Employee> GetNameListGridRows(Action<IGridColumnCollection<Employee>> columns,
                  QueryDictionary<StringValues> query)
      {

         var server = new GridServer<Employee>(GetNameListEmployees().Result, new Microsoft.AspNetCore.Http.QueryCollection(query),
                 true, "empGrid", columns)
             .Sortable()
             .WithPaging(25)
             .Filterable()
             .WithMultipleFilters()
             .Searchable(true, false);

         return server.ItemsToDisplay;
      }

**Comment by gustavnavar** [comment]
Aside of this method, you have to implement the ICrudDataService interface. This is a sample of service that works for CRUD grids:

```c#
    public class EmployeeService : IEmployeeService
    {
        private readonly ILogger<EmployeeService> _logger;

        public UserService(ILogger<EmployeeService> logger)
        {
            _logger = logger;
        }

        public ItemsDTO<Employee> GetNameListGridRows(Action<IGridColumnCollection<Employee>> columns,
              QueryDictionary<StringValues> query)
        {
            using (var context = new ApplicationDbContext())
            {
                var repository = new EmployeeRepository(context);
                var server = new GridServer<Employee>(repository.All, new QueryCollection(query), true,
                    "empGrid", columns)
                    .Sortable()
                    .WithPaging(25)
                    .Filterable()
                    .WithMultipleFilters()
                    .Searchable(true, false);

                return server.ItemsToDisplay;
            }
        }

        public async Task<Employee> Get(params object[] keys)
        {
            using (var context = new ApplicationDbContext())
            {
                var repository = new EmployeeRepository(context);
                return await repository.All.SingleOrDefaultAsync(o => o.EmployeeID == keys[0].ToString());
            }
        }

        public async Task Insert(Employee item)
        {
            using (var context = new ApplicationDbContext())
            {
                try
                {
                    var repository = new EmpRepository(context);
                    repository.Insert(item);
                    await repository.SaveAsync();
                }
                catch (Exception e)
                {
                    _logger.LogError(e, "EmployeeService/Insert: " + item.EmployeeID);
                    if (e is GridException)
                        ExceptionDispatchInfo.Capture(e).Throw();
                    else
                        throw new GridException(e);
                }
            }
        }

        public async Task Update(Employee item)
        {
            using (var context = new ApplicationDbContext())
            {
                try
                {
                    var repository = new EmployeeRepository(context);
                    repository.Update(item);
                    await repository.SaveAsync();
                }
                catch (Exception e)
                {
                    _logger.LogError(e, "EmployeeService/Update: " + item.EmployeeID);
                    if (e is GridException)
                        ExceptionDispatchInfo.Capture(e).Throw();
                    else
                        throw new GridException(e);
                }
            }
        }

        public async Task Delete(params object[] keys)
        {
            using (var context = new ApplicationDbContext())
            {
                try
                {
                    var repository = new EmployeeRepository(context);
                    repository.Delete(keys[0].ToString());
                    await repository.SaveAsync();
                }
                catch (Exception e)
                {
                    _logger.LogError(e, "EmployeeService/Delete: " + keys[0].ToString());
                    if (e is GridException)
                        ExceptionDispatchInfo.Capture(e).Throw();
                    else
                        throw new GridException(e);
                }
            }
        }
    }

    public interface IEmployeeService : ICrudDataService<Employee>
    {
        ItemsDTO<Employee> GetNameListGridRows(Action<IGridColumnCollection<Employee>> columns,
              QueryDictionary<StringValues> query)
    }
```

You also need a base repository class:
```c#
    public class EmployeeRepository : IEmployeeRepository
    {
        protected readonly ApplicationDbContext _context;
        protected readonly DbSet<Employee> _dbSet;

        public BaseRepository(ApplicationDbContext context)
        {
            _context = context;
            _dbSet = context.Set<Employee>();
        }

        public virtual IQueryable<Employee> All
        {
            get { return _dbSet; }
        }

        public virtual Employee Find(int id)
        {
            return _dbSet.Find(id);
        }

        public virtual void Insert(Employee emp)
        {
            _dbSet.Add(emp);
        }

        public virtual void Update(Employee emp)
        {
            var entry = _context.Entry(emp);
            if (entry.State == EntityState.Detached)
            {
                var attachedItem = _context.Employee.Find(emp.EmployeeID);
                if (attachedItem != null)
                {
                    _context.Entry(attachedItem).CurrentValues.SetValues(emp);
                }
                else
                {
                    entry.State = EntityState.Modified;
                }
            }
        }

        public virtual void Delete(int id)
        {
            var entity = _dbSet.Find(id);
            _dbSet.Remove(entity);
        }

        public async Task SaveAsync()
        {
            await _context.SaveChangesAsync();
        }

        private bool disposed = false;

        protected virtual void Dispose(bool disposing)
        {
            if (!this.disposed)
            {
                if (disposing)
                {
                    _context.Dispose();
                }
            }
            this.disposed = true;
        }

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }
    }

    public interface IEmployeeRepository : IDisposable
    {
        IQueryable<Employee> All { get; }
        Employee Find(int id);
        void Insert(Employee emp);
        void Update(Employee emp);
        void Delete(int id);
        Task SaveAsync();
    }
```
