### ISSUE TITLE
Grid does not show table data.

### ISSUE THREAD

**Issue by uday-shetty-manila** [gustavnavar/Grid.Blazor#207]
Using VS 16.7.3
My code does not fetch data from the table. It is always empty. Here is the code. 
// model
public class Brand
    {
        [Key]
        public int brandID { get; set; }
        [StringLength(20)]
        [DisplayName("Brand")]
        public string brandName { get; set; }
}

@page "/Brand/Index"
@inject HttpClient Http
@inject IModalService Modal
@inject Microsoft.AspNetCore.Components.NavigationManager navigation
@using GridShared
@using GridShared.Utility
@using Microsoft.Extensions.Primitives
@using ITAssets.Models;
@using System.Globalization

<h1>Brands</h1>

<p>
    <a href="/Brand/Create">Create</a>
</p>

@if (_task.IsCompleted)
{
    <GridComponent T="Brand" Grid="@_grid"></GridComponent>
}
else
{
    <p><em>Loading...</em></p>
}

@code {
    private CGrid<Brand> _grid;
    private Task _task;

    public static Action<IGridColumnCollection<Brand>> Columns = c =>
    {
        c.Add(o => o.brandID);
        c.Add(o => o.brandName);
    };

    protected override async Task OnInitializedAsync()
    {
        var locale = CultureInfo.CurrentCulture;

        string url = navigation.BaseUri + "api/Brands/";
        var query = new QueryDictionary<StringValues>();        
        var client = new GridClient<Brand>(Http, url, query, false, "brandGrid", Columns, locale);
        _grid = client.Grid;

        _task = client.UpdateGrid();
        await _task;               

        // the below code works in normal blazor page
        // brands = await Http.GetFromJsonAsync<ITAssets.Models.Brand[]>("/api/Brands");
    }
}

**Comment by gustavnavar** [comment]
There is no ```GridComponent``` included in your component.

There should be something like this:
```c#
@if (_task.IsCompleted)
{
    <div class="row">
        <div class="col-md-12">
            <GridComponent T="Brand" Grid="@_grid"></GridComponent>
        </div>
    </div>
}
```

And the ```_grid``` variable must be defined as follows:
```c#
private CGrid<Brand> _grid;
```
