### ISSUE TITLE
RenderComponentAs rendering an empty column

### ISSUE THREAD

**Issue by WDcontrol** [gustavnavar/Grid.Blazor#209]
Hey there !

I'm trying to use RenderComponentAs but it is not working.

1. I added 3 columns like this :
```
Action<IGridColumnCollection<Logs>> columns = c =>
        {
            c.Add(o => o.Datetime).Sortable(true);
            c.Add(o => o.Comment);
            c.Add().Encoded(false).Sanitized(false).RenderComponentAs(typeof(ExportLogsButtons));
        };
```

The two first columns are rendering correctly but the last one is an empty column.

The component ExportLogsButtons is like this :
```
<p>test</p>


@code {
    [Parameter]
    public BasicDataInBlazor.Models.Logs Item { get; set; }
}
```

Note that I declared my Item Parameter as *public* because I can't declare it as protected.

The DOM is rendering my column like this :

![image](https://user-images.githubusercontent.com/24476835/94456985-40edcf00-01b4-11eb-96ba-70f27d2d7628.png)

I'm using BlazorServerRendering

- GridBlazor Version : v1.8.9
- GridMvcCore Version : v3.1.8
- GridShared Version : v3.1.8

Am I the only one to encounter this issue ?
Did I miss something in the configuration ? 

Thank you for all in advance !
JCE

**Comment by gustavnavar** [comment]
Is the ExportLogsButtons  implememting the ```ICustomGridComponent`<Logs>``` interface?

If it doesn't,  you have to add the following line in the component:

```c#@implements ICustomGridComponent<Logs>
```

**Comment by WDcontrol** [comment]
I implemented `ICustomGridComponent<Logs>` interface and it works now !

Thank you a lot !
JCE
