### ISSUE TITLE
GridMVC and GridShared nuget packages appear to be out of sync with code

### ISSUE THREAD

**Issue by CD1010** [gustavnavar/Grid.Blazor#21]
CGrid and GridClient objects do not appear to be in the nuget packages when trying to compile sample code in my project, Yet the sample application works fine as it links to GridMVC and gridShared directly.  

Did source code diverge from nuget?

**Comment by gustavnavar** [comment]
The are in sync, but CGrid and GridClient are in the GridBlazor package.

If you are building a Blazor client-side solution you should procede as follows:
https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/Installation.md

If you build a Blazor server-side solution you have to install all packages in the project:
https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Installation.md

**Comment by OutlawGameTools** [comment]
> If you build a Blazor server-side solution you have to install all packages in the project:
> https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Installation.md

Step 1 on that page says: Create a new Blazor client-side solution using the Blazor (server-side) template

Since I'm so new to Blazor, telling me to create a client-side solution for a server-side solution confuses me. :) If what you're saying is what I'm supposed to do, maybe a little clarification would help us noobs.

**Comment by gustavnavar** [comment]
Sorry, it was a mistake. It should say:
1. Create a new Blazor server-side solution using the Blazor (server-side) template.

It's already corrected.

**Comment by CD1010** [comment]
Thanks, I got latest and included the nuget packages and now it works.
