### ISSUE TITLE
Nested CRUD on Create Form

### ISSUE THREAD

**Issue by BadarAljahwari** [gustavnavar/Grid.Blazor#210]
**Description of the issue**

Currently in Nested CRUD example the sub grid is only shown in edit mode.
So for the user he need to save the record first then he need to edit it to be able to add data in sub grid.

*The Question*: Is there any way that I can show the sub grid in create mode or automatically showing the edit mode after clicking on save in create mode?

I tried different ways for couple of hours but nothing work for me. 

ex. of one try :switching to edit mode  after insert

protected override async Task OnParametersSetAsync()
    {
...
 if (InsertedItem != 0)
        {
            _keys = new object[] { InsertedItem };
            _mode = GridMode.Update;
        }
...
}

Thanks for such great project

**Comment by gustavnavar** [comment]
This is a feature that I want to implement in the short term. I think that showing the subgrid in create mode will not be possible. I think that going to the edit mode just after inserting will be the way to do it. I will have to implement a new method for the ```GridClient``` object or to modify the existing ````Crud``` method.

**Comment by BadarAljahwari** [comment]
Will be waiting for that.
Hopefully I reach to your level and contribute more.
Wishing you all the best.

**Comment by gustavnavar** [comment]
GridBlazor 1.8.10 implementes this feature: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/Nested_crud.md#showing-the-update-form-just-after-inserting-a-row

**Comment by BadarAljahwari** [comment]
Implemented & tested Successfully 💯 
Much Appreciated
