### ISSUE TITLE
onRowSelectEvent not firing

### ISSUE THREAD

**Issue by LeoPiresDeSouza** [gustavnavar/Grid.Blazor#212]
Hi Gustav,

I'm using GridMvc in y project, .Net Core 3.1 with Razror Pages (not MVC). 
I'm trying to cath the onRowSelectEvent but it is not firing. Is there any known issue about this?
Thank you.

**Comment by gustavnavar** [comment]
It works fine. I've added a razor page sample to the GridMvc.Demo project: https://github.com/gustavnavar/Grid.Blazor/tree/master/GridMvc.Demo/Pages

**Comment by LeoPiresDeSouza** [comment]
Thank you, but I can't make it happens. I can't even change de default language.
As you can see below, it's a very simple grid.
Am I missing something?



@page
@model Escol.Areas.Infraestrutura.Pages.AppFuncionario.FuncionarioGridModel

@using Escol.Business.Entities.Infraestrutura
@using GridMvc
@using GridShared

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

@{
    Action<IGridColumnCollection<Funcionario>> columns = c =>
    {
        c.Add(col => col.PessoaFisicaId);
        c.Add(col => col.Nome);
        c.Add(col => col.Cpf);
    };
}

@await Html.Grid(Model.ModelItens).Named("testGrid").Columns(columns).WithPaging(10).Sortable().Searchable(true, false).Selectable(true).SetLanguage("fr").RenderAsync()

@section scripts{
    <script src="~/js/gridmvc-lang-fr.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap-datepicker/locales/bootstrap-datepicker.fr.min.js" type="text/javascript"></script>
    <script src="~/js/gridmvc.js" type="text/javascript"></script>
    <script src="~/js/gridmvc.customwidgets.js" type="text/javascript"></script>
    <script>
        pageGrids.testGrid.onRowSelect(function (e) {
            alert("event fired");
        });
    </script>
}

**Comment by gustavnavar** [comment]
There are 2 missing things: 
- I don't see if you are loading jquery. Maybe you load it on the layout page. In any case, jquery is a required package.
- The onRowSelect function must be load after the page has been loaded. If you don't do in this way the testGrid object is undefined.

The following script section should work for you:
```c#
@section scripts{
    <script src="~/lib/jquery/jquery.js" type="text/javascript"></script>
    <script src="~/js/gridmvc-lang-fr.js" type="text/javascript"></script>
    <script src="~/lib/bootstrap-datepicker/locales/bootstrap-datepicker.fr.min.js" type="text/javascript"></script>
    <script src="~/js/gridmvc.js" type="text/javascript"></script>
    <script>
        $(function () {
            pageGrids.testGrid.onRowSelect(function (e) {
                alert("event fired");
            });
        });
    </script>
}
```
 
By the way, gridmvc.customwidgets.js script is not required. It's only a sample of custom filter widget that you don't use in your grid.

**Comment by LeoPiresDeSouza** [comment]
Thanks!!!! Without $(function ()) js was loading before de page. It's done.
