### ISSUE TITLE
Translation to Brazilian-Portuguese

### ISSUE THREAD

**Issue by LeoPiresDeSouza** [gustavnavar/Grid.Blazor#213]
Hi Gustav. Could you implement the resources for supporting brazilian-portuguese language (pt-br)?
I'm sendig the translation in the attached file.
Thank you.
[Pt-Br translation.xlsx](https://github.com/gustavnavar/Grid.Blazor/files/5356999/Pt-Br.translation.xlsx)

**Comment by gustavnavar** [comment]
I will add it in the next release.
Thanks!

**Comment by gustavnavar** [comment]
GridBlazor 1.8.12 and GridMvcCore 3.1.11 support  Brazilian-Portuguese translation
