### ISSUE TITLE
Localizations are not applied to column filters

### ISSUE THREAD

**Issue by adugasBID** [gustavnavar/Grid.Blazor#215]
No matter what I do, the grid filters stays in the OS language.

Follow the instructions here to reproduce:
https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Localization.md

I tried changing the Language field on the CGrid object.
I also tried changing the culture on the thread creating the grid.

Here you can see the search bar and total are in a different language than the filter "pop-up":
 ![image](https://user-images.githubusercontent.com/59090586/96290791-2d64a580-0fb5-11eb-972b-bdca9319f083.png)

I am using server side blazor with Windows 10 and Firefox.
It is not a regression as far as I know, I tried this a few months ago and got the same result.

**Comment by gustavnavar** [comment]
Can you try changing the current culture locale?

```c#
var locale = new CultureInfo("de-DE");
CultureInfo.CurrentCulture = locale;
var client = new GridClient<Order>(q => orderService.GetOrdersGridRows(columns, q), query, false, "ordersGrid", Columns, locale);
```

**Comment by adugasBID** [comment]
It gave the same result.

I didn't notice when I entered the issue, but there's another weird thing that happen:
When I selected a row, the search bar switch to french (the OS language)
![image](https://user-images.githubusercontent.com/59090586/96467268-bcadcb00-11f8-11eb-87ff-0adea49210ad.png)

The total stays in the culture I specified ("de-DE").

Can you reproduce ?

**Comment by gustavnavar** [comment]
I cannot reproduce this error.

Can you verify if there is any cookie for the culture (.AspNetCore.Culture)?
![Captura (23)](https://user-images.githubusercontent.com/30131949/96559649-9dc53c80-12bd-11eb-89af-035f8b0d40bd.png)

Which value has this cookie?

**Comment by adugasBID** [comment]
Interesting, I thought it would be easy to reproduce :/
I have the same problem on both of my machines (dev machine and production server).

I used chrome like you to see the cookies, but found none (on both machines).
![image](https://user-images.githubusercontent.com/59090586/96587823-d3aff400-12b0-11eb-8c99-87f1de718768.png)


Would that be it ? Since there's no cookies, it probably defaults to the machine culture ?

**Comment by gustavnavar** [comment]
Yes, I think so. The language cookies attached to requests are used to define the current locale.

Add this to the ```ConfigureServices``` method of Startup.cs:
```c#
     services.Configure<RequestLocalizationOptions>(
                options =>
                {
                    var supportedCultures = new List<CultureInfo>
                        {
                            new CultureInfo("en-US"),
                            new CultureInfo("de-DE"),
                            new CultureInfo("fr-FR")
                        };

                    options.DefaultRequestCulture = new RequestCulture(culture: "en-US", uiCulture: "en-US");
                    options.SupportedCultures = supportedCultures;
                    options.SupportedUICultures = supportedCultures;
                });
```

And this to the ```Configure``` method of Startup.cs:
```c#
     var locOptions = app.ApplicationServices.GetService<IOptions<RequestLocalizationOptions>>();
     app.UseRequestLocalization(locOptions.Value);
```

You can use this balzor page to select the locale for each user: 
https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorServerSide/Shared/Language.razor

It calls this controller to add the locale cookie:
https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorServerSide/Controllers/CultureController.cs

**Comment by adugasBID** [comment]
First off, thank you for your time and your quick replies! It's appreciated.

I'm not sure the CultureController applies to me because I don't use MVC.
But anyways the whole redirect to another page to set the culture is a bit too much in my opinion.

I did try to add the code in Startup.cs and I manually created a cookie (in my browser), but it wasn't enough (no functional change). I guess it really needs to be in the HttpContext.Response.

I wish I could change the grid language with a parameter independently of any cookies the user might have.
This would've been intuitive and elegant:
`var locale = new CultureInfo("en-US");
var client = new GridClient<Order>(q => orderService.GetOrdersGridRows(columns, q), query, false, "ordersGrid", Columns, locale);`

So I guess my request would be: Could the grid use and remember the locale specified at creation ?
It could default to the cookie language if no specific culture is specified (to not break existing grids).

**Comment by gustavnavar** [comment]
Using a controller is the recommended way by Microsoft if you want users to change the language in Blazor Server projects:
https://docs.microsoft.com/es-es/aspnet/core/blazor/globalization-localization?view=aspnetcore-3.1

In the Microsoft documentation you will see another way to create the cookie if you want a single language for all users.

Localization in Blazor Server is more complicated than in Blazor Wasm. In fact is very similar to ASP.NET MVC.

**Comment by adugasBID** [comment]
Thank you for the link.
We're not fans of how Microsoft handle localization, because it seems wasteful and a bit hacky (all that because you can't set cookies while in a blazor session).
We can't know the localization to use for an user before the blazor session starts so we'd need to start it, redirect and then continue.

We already have an "Session" object to track who the user is and a whole system built around it for translation tags / permissions / etc.
So we'd rather continue on that path and not have two different ways of doing things.
We'll live with it.

You can close this because, in the end, the grid works as intended.
Thanks!
