### ISSUE TITLE
Provide a way to query the currently selected row

### ISSUE THREAD

**Issue by simonp2014** [gustavnavar/Grid.Blazor#217]
Therefore are times in my app where I want to restore the previously selected row using GridComponent.SelectRow . However, there doesn't seem to be a way to query which row is currently selected.

I've added a public method like this to GridBlazor/Pages/GridComponent.razor.cs

```
public int GetSelectedRow()
{
	return SelectedRow;
}
```

Please can you add an accessor like this unless there's a better way of achieving a similar result?

**Comment by gustavnavar** [comment]
Package version 1.9.2 implements public getters for ```SelectedRow``` and ```SelectedRows``` properties.

```SelectedRow```  is used for single row selections and  ```SelectedRows```  is used when multiple selection is enabled

**Comment by simonp2014** [comment]
Thank you. Just what I needed!
