### ISSUE TITLE
Localization doesn't work

### ISSUE THREAD

**Issue by jeisonjei** [gustavnavar/Grid.Blazor#218]
Hello, thank you for this project, here is my issue:
In my project it seems like localization doesn't work, 
I tried to specify "ru-RU", "de-DE" - no result - it's anyway in English
Here is the GridClient:
```
protected override async Task OnParametersSetAsync()
    {
        var locale = new CultureInfo("de-DE");
        string uri = nav.BaseUri + "api/vm/grid";
        var query = new QueryDictionary<StringValues>();
        var client = new GridClient<Vm>(Http, uri, query, false, "vmlistgrid", Columns, locale)
            .ChangePageSize(true)
            .Sortable()
            .Filterable()
            .Searchable()
            .Selectable(true);

        grid = client.Grid;
        task = client.UpdateGrid();
        await task;
    }
```
and the result anyway in English:
![image](https://user-images.githubusercontent.com/39847800/96495114-07a6fd00-1250-11eb-89d5-b0ac68a26cd1.png)

**Desktop:**
 - OS: Windows 10
 - Browser : Edge

**Comment by gustavnavar** [comment]
Could you try changing the current culture locale?

```c#
protected override async Task OnParametersSetAsync()
    {
        var locale = new CultureInfo("de-DE");
        CultureInfo.CurrentCulture = locale;
        string uri = nav.BaseUri + "api/vm/grid";
        var query = new QueryDictionary<StringValues>();
        var client = new GridClient<Vm>(Http, uri, query, false, "vmlistgrid", Columns, locale)
            .ChangePageSize(true)
            .Sortable()
            .Filterable()
            .Searchable()
            .Selectable(true);

        grid = client.Grid;
        task = client.UpdateGrid();
        await task;
    }

```

**Comment by gustavnavar** [comment]
You can also take a look to the GridBlazorClientSide sample project. 

This blazor page manage the language selection 
- https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorClientSide.Client/Shared/Language.razor

**Comment by jeisonjei** [comment]
> Could you try changing the current culture locale?
> 
> ```cs
> protected override async Task OnParametersSetAsync()
>     {
>         var locale = new CultureInfo("de-DE");
>         CultureInfo.CurrentCulture = locale;
>         string uri = nav.BaseUri + "api/vm/grid";
>         var query = new QueryDictionary<StringValues>();
>         var client = new GridClient<Vm>(Http, uri, query, false, "vmlistgrid", Columns, locale)
>             .ChangePageSize(true)
>             .Sortable()
>             .Filterable()
>             .Searchable()
>             .Selectable(true);
> 
>         grid = client.Grid;
>         task = client.UpdateGrid();
>         await task;
>     }
> ```

Thank you for reply, 
I tried to do this, no result

**Comment by gustavnavar** [comment]
You can also test adding this:

```c#
    CultureInfo.DefaultThreadCurrentCulture = locale;
    CultureInfo.DefaultThreadCurrentUICulture = locale;
```

**Comment by jeisonjei** [comment]
Hello, turns out that localization works on my colleagues computers. So, it's bizarre - we use the same url, and on my computer whatever I would do - I see only english language. Will try to find the reason why
