### ISSUE TITLE
GridColumn should have a ResourceType property (for title localization)

### ISSUE THREAD

**Issue by phisakel** [gustavnavar/Grid.Blazor#22]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gustavnavar** [comment]
You can use the Title method of the GridColumn object to configure localized title. You can use IStringLocalizer<> or a strongly typed resource class.

I've updated the GridBlazorServerSide sample using a  strongly typed resource class:
```c#
c.Add(o => o.OrderID).Titled(SharedResource.Number).SetWidth(100);
```

Remember that localization only works on Blazor server-side projects. Blazor WebAssembly does not support it yet.
