### ISSUE TITLE
Searching get property

### ISSUE THREAD

**Issue by muratoner** [gustavnavar/Grid.Blazor#220]
i have a simple category table. i want show category with all parents name. For example i have a "Automotive Accessory" category but this "Automotive Accessory" category have parent category and this parent category name is "Automotive". I want show this "Automotive" category record like as "Automotive > Automotive Category". I can show like as "Automotive > Automotive Category". But this get property added linq query when i want to search. Throwed exception when searching get propert and this proeprty doesn't have in table.

**I can show category list with auto generated FullPath named get property.**
![Category List](https://i.imgur.com/4PZN4m7.png)

**Sample category table records**
![Category List](https://i.imgur.com/2fCdFnz.png)

**Throwed exception when i write "cep" in search field**
![Category List](https://i.imgur.com/Ujl2nkg.png)

**Exception Detail**
```
System.InvalidOperationException: 'The LINQ expression 'DbSet<Category>
    .OrderBy(c => c.Id)
    .Where(c => c.FullPath != null && c.FullPath.ToUpper().Contains("CEP"))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
```
**Category Entity**
```
public class Category
{
    public int Id { get; set; }

    public string Name { get; set; }

    public long? N11CategoryId { get; set; }

    public int? TrendyolCategoryId { get; set; }

    public int? EPttAvmCategoryId { get; set; }

    public string GittiGidiyorCategoryId { get; set; }

    public int? ParentCategoryId { get; set; }

    public int CompanyId { get; set; }

    public virtual Company Company { get; set; }
    public virtual Category Parent { get; set; }
    public virtual HashSet<Category> Children { get; set; }

    [NotMapped]
    public string FullPath
    {
        get
        {
            var list = new List<string>();
            var category = this;
            while (category != null)
            {
                list.Add(category.Name);
                category = category.Parent;
            }
            list.Reverse();
            return string.Join(" > ", list);
        }
    }
}
```

**GridShared Columns List**
```
void Columns(IGridColumnCollection<Category> c)
{
    c.Add(o => o.Id)
        .Titled("#")
        .SetWidth(50);

    c.Add(o => o.FullPath) // i don't want search this column because this column is not have in table but i want show.
        .Titled("Adı");

    c.Add(o => o.Name, true); // i want search this hidden column

    c.Add().RenderComponentAs<ActionEdit<Category>>(new List<Action<object>> { (item) => NavigateToEdit((Category)item) }).SetWidth(50);
}
```
 - OS: Windows 20H2  - 19042.608
 - Browser Edge Chromium
 - GridShared 1.9.2

**Comment by gustavnavar** [comment]
Entity Framework Core 3.x does not translate combined columns seach to the server. Take a look at this issue https://github.com/gustavnavar/Grid.Blazor/issues/39#issuecomment-559031039

The best option is to use a keyless entity with a database view that combines the 2 columns.

**Comment by gustavnavar** [comment]
Another option is to use a non-connected column for the ```FullPath``` property:
´´´c#
Columns.Add().RenderValueAs(o => o.FullPath);
´´´
This column will be shown on the grid, but it shouldn't have searching enabled

**Comment by muratoner** [comment]
Thanks @gustavnavar solved to my issue with your code suggestion.
