### ISSUE TITLE
Odata datetimeoffset query string is not valid when we try to filter by datetimeoffset column

### ISSUE THREAD

**Issue by veselinbg** [gustavnavar/Grid.Blazor#225]
**Describe the bug**

Here is the tested link on my local machine. 

The column StartDate is **Datetimeoffset** type!

https://localhost:44321/api/Drawings?$count=true&$expand=DrawedSymbols%2CStatus&$filter=(tolower(StartDate)+eq+%272020-11-03t13%3A00%27)&$top=0

Here is the exception :

{"error":{"code":"","message":"The query specified in the URI is not valid. No function signature for the function with name 'tolower' matches the specified arguments. The function signatures considered are: tolower(Edm.String Nullable=true).","details":[],"innererror":{"message":"No function signature for the function with name 'tolower' matches the specified arguments. The function signatures considered are: tolower(Edm.String Nullable=true).","type":"Microsoft.OData.ODataException","stacktrace":"   at Microsoft.OData.UriParser.FunctionCallBinder.MatchSignatureToUriFunction(String functionCallToken, SingleValueNode[] argumentNodes, IList`1 nameSignatures)\r\n   at Microsoft.OData.UriParser.FunctionCallBinder.BindAsUriFunction(FunctionCallToken functionCallToken, List`1 argumentNodes)\r\n   at Microsoft.OData.UriParser.FunctionCallBinder.BindFunctionCall(FunctionCallToken functionCallToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.BindFunctionCall(FunctionCallToken functionCallToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)\r\n   at Microsoft.OData.UriParser.BinaryOperatorBinder.GetOperandFromToken(BinaryOperatorKind operatorKind, QueryToken queryToken)\r\n   at Microsoft.OData.UriParser.BinaryOperatorBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)\r\n   at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)\r\n   at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()\r\n   at Microsoft.AspNet.OData.Query.FilterQueryOption.get_FilterClause()\r\n   at Microsoft.AspNet.OData.Query.Validators.FilterQueryValidator.Validate(FilterQueryOption filterQueryOption, ODataValidationSettings settings)\r\n   at Microsoft.AspNet.OData.Query.FilterQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ValidateQuery(HttpRequest request, ODataQueryOptions queryOptions)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.CreateAndValidateQueryOptions(HttpRequest request, ODataQueryContext queryContext)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.<>c__DisplayClass1_0.<OnActionExecuted>b__1(ODataQueryContext queryContext)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)"}}}

The grid is readonly. Here is the code of the grid. 

```        
        private CGrid<Drawing> _grid;
        [Inject] HttpClient httpClient { get; set; }

        private Task _task;

        protected override async Task OnParametersSetAsync()
        {
            Action<IGridColumnCollection<Drawing>> drawingColumns = c =>
            {
                foreach (var column in GetColumns1(typeof(Drawing)))
                {
                    var gridColumn = c.Add(column).Titled(Loc(column.Name));
                    if (column.PropertyType == typeof(DateTimeOffset))
                    {
                        gridColumn.SetFilterWidgetType("DateTimeLocal");
                    }
                }
            };
            var query = new QueryDictionary<StringValues>();

            var locale = CultureInfo.CurrentCulture;

            string url = httpClient.BaseAddress + "Drawings";

            var client = new GridODataClient<Drawing>(httpClient, url, query, false, "drawingsGrid", drawingColumns, Constants.Grid_Page_Size, locale, new List<string>() { nameof(Status), nameof(DrawedSymbols) })
             //.SetRowCssClasses(item => item.Customer.IsVip ? "success" : string.Empty)
             .Sortable()
             .Filterable()
             .SetStriped(true)
             .ClearFiltersButton(true)
             .WithMultipleFilters()
             .Selectable(true)
             .WithGridItemsCount()
             .ChangePageSize(true)
             .SetLanguage(locale.Name)
             .SetExcelExport(true, true);

            _grid = client.Grid;
            // Set new items to grid
            _task = client.UpdateGrid();
            await _task;

```

**Comment by veselinbg** [comment]
Hi, 
I continue digging in your project and I find out this. 
If i am using DateTimeLocal the next part format is useless depends on you code which i find.
 `                            return Convert.ToDateTime(x.GetType().GetProperty(column.Name).GetValue(x)).ToLocalTime().ToString();
                        }).SetFilterWidgetType("DateTimeLocal").Format("{0:yyyy-MM-dd HH:mm.fffZ}");
`

Your code: 

`public string GetFormatedDateTime(object value, string type)
        {
            if (value == null)
                return null;
            string textValue;
            if(type == "date")
                textValue = string.Format("{0:yyyy-MM-dd}", value);
            else if (type == "time")
                textValue = string.Format("{0:HH:mm}", value);
            else if (type == "datetime-local")
                textValue = string.Format("{0:yyyy-MM-ddTHH:mm}", value);
            else if (type == "week")
                textValue = string.Format("{0:yyyy}-W{1}", value, DateTimeUtils.GetIso8601WeekOfYear(value));
            else if (type == "month")
                textValue = string.Format("{0:yyyy-MM}", value);
            else if (!string.IsNullOrEmpty(ValuePattern))
                textValue = string.Format(ValuePattern, value);
            else
                textValue = value.ToString();
            return textValue;
        }`

Here is the exception when I try to search on datetime field.
{"error":{"code":"","message":"The query specified in the URI is not valid. The DateTimeOffset text '2020-11-04T11:42' should be in format 'yyyy-mm-ddThh:mm:ss('.'s+)?(zzzzzz)?' and each field value is within valid range.","details":[],"innererror":{"message":"The DateTimeOffset text '2020-11-04T11:42' should be in format 'yyyy-mm-ddThh:mm:ss('.'s+)?(zzzzzz)?' and each field value is within valid range.","type":"Microsoft.OData.ODataException","stacktrace":"   at Microsoft.OData.UriUtils.ConvertUriStringToDateTimeOffset(String text, DateTimeOffset& targetValue)\r\n   at Microsoft.OData.UriParser.ExpressionLexer.TryParseDateTimeoffset(Int32 tokenPos)\r\n   at Microsoft.OData.UriParser.ExpressionLexer.ParseFromDigit()\r\n   at Microsoft.OData.UriParser.ExpressionLexer.NextTokenImplementation(Exception& error)\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseComparison()\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseLogicalAnd()\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseLogicalOr()\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseExpression()\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseParenExpression()\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParsePrimaryStart()\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParsePrimary()\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseUnary()\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseMultiplicative()\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseAdditive()\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseComparison()\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseLogicalAnd()\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseLogicalOr()\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseExpression()\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseExpressionText(String expressionText)\r\n   at Microsoft.OData.UriParser.UriQueryExpressionParser.ParseFilter(String filter)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguration configuration, ODataPathInfo odataPathInfo)\r\n   at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()\r\n   at Microsoft.AspNet.OData.Query.FilterQueryOption.get_FilterClause()\r\n   at Microsoft.AspNet.OData.Query.Validators.FilterQueryValidator.Validate(FilterQueryOption filterQueryOption, ODataValidationSettings settings)\r\n   at Microsoft.AspNet.OData.Query.FilterQueryOption.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.Validators.ODataQueryValidator.Validate(ODataQueryOptions options, ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.Query.ODataQueryOptions.Validate(ODataValidationSettings validationSettings)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ValidateQuery(HttpRequest request, ODataQueryOptions queryOptions)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.CreateAndValidateQueryOptions(HttpRequest request, ODataQueryContext queryContext)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.<>c__DisplayClass1_0.<OnActionExecuted>b__1(ODataQueryContext queryContext)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.ExecuteQuery(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, Func`2 modelFunction, IWebApiRequestMessage request, Func`2 createQueryOptionFunction)\r\n   at Microsoft.AspNet.OData.EnableQueryAttribute.OnActionExecuted(Object responseValue, IQueryable singleResultCollection, IWebApiActionDescriptor actionDescriptor, IWebApiRequestMessage request, Func`2 modelFunction, Func`2 createQueryOptionFunction, Action`1 createResponseAction, Action`3 createErrorAction)","internalexception":{"message":"The time zone information is missing on the DateTimeOffset value '2020-11-04T11:42:00'. A DateTimeOffset value must contain the time zone information.","type":"System.FormatException","stacktrace":"   at Microsoft.OData.PlatformHelper.ValidateTimeZoneInformationInDateTimeOffsetString(String text)\r\n   at Microsoft.OData.PlatformHelper.ConvertStringToDateTimeOffset(String text)\r\n   at Microsoft.OData.UriUtils.ConvertUriStringToDateTimeOffset(String text, DateTimeOffset& targetValue)"}}}}

Here is the uri:

https://localhost:44321/api/Drawings?$count=true&$expand=DrawedSymbols%2CStatus&$filter=(StartDate+eq+2020-11-04T11%3A42)&$top=0

If I add **z** to the end of the date value StartDate+eq+2020-11-04T11%3A42**z**
everything is ok. 

Please check and fix it.

Thank you.

**Comment by veselinbg** [comment]
Is there any progress with this issue ?

**Comment by gustavnavar** [comment]
Package version 2.1.4 has a fix for this error
