### ISSUE TITLE
Russian localization mistakes

### ISSUE THREAD

**Issue by jeisonjei** [gustavnavar/Grid.Blazor#227]
**Describe the bug**
Hello,
thank you for this project,
there is likely mistake in russian localization

![image](https://user-images.githubusercontent.com/39847800/98439265-c3e23d80-2101-11eb-9b23-6d7882dae965.png)

**To Reproduce**
swith to russian localization

**Expected behavior**
The  word **Sum** in the sum row should be written "Сумма" with "у" (0443 Unicode) letter without stroke on the top (1)
And second thing -  there is an element's collision (2) at least as it shows up on my and my collegue's computer

**Comment by gustavnavar** [comment]
GridBlazor 2.1.0 has fixes for these 2 issues

**Comment by jeisonjei** [comment]
Thank you very much!
