### ISSUE TITLE
How to enable sorting and filtering on grid side?

### ISSUE THREAD

**Issue by kalaur** [gustavnavar/Grid.Blazor#228]
How to enable sorting and filtering on grid side?
I have not found a configuration for this.
every time the grid accesses the server

**Comment by gustavnavar** [comment]
Filetering, sorting and searching are always done by the server to minimize data transfer.

**Comment by timbze** [comment]
@kalaur you can pass a list to the grid instead of IQueryable, then data will search only on grid side.
E.g.
```csharp
var data = database.table.Where(i => i.id > 1);
var queryList = data.ToList();
var client = new GridClient<T>(q => GetGridServer(gridName, queryList, columns),
                queryDictionary, false, gridName, columns);
```
