### ISSUE TITLE
Cant create a custom component column

### ISSUE THREAD

**Issue by brentgiesler** [gustavnavar/Grid.Blazor#229]
**Describe the bug**
Nothing renders when I try to create a custom component:

Here's my call:
c.Add().RenderComponentAs(typeof(ButtonCell)).Titled("Test Component Cell");

Here's my component (ButtonCell.razor):

@*<button class='btn btn-sm btn-primary' @onclick="@MyClickHandler">Save</button>*@
Brent

@code {
    [Parameter]
    public CSRsEntity Item { get; set; }

    public void MyClickHandler(MouseEventArgs e)
    {
        Console.WriteLine("Button clicked: Item " + Item.IC_ID);
    }
}

Nothing get's rendered:

![image](https://user-images.githubusercontent.com/10464889/98744570-8e468a00-2377-11eb-8dc0-f72aa6b7a01c.png)

**Comment by brentgiesler** [comment]
Got it solved.  Thanks.

**Comment by wolfgangschneider** [comment]
@brentgiesler  How? , have the same issue

thanks
