### ISSUE TITLE
Filtering and sorting are always active

### ISSUE THREAD

**Issue by faina09** [gustavnavar/Grid.Blazor#23]
Even when in class ColumnCollections a column is defined as not filterable nor searchable e.g.:

`c.Add(o => o.QuantityPerUnit).Sortable(false).Filterable(false);`

the UI always allows sort and filter.
I followed the code, and during the execution of .Filterable(false) the Column property 'FilterEnabled' is set to false, but in class GridHeaderComponentBase<T> this prop is both ignored and set (by who?) to true.

PS:
I like your project very much and I would like to use it as a component for a Open Source CRUD framework I'll try to develop, based on Blazor .NET core 3.0+
I have a lot of questions (the doc and the sample do not cover many of the features) an possibly I would like to partecipate in this project, please let me know!

**Comment by gustavnavar** [comment]
You can configure sorting and filtering at column level or globally at grid level. But currently grid level configuration has higher precedence than column level configuration. 

Can you check how CGrid object is configured?

**Comment by gustavnavar** [comment]
By the way, you can send me all your doubts and I will answer them asap

**Comment by faina09** [comment]
Thank you very much for your clear answer and for your willingness.
It was not clear to me that the CGrid global config has the precedence on single column; knowing this all goes well.
My next step is to try configure each column (visibility, displayed name, sortability, ordinability, ...) using only decorators in class definition. Do you think it is possible?
