### ISSUE TITLE
How can I deselect row by Code ?

### ISSUE THREAD

**Issue by wolfgangschneider** [gustavnavar/Grid.Blazor#231]
Hi

After reload the Grid with other data a row is still selected , its not the previous PK, its the same record position.

Is there a way to deselect GridRow after new loading? Or is there a workaround to achieve this goal?

Thanks Wolfgang

**Comment by gustavnavar** [comment]
If you use the  ```.Selectable(true)``` method (or ```.Selectable(true,false, ...)```) rows should be deselected after a new data load:
https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/Selecting_row.md#selectable-method

**Comment by wolfgangschneider** [comment]
Thanks for quick replay.

I have to describe the issue more in deep:

1) => load the data into the grid  
2) => select a row in the grid => a row is selected e.g second row
3) => load  other data into the grid
3.1) => data are loaded but record 2 is still selected (but contains other data), unfortunately the selected row is used as filter for an other Grid.

Your suggestion:
 switch of selection .Selectable(false) avoid to select a row on an new loaded grid

What I want to achieve:
When the Grid is filled in with new Data , no record should be selected, doesn't mather a row was selected bevor


B.R Wolfgang

**Comment by gustavnavar** [comment]
If new data is loaded on the grid using paging, filtering or sorting buttons of the grid, all selected rows are cleared automatically.

If you want to load new data programmatically, then you must use the ```UpdateGrid``` method of the ```GridComponent``` object instead of the ```UpdateGrid```method of the ```Grid``` object
