### ISSUE TITLE
Editing Primary Key When Crud Insert

### ISSUE THREAD

**Issue by resoftw** [gustavnavar/Grid.Blazor#233]
How to enable editing of primary key when inserting via CRUD? ie. primary key is a string, or non incremental int.

**Comment by gustavnavar** [comment]
You can use the ```SetPrimaryKey(true, false)``` method to define this type of columns: 
https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/Crud.md#column-definition
