### ISSUE TITLE
"Three state sorting"

### ISSUE THREAD

**Issue by RobertoMilani** [gustavnavar/Grid.Blazor#234]
Hello,

seems to me that - after enabling sorting feature for one or more columns - applying sort to a column causes that column can only be sorted ascending or descending but no way to remove sort (by user interface).
So, it will be a nice feature having possibility to enable a three-state sorting: 
no sort -> sort ascending -> sort descending -> no sort again... and so on (as user clicks on column title)

Thanks a lot,
  Roberto

_P.S. In the meanwhile, I'll analyse original source code and - if I'm able to do - I'll try locally to implement this feature, then share my code with all You if interested._

**Comment by gustavnavar** [comment]
GridBlazor 2.1.2 implements this feature
