### ISSUE TITLE
Customizing the sub grid in blazor

### ISSUE THREAD

**Issue by Arnab001** [gustavnavar/Grid.Blazor#235]
I have created a blazor grid along with 1 level of sub grid. I have created the sub grid by using the .subgrid() method of IGridClient. This creates a sub grid for all the grid rows. But I want to have the sub grid for few chosen grid rows. How can I achieve that?

**Comment by gustavnavar** [comment]
This feature is not suported. When subgrids are enabled, they are created for all rows.
