### ISSUE TITLE
Error in OData filtering for column types Guid and DateTimeLocal

### ISSUE THREAD

**Issue by alcor-bg** [gustavnavar/Grid.Blazor#239]
**1. OData Services cannot do lowercase on Guid type.**

When filter is added to a column of type Guid the following URL is passed to OData service:
> https://localhost:44321/api/SomeEndpoint?$count=true&$filter=(tolower(Id)+eq+b4ccc76a-119b-47c3-baca-aee4308e3052)&$top=0

But the service returns an error:
> The query specified in the URI is not valid. No function signature for the function with name 'tolower' matches the specified arguments. The function signatures considered are: tolower(Edm.String Nullable=true).

Proposed fix (tested and working):
Remove adding tolower() function when generating the filter expression for the URL. 
Filename: .\GridShared\Filtering\Types\GuidFilterType.cs -> GetFilterExpression() 
Comment or remove line 103:
```
    //columnName = "tolower(" + columnName + ")";
```

**2. Use full DateTime format when filtering with OData service.**

When filter is added to a column of type DateTimeLocal the following URL is passed to OData service:
> https://localhost:44321/api/SomeEndpoint?$count=true&$filter=(Date+gt+2020-12-08T11%3A27)&$top=0

But the service returns an error:
> The query specified in the URI is not valid. The DateTimeOffset text '2020-12-08T11:27' should be in format 'yyyy-mm-ddThh:mm:ss('.'s+)?(zzzzzz)?' and each field value is within valid range.

Proposed fix (tested and working):
Using full datetime format ("yyyy-MM-ddTHH:mm:ss.fffzzzzzz") when generating the filter expression for the URL.
Filename: .\GridShared\Filtering\Types\DateTimeFilterType.cs
Add GetStringValue() override:
```
public override string GetStringValue(string value)
{
    DateTime datetimeValue = DateTime.Parse(value);
    return datetimeValue.ToString("yyyy-MM-ddTHH:mm:ss.fffzzzzzz", DateTimeFormatInfo.InvariantInfo);
}
```

**Comment by gustavnavar** [comment]
Package version 2.1.4 has a fix for these errors
