### ISSUE TITLE
[Enter] executes the search within the grid

### ISSUE THREAD

**Issue by DrGriff** [gustavnavar/Grid.Blazor#24]
When you have set the grid to be searchable, it would be great to type in the search term and then hit [Enter] to execute the search.  The more we can reduce using the mouse and control behaviour usign the keyboard, the more user-friendly this would be.
Thanks

**Comment by gustavnavar** [comment]
New nuget packages support this feature:
- GridBlazor 1.1.1
- GridMvcCore 2.9.1
- GridShared 2.9.1
