### ISSUE TITLE
Question: can I open subgrids by default and/or programmatically?

### ISSUE THREAD

**Issue by RobKuipers** [gustavnavar/Grid.Blazor#240]
Hi, first; I love the work you've done.
I'm completely new to Blazor, razor and what-not, but this gave productivity a real boost.

Now I have a requirement whereby I'd like all subgrids to be opened on loading by default. 
I haven't found an option on creating the grid, so I was wondering if it can be done programmatically?
I'm using Blazor serverside version.

Any hint would be appreciated.

Best regards,
Rob

**Comment by gustavnavar** [comment]
GridBlazor 2.1.3 supports this feature. 

You have to use the ```SubGrid ``` method with the parameters described [here](https://github.com/gustavnavar/Grid.Blazor/blob/2.1.3/docs/blazor_client/Subgrids.md#subgrid-parameters)

**Comment by RobKuipers** [comment]
Wow, that was quick! Works like a charm.

¡Thanks Gustavo!
