### ISSUE TITLE
Column Rearranging/Selection

### ISSUE THREAD

**Issue by elylv** [gustavnavar/Grid.Blazor#242]
It would be nice if the grid supported a couple of features that are part of the DevExpress Blazor Grid (which is very expensive!)

That grid allows you to drag/drop columns to rearrange them, and resize them:
https://demos.devexpress.com/blazor/GridResizeColumns

It also has a feature where you can click a toolbar button and it pops up a list of all available columns, and lets you choose which ones you would like displayed/hidden:
https://demos.devexpress.com/blazor/GridColumnChooser

Great work on the grid so far, and I hope if you do start charging for this, it will be more reasonably priced than the other commercial offerings :)

**Comment by gustavnavar** [comment]
I will add the first feature in the future. 

The second one is more difficult to implement. I will have to check if I can add it.

On the other side my intention is to keep this project as free. The downside is that I can only expend few hours per week to fix bugs and to add new features.
