### ISSUE TITLE
DateTime filter error on GridClient

### ISSUE THREAD

**Issue by megatron78** [gustavnavar/Grid.Blazor#243]
**Describe the bug**
I'm using GridClient with a model in EF, I have a datetime column. Filter always produces this SQL Query:

SELECT COUNT(*)
FROM [tbl_cntmov_docc] AS [t]
WHERE ([t].[fecha] = '2020-12-04T00:00:00.0000000')

This query always throw a SQL converting error.

In another project I'm using GridODataClient and the filter produces a different SQL Query that works well:

exec sp_executesql N'SELECT COUNT_BIG(*)
FROM [AWM_SERVICIO] AS [a]
WHERE ([a].[SERV_ID] <> 0.0) AND ((((DATEPART(year, [a].[Created_At]) * 10000) + 
(DATEPART(month, [a].[Created_At]) * 100)) + DATEPART(day, [a].[Created_At])) = @__p_0)',N'@__p_0 int',@__p_0=20201215

I don't know how the resulting SQL query is different.

**To Reproduce**
Use GridClient and filter, throw sql error.
Use GridODataClient and filter, the query is OK.

**Expected behavior**
The resulting SQL Query is supposed to be the same in both cases.

Thanks in advance

**Comment by gustavnavar** [comment]
You are right, depending on the back-end that you use the query will be different. It is the back-end that converts filtering, sorting, paging to queries. And it is a combination of components that performs that:

- In the first case you are using ```GridMvcCore``` as back-end. ```GridBlazor``` library creates the query parameters using this (API)[https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/API.md]. ```GridMvcCore``` receives the query parameters and then creates Linq expresions. And finally is the ORM that you use in the project that translates Linq expressions to SQL queries. If you use EF Core, ORM is the combination of ```EntitityFramework``` libraries and the database provider that you use.

- In the second case ```Microsoft.AspNetCore.OData``` is used a back-end.  ```GridBlazor``` library creates an OData query using (OData API)[http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html]. ```Microsoft.AspNetCore.OData``` receives the OData query and creates the SQL query with the help of ```EntitityFramework```

So there in no way to get the same query using both methods. But the results in both cases should be the same and no errors should be thrown.

The ```GridBlazor``` samples https://gridblazor.azurewebsites.net/ produce the following 2 queries when filtering by date:
```sql
SELECT COUNT(*)
FROM [Orders] AS [o]
WHERE [o].[OrderDate] IS NOT NULL AND ([o].[OrderDate] = '2020-12-14T00:00:00.0000000')

exec sp_executesql N'SELECT [t].[OrderID], [t].[CustomerID], [t].[EmployeeID], [t].[Freight], [t].[OrderDate], [t].[RequiredDate], [t].[ShipAddress], [t].[ShipCity], [t].[ShipCountry], [t].[ShipName], [t].[ShipPostalCode], [t].[ShipRegion], [t].[ShipVia], [t].[ShippedDate], [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[IsVip], [c].[Phone], [c].[PostalCode], [c].[Region], [e].[EmployeeID], [e].[Address], [e].[BirthDate], [e].[City], [e].[Country], [e].[Extension], [e].[FirstName], [e].[HireDate], [e].[HomePhone], [e].[LastName], [e].[Notes], [e].[Photo], [e].[PhotoPath], [e].[PostalCode], [e].[Region], [e].[ReportsTo], [e].[Title], [e].[TitleOfCourtesy], [s].[ShipperID], [s].[CompanyName], [s].[Phone]
FROM (
    SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[Freight], [o].[OrderDate], [o].[RequiredDate], [o].[ShipAddress], [o].[ShipCity], [o].[ShipCountry], [o].[ShipName], [o].[ShipPostalCode], [o].[ShipRegion], [o].[ShipVia], [o].[ShippedDate]
    FROM [Orders] AS [o]
    WHERE [o].[OrderDate] IS NOT NULL AND ([o].[OrderDate] = ''2020-12-14T00:00:00.0000000'')
    ORDER BY (SELECT 1)
    OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
) AS [t]
INNER JOIN [Customers] AS [c] ON [t].[CustomerID] = [c].[CustomerID]
INNER JOIN [Employees] AS [e] ON [t].[EmployeeID] = [e].[EmployeeID]
LEFT JOIN [Shippers] AS [s] ON [t].[ShipVia] = [s].[ShipperID]',N'@__p_0 int,@__p_1 int',@__p_0=0,@__p_1=10
```

The first query returns the number of rows and the second one returns the rows to be shown by the grid component.

I also executed the OData sample: https://github.com/gustavnavar/Grid.Blazor/tree/master/GridBlazorOData.Server and I got the following 2 queries:

```sql
exec sp_executesql N'SELECT COUNT_BIG(*)
FROM [Orders] AS [o]
WHERE (((DATEPART(year, [o].[OrderDate]) * 10000) + (DATEPART(month, [o].[OrderDate]) * 100)) + DATEPART(day, [o].[OrderDate])) = @__p_0',N'@__p_0 int',@__p_0=20201221

exec sp_executesql N'SELECT [t].[OrderID], [t].[CustomerID], [t].[EmployeeID], [t].[Freight], [t].[OrderDate], [t].[RequiredDate], [t].[ShipAddress], [t].[ShipCity], [t].[ShipCountry], [t].[ShipName], [t].[ShipPostalCode], [t].[ShipRegion], [t].[ShipVia], [t].[ShippedDate], [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[IsVip], [c].[Phone], [c].[PostalCode], [c].[Region], [e].[EmployeeID], [e].[Address], [e].[BirthDate], [e].[City], [e].[Country], [e].[Extension], [e].[FirstName], [e].[HireDate], [e].[HomePhone], [e].[LastName], [e].[Notes], [e].[Photo], [e].[PhotoPath], [e].[PostalCode], [e].[Region], [e].[ReportsTo], [e].[Title], [e].[TitleOfCourtesy], [s].[ShipperID], [s].[CompanyName], [s].[Phone], CAST(0 AS bit)
FROM (
    SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[Freight], [o].[OrderDate], [o].[RequiredDate], [o].[ShipAddress], [o].[ShipCity], [o].[ShipCountry], [o].[ShipName], [o].[ShipPostalCode], [o].[ShipRegion], [o].[ShipVia], [o].[ShippedDate]
    FROM [Orders] AS [o]
    WHERE (((DATEPART(year, [o].[OrderDate]) * 10000) + (DATEPART(month, [o].[OrderDate]) * 100)) + DATEPART(day, [o].[OrderDate])) = @__p_0
    ORDER BY [o].[OrderID]
    OFFSET @__TypedProperty_3 ROWS FETCH NEXT @__TypedProperty_4 ROWS ONLY
) AS [t]
INNER JOIN [Customers] AS [c] ON [t].[CustomerID] = [c].[CustomerID]
INNER JOIN [Employees] AS [e] ON [t].[EmployeeID] = [e].[EmployeeID]
LEFT JOIN [Shippers] AS [s] ON [t].[ShipVia] = [s].[ShipperID]
ORDER BY [t].[OrderID]',N'@__p_0 int,@__TypedProperty_3 int,@__TypedProperty_4 int',@__p_0=20201221,@__TypedProperty_3=0,@__TypedProperty_4=10
```

I don't  see anything wrong in the SQL query that returns an error in your first case:
```sql
SELECT COUNT(*)
FROM [tbl_cntmov_docc] AS [t]
WHERE ([t].[fecha] = '2020-12-04T00:00:00.0000000')
```

The only difference with my sample is that ```OrderDate``` is ```Nullable``` and ```GridMvcCore``` adds a ```[o].[OrderDate] IS NOT NULL``` clausule.

Is ```[t].[fecha]``` defined as nullable in the database? Can you send the error returned by SQL Server?

**Comment by megatron78** [comment]
The exception returned is:
Msg 241, Level 16, State 1, Line 27
Conversion failed when converting date and/or time from character string.

That's because it executes:
SELECT COUNT(*)
FROM [tbl_cntmov_docc] AS [t]
WHERE ([t].[fecha] = '2020-12-04T00:00:00.0000000')

But if I change to:
SELECT COUNT(*)
FROM [tbl_cntmov_docc] AS [t]
WHERE ([t].[fecha] = '04-12-2020')

It works well.

The column "fecha" is (datetime, null)

**Comment by gustavnavar** [comment]
Can you change the fecha data type to (datetime2(7),null)?

**Comment by megatron78** [comment]
Changing data type to (datetime2(7),null) works very well, thanks a lot.
