### ISSUE TITLE
AddToOnAfterRender() Explication and Examples

### ISSUE THREAD

**Issue by MarkitoAlmeida** [gustavnavar/Grid.Blazor#244]
Hello, Gustav!

First, I would like to thank you for Grid.Blazor library. It has being awesome for the needs in my project.

I would like an explanation about the "AddToOnAfterRender(Func<GridComponent<T>, bool, Task> OnAfterRender);", I did not understand its use. Could you add an explanation and an example into the Gird.Blazor documentation?

Thanks!

Best regards,
Marcos Almeida

**Comment by gustavnavar** [comment]
AddToOnAfterRender is used to add events to a grid compoment that is nested in another component:  https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Events.md#events-for-subgrids-and-nested-crud-subgrids

[This](https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorServerSide/Pages/NestedCrud.razor) is a sample that uses the AddToOnAfterRender method in a Blazor server project. There are also available samples for Blazor Webassembly and Blazor Webassembly with an OData back-end

**Comment by MarkitoAlmeida** [comment]
Thanks, Gustav! This is what I need!
