### ISSUE TITLE
DateTimeOffset OData query issue

### ISSUE THREAD

**Issue by igorgy** [gustavnavar/Grid.Blazor#249]
I have an issue filtering and searching by DateTimeOffset field, i thought i have an issue similar to 
https://github.com/gustavnavar/Grid.Blazor/issues/225
but, i updated and still have it.

My column is described as:
`c.Add(o => o.CreationTime).Filterable(true).Sortable(true).SetInputType(InputType.DateTimeLocal).SetFilterWidgetType("DateTimeLocal").Format("{0:yyyy-MM-dd HH:mm}").SortInitialDirection(GridShared.Sorting.GridSortDirection.Descending);`

where CreationTime is DateTimeOffset.

and it produces the following odata url:

https://localhost:44326/odata/EstimateJobDto?$count=true&$filter=(tolower(CreationTime)+eq+%272021-01-11t13:34:00%2B03:00%27)&$top=0

That gives me the following error:
"The query specified in the URI is not valid. No function signature for the function with name 'tolower' matches the specified arguments. The function signatures considered are: tolower(Edm.String Nullable=true)."

**Comment by gustavnavar** [comment]
GridBlazor 2.1.6 adds filter support to DateTimeOffset columns

**Comment by igorgy** [comment]
thx, works as expected.
