### ISSUE TITLE
Odata enum filter doesn't work

### ISSUE THREAD

**Issue by tony-asu** [gustavnavar/Grid.Blazor#252]
**Describe the bug**

odata enum filters need to have the namespace included   

example:  /odata/Products?$filter=PackageColor eq Namespace.Color’Green’  

https://www.schaeflein.net/filter-using-enum-values-in-odata-v4/

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gustavnavar** [comment]
GridBlazor 2.1.6 fix this bug
