### ISSUE TITLE
Grid loaded with subgrids opened messes up subgrids after going to page 2

### ISSUE THREAD

**Issue by timbze** [gustavnavar/Grid.Blazor#254]
**Describe the bug**
I have not yet tested what is the shortest way to reproduce, but I have a grid where I have SubGrid with `allOpened` set to true.

The grid has more than 1 page (20 rows per page).

The first page loads correctly. Once I go to page 2, all the subgrids are swapped around and no longer under the correct main grid row. Going back to page 1, now page 1 also does not have the correct subgrids under the main rows.

**Comment by gustavnavar** [comment]
Package version 2.1.9 fixes this issue

**Comment by timbze** [comment]
I've confirmed the fix. Thank you!
