### ISSUE TITLE
Allow multiple row selection using the SHIFT key

### ISSUE THREAD

**Issue by openbullet** [gustavnavar/Grid.Blazor#256]
As a user, if I want to be able to select many rows I have to click on each one holding down the CTRL key, which is very time consuming and frustrating.

I would like to be able to select multiple adjacent rows on by clicking on the first row and then clicking on the last row of the interval holding down the SHIFT key, as it happens in most implementations of grids.

Thank you!

**Comment by openbullet** [comment]
@gustavnavar I haven't found any way to contact you privately, so I will just write it here. I would like to offer you monetary compensation to implement this and some more changes. If you're interested, please contact me at ruri@openbullet.dev to discuss further, thanks!

**Comment by gustavnavar** [comment]
@openbullet I've already implemented this feature in GridBalzor 2.1.20. 

Thks, but no complensation is required.

**Comment by openbullet** [comment]
I still would like to donate you some crypto for this nice component you made, if you have a BCH address let me know and I'll send some your way!
