### ISSUE TITLE
Spinner not hidden on error

### ISSUE THREAD

**Issue by davidst** [gustavnavar/Grid.Blazor#259]
**Describe the bug**
If an exception is thrown from the server when creating/updating/deleting a row, then the spinner is still displayed
over the grid and the error message cannot be seen.

**To Reproduce**
1. Go to the create/update/delete page on a grid
2. Make sure the server will throw an exception when saving
3. Click on the Save button
4. See the spinner instead of the error message on the grid

**Expected behavior**
The spinner should be hidden and the error message should be displayed on the create/update/delete page when an exception is thrown from the server.

**Comment by gustavnavar** [comment]
GridBlazor 2.1.12 has a fix for this issue

**Comment by davidst** [comment]
A fix so fast! Thank you for your great job and the awesome project!
