### ISSUE TITLE
rename IGridAnnotaionsProvider -> IGridAnnotationsProvider

### ISSUE THREAD

**Issue by faina09** [gustavnavar/Grid.Blazor#26]
there is only a little mispelling, you may want to rename the file/class in Grid.Blazor\GridBlazor\DataAnnotations and in Grid.Blazor\GridShared\DataAnnotations from  IGrid**Annotaions**Provider to IGridAnnotationsProvider

**Comment by gustavnavar** [comment]
Done

**Comment by faina09** [comment]
nice, thank you!
