### ISSUE TITLE
CRUD

### ISSUE THREAD

**Issue by jtempra** [gustavnavar/Grid.Blazor#27]
Hola Gustau,
Antes que nada muy buen trabajo!
Podrias implementar opción de añadir registro y borrar?
Asi tendriamos un CRUD implementado.
Gràcies
Josep

**Comment by gustavnavar** [comment]
Hola Josep,
lo he pensado varias veces pero nunca me he decidido a hacerlo. Siempre he pensado que deberia hacerse en un formulario modal mas que sobre el mismo grid. Le dare una vuelta al tema y te comento.
Saludos,
Gus

**Comment by jtempra** [comment]
Hola Gus,
Gracias por la respuesta. Efectivamente seria mejor poner un botón ADD que desplegara un modal para las inserciones y un botón DELETE en las filas para su borrado.
Estoy empezando con blazor y me iria muy bien tu Grid...lo veo perfecto (agrupaciones, filtros, totales, subgrids, multiple grids, ...) y si tuviera CRUD ya seria....
Gracias!
Josep

**Comment by faina09** [comment]
Yo tambièn estoy muy interesado en este asunto, y ademàs a tener un **formulario auto-generado** por edit/add/delete. Continuamos comentando aquì!

**Comment by gustavnavar** [comment]
Hola,
la principal razon por la que nunca lo incorpore en la version ASP.NET MVC es porque no me servia en las aplicaciones que yo normalmente hago.
Si os parece os envio los requerimientos que you tenia en un comentario posterior en ingles, para poder dar entrada a mas gente.
Saludos,
Gus

**Comment by gustavnavar** [comment]
Requirements draft:
- Modal form (but not in-line edition)
- Auto-generated form to add, edit, view and delete items
- Field type detection based on column definition
- Lists for drop-drown fields
- Custom forms
- Support for the following grid models:
    - entity
    - view model
- Support of grid models including 1:N relationships
- Support of entities with multiple keys and multiple foreign keys
- Support for Blazor client-side and server-side

Open issues:
- entity IDs must be defined on the grid
- foreign keys defined at column level
- Support of grid models including N:M relationships
- Standardization of CRUD requests and responses:
    - REST webservices for client-side projects
    - services for server-side projects

**Comment by faina09** [comment]
I agree to the all requirements but the first one (partially), as I don't like modals :-)
Anyway I started with a new page dedicated to edit/delete/insert (non in-line edition); the modal version should be similar.
Starting for the edit sample ServerSide in this project, I wrote a single .razor page for the three operations, but at the moment I have trouble generating the fields dynamically using "Field type detection based on column definition". 
Have you guys any hint about how to access the column definition already in the Model for Grid? (`properties = _item.GetType().GetProperties();`? and then?)

**Comment by gustavnavar** [comment]
I've created a new branch for CRUD:
https://github.com/gustavnavar/Grid.Blazor/tree/crud

It has initial support for Read and Update and auto-generates forms for add, edit, view and delete actions.

**Comment by faina09** [comment]
great!! It works fine! I try to understand the code.

**Comment by gustavnavar** [comment]
There is a new version (https://github.com/gustavnavar/Grid.Blazor/commit/e6fd6d8ae80812d233078f5dea16da81b062c649) that includes:
- <select> items on the auto-generates forms
- Create and Update for Blazor Server Apps (these forms on Blazor WabAssembly don't work yet)

**Comment by gustavnavar** [comment]
CRUD support has been released. 

Nuget package version supporting CRUD are:
- GridBlazor: 1.2.0
- GridMvcCore: 2.10.0
- GridShared: 2.10.0

Documentation can be found in:
- Blazor WebAssembly: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/Crud.md
- Blazor Server App: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Crud.md

**Comment by gustavnavar** [comment]
I close this issue as it has been implemented. If there is any issue about it, please reopen the case
