### ISSUE TITLE
Server-side paging?

### ISSUE THREAD

**Issue by Oninaig** [gustavnavar/Grid.Blazor#28]
I see how you are doing paging when doing client-side blazor, but do you have an example of how to get paging working with server-side? On your demo your paging buttons all trigger Ajax calls but the same Ajax calls don't exist in your server side sample code.

Currently I am able to get a grid to render using server-side blazor, but clicking any of the paging buttons does nothing. How should I hook into the individual paging buttons?

**Comment by gustavnavar** [comment]
Have you look at the GridBlazorServerSide project https://github.com/gustavnavar/Grid.Blazor/tree/master/GridBlazorServerSide ?

This is the server-side demo project

**Comment by Oninaig** [comment]
Right i am attempting to build locally but I'm missing all of the sample data. I can create the tables just fine but could you export your sample data used on the demo site so we can use it locally for testing?

**Comment by gustavnavar** [comment]
The SQL Server database is here: https://github.com/gustavnavar/Grid.Blazor/tree/master/GridMvc.Demo/App_Data
