### ISSUE TITLE
Partial data display on Grid

### ISSUE THREAD

**Issue by faina09** [gustavnavar/Grid.Blazor#29]
I would like to limit the records visualized by **GridComponent**:
 e.g. in NorthWind db I want to display only the Products supplied by a specific Supplier, let's say the supplier with ID=1.

I want to use a method to do this dynamically, NOT using `.SetInitialFilter` during column collection definition (that is working).

I try to set a filter SupplierID = 1 in Products on the **code section** of a .razor page, but cannot found how to do (Columns are private in _items, methods like AddQueryParameter etc seem to be not suitable for this, ...)

How can I do? Thank you

**Comment by gustavnavar** [comment]
You can use the method ```GridComponent.AddFilter(IGridColumn column, FilterCollection filters)``` to add a filter dynamically

**Comment by faina09** [comment]
thank you for the hint!
I tried defining a new
 `FilterCollection filters = new FilterCollection(GridFilterType.Equals.ToString("d"), "1");` 
but I was enable to reference the `GridComponent` object (that is defined in html section of razor as `<GridComponent T="Product" Grid="@_grid"...>`) and the `IGridColumn<Product> column` SupplierID.

How can I reach these objects? Thanks

**Comment by gustavnavar** [comment]
You can get a reference to the GridComponent as explained here:
https://docs.microsoft.com/en-Us/aspnet/core/blazor/components?view=aspnetcore-3.0#capture-references-to-components

And for the IGridColumn you can use:
```c#
((IGrid)_grid).Columns.SingleOrDefault(r => r.Name == "OrderID")
```

**Comment by faina09** [comment]
Defining `<GridComponent @ref="_gridComponent" T="Product" ,,,` the code

```
protected override async Task OnAfterRenderAsync(bool firstRender)        {
            var column = ((IGrid)_grid).Columns.SingleOrDefault(r => r.Name == "UnitPrice");// the column must be not hidden
            FilterCollection filters = new FilterCollection(GridFilterType.GreaterThan.ToString("d"), "30");
            await _gridComponent.AddFilter(column, filters);
            await base.OnAfterRenderAsync(firstRender);
        }
```

works fine but only if the column to filter on **is not hidden**.
If I want to filter on an hidden column a workaround may be to define a css for this column, but is there a better approach?

**Comment by gustavnavar** [comment]
If the column is hidden there is no way to select the filter widget. How will you change the filter is the column is hidden?

**Comment by faina09** [comment]
Yes I know, but I am not interested in the filter *widged*. The idea is to display only the products that are supplied by a specific supplier, hence the SupplierID is an unwanted column in the grid of Products.
But I think that a css specifying that column as not visible and with width=0 is ok e.g. 
    `c.Add(o => o.SupplierID).Css("hidden");`
and in CSS
```
.hidden {
    visibility: hidden;
    max-width: 0px;
} 
```
Is there any method to do this?

**Comment by gustavnavar** [comment]
Maybe you can filter the source of the GridServer object:

```c#
var server = new GridServer<Product>(repository.GetAll().Where(r => r.SupplierID == 1) , ... 
```

**Comment by GriesmarThomas** [comment]
Hello @gustavnavar , 
Is there any solution now, to use grid-filter on a hidden column ? Or is it still a limit of the custom filter widget ?

**Comment by gustavnavar** [comment]
GridBlazor v. 1.3.11 support manipulation feature processing (e.g. sorting, grouping, filtering, etc.) on hidden columns. Of course it onlycan be manipulated from external components:

https://github.com/gustavnavar/Grid.Blazor/issues/71

**Comment by GriesmarThomas** [comment]
Thanks a lot for your answer.
