### ISSUE TITLE
Allow CSS theming of grid error text.

### ISSUE THREAD

**Issue by nitroxis** [gustavnavar/Grid.Blazor#291]
I'm customizing the styling of this (really awesome!) grid component. However, the "error" `<p>` appears to be hard coded currently:

https://github.com/gustavnavar/Grid.Blazor/blob/a9bb0892ca01da58b2264819e7bf18e168478acd/GridBlazor/Pages/GridComponent.razor#L89

It would be very helpful if this instead used a class like `.grid-error` instead of element styles to allow styling of this text.

Additionally, I noticed that this element moves the grid down a bit because it is always present, no matter if it's empty or not. Wrapping it in an `@if(!string.IsNullOrEmpty(Error)) { <p>... }` or something similar might make sense. I managed to hide it with a CSS `:empty` selector for now.

**Comment by gustavnavar** [comment]
Package version 2.1.17 supports this feature.

You can override the ```grid-error``` css class or you can use another class setting the ```GridErrorCssClass``` parameter of the ```GridComponent``` object (https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/GridBlazor_configuration.md#gridcomponent-parameters)

**Comment by nitroxis** [comment]
Cool, thanks!
