### ISSUE TITLE
On CRUD Form numeric field (with format #,##0.00) when updated becomes zero 0 [Label: bug & feature]

### ISSUE THREAD

**Issue by borisdj** [gustavnavar/Grid.Blazor#296]
**Describe the bug**
Numeric field with thousands separator when updated gets 0.00 value instead of actual.

**To Reproduce**
IN CODE - Set Format:
`c.Add(o => o.Amount).Format("{0:#,##0.00}");`

ON FORM
1. Add ___________________ ![image](https://user-images.githubusercontent.com/1279604/123663360-9ab02200-d836-11eb-8cdb-e7c4bb95157e.png)

2. Added ________________ ![image](https://user-images.githubusercontent.com/1279604/123705009-a6b3d800-d866-11eb-9ccf-d6adb1397cfa.png)

 **

3. Update _______________ ![image](https://user-images.githubusercontent.com/1279604/123663460-b3b8d300-d836-11eb-9f2d-337766ebb850.png)

4. Updated ______________ ![image](https://user-images.githubusercontent.com/1279604/123705106-c5b26a00-d866-11eb-8f56-476453f4e2de.png)

**Expected behavior**
After update **_Amount_** should be **1,234.57**.
Currently only way for getting correct value is when editing number with 4+ digits to always delete thousands separators in the field and then Save the Form.

Fix should parse correctly separator to number, or not to be shown in the field at all.
Also to note that when using localization de-DE and some other European languages, comma and dot are inverted:
1.234,56
But bug is the same, also goes to zero.

Additionaly it would be best if Field could be configured in such way that thousands separator is shown both when Adding or Updating on FocusOut when switching input to another field. In that case when that number is in Focus then thousands separator is removed in both cases since it can interfere with typing digits. This format is useful to avoid mistakes when typing large numbers.
- In Focus 
![image](https://user-images.githubusercontent.com/1279604/123668536-7c98f080-d83b-11eb-8e03-b914b6224e80.png)
- Out Focus
![image](https://user-images.githubusercontent.com/1279604/123668446-6854f380-d83b-11eb-9826-d14dc9e97909.png)

**Comment by gustavnavar** [comment]
Package 2.1.18 implements your fix.

This sample implements it for the Freight field: https://gridblazor.azurewebsites.net/crud

Thanks for your fix

**Comment by borisdj** [comment]
Glad to help.
