### ISSUE TITLE
Performance : Loading 1000 records taking 15 seconds  using OData

### ISSUE THREAD

**Issue by sannaini** [gustavnavar/Grid.Blazor#298]
**Describe the bug**
Trying to load 1000 records in my project it is taking around 30 seconds , So I checked in gridblazor it is taking 15 seconds.

**To Reproduce**
https://gridblazorodata.azurewebsites.net/changepagesize

**Expected behavior**
How to load records in less time.

**Comment by wolfgangschneider** [comment]
Hi
On my IPhone Xr. Using LTE you example needs approximately 7s for 1000 records

B.R

**Comment by gustavnavar** [comment]
The sample back-end (SQL server + OData) sends all records in  1.5 seconds. It's composed by a small server running the .Net Core app and a separated SQL server, also an small server. You can test it here https://gridblazorodata.azurewebsites.net/odata/orders

The main part of the process happens on the browser. I beleive that Blazor WASM 6.0 will support AOT and multi-thread. 

So I think AOT will increase speed in this case.
