### ISSUE TITLE
improve logging when UpdateGrid doesn't get a valid response

### ISSUE THREAD

**Issue by jcageman** [gustavnavar/Grid.Blazor#3]
**Is your feature request related to a problem? Please describe.**
The endpoint for my GridClient was a faked .json, but it didn't contain the right data format for the ItemsDto, which caused a null response (could also be a null value for Pager or Items). Would have been nice if there was some logging, because currently its a pain to debug Blazor (or am i missing something?)

When calling UpdateGrid the response could be checked or appropriate logging should be in place to easily detect what is going wrong (instead of a stacktrace without even line information)

Thanks for this library by the way, great example!

**Comment by gustavnavar** [comment]
I've just  added a new version that improves response checking in the UpdateGrid method.

I've not added logging because Microsoft is not providing a logging library for Blazor yet. I believe they will not provide such library until Blazor on WebAssembly will suport multi-threading.
