### ISSUE TITLE
Provide ability to change the page size

### ISSUE THREAD

**Issue by DrGriff** [gustavnavar/Grid.Blazor#30]
In [DataTables.net](https://datatables.net/), there's a convenient drop-down next to the grid search functionality that allows the user to change the number or records displayed.

I think that this would be a great addition to the grid functionality.

**Comment by gustavnavar** [comment]
I will add this feature to the pager

**Comment by gustavnavar** [comment]
It has included on the following package versions
GridBlazor: 1.2.3
GridMvcCore: 2.10.1

You can enable it using the ChangePageSize method of the GridClient object (e.g.):

```c#
    var client = new GridClient<Order>(q =>
        orderService.GetOrdersGridRows(ColumnCollections.OrderColumns, q),
        query, false, "ordersGrid", ColumnCollections.OrderColumns, locale)
        .ChangePageSize(true);
```

**Comment by DrGriff** [comment]
This is great, thanks.

**Comment by DrGriff** [comment]
One minor point: when one changes the page-size and then TAB to the next control, this does not take affect.  One has to hit the [Enter] button.  I think it would be useful if it updated when losing focus.

**Comment by gustavnavar** [comment]
It has been corrected in the last commit of the branch https://github.com/gustavnavar/Grid.Blazor/tree/net-core-3.1

**Comment by gustavnavar** [comment]
Nuget packages implementing this changes has been released. They are for .Net Core 3.1-Preview3

- GridBlazor: 1.3.0-Preview3
- GridMvcCore: 2.11.0
- GridShared: 2.11.0
