### ISSUE TITLE
Show alternate row colours

### ISSUE THREAD

**Issue by DrGriff** [gustavnavar/Grid.Blazor#31]
I think that tables with many rows do benefit from having alternate row colour.

I know that there is `SetRowCssClasses`, but I've not been able to get that to work (maybe it's documented?).  If not, I think this would be a useful feature.

**Comment by gustavnavar** [comment]
I will have a look at this after the CRUD feature will be released

**Comment by gustavnavar** [comment]
Last version supports alternate row colour. Nuget package version supporting it are:

- GridBlazor: 1.2.0
- GridMvcCore: 2.10.0
- GridShared: 2.10.0

To enable it you have to call the **SetStriped** method of the **GridClient** object:

```c#
 var client = new GridClient<Order>(q => orderService.GetOrdersGridRows(ColumnCollections.OrderColumns, q),
            query, false, "ordersGrid", ColumnCollections.OrderColumns, locale)
            .SetStriped(true));
```
