### ISSUE TITLE
RenderAsComponent for ChangePageSize?

### ISSUE THREAD

**Issue by rlebowitz** [gustavnavar/Grid.Blazor#318]
I wonder if it's possible to modify the ChangePageSize handler and renderer so that one could specify a different kind of component to indicate and change the page size?  For example, a dropdown, etc.

**Comment by gustavnavar** [comment]
Change page field is embedded in the GridComponent object. It is difficult to add the option to use a custom component.

But it can be easier to add other behaviors for the ChangePageSize input element. What do you want to get? A different selector or different location on the page?

**Comment by rlebowitz** [comment]
The current behavior is fine; I suppose that I can override the CSS to change the appearance myself, but it would be nice if it were in a different location, for example, along side the navigation buttons at the bottom, and sized to the same dimensions?

**Comment by gustavnavar** [comment]
Package 3.0.3 implements a new location of the ChangePageSize input element close to the navigation buttons

**Comment by rlebowitz** [comment]
Great!! I'll give it a try!
