### ISSUE TITLE
Add keyboard navigation of the grid

### ISSUE THREAD

**Issue by DrGriff** [gustavnavar/Grid.Blazor#32]
Many of our users are very keyboard orientated and have mentioned that it would be nice to be able to use the up and down arrows to navigate the grid.  Is that possible?

**Comment by gustavnavar** [comment]
I will add the up and down events to move between pages.

**Comment by DrGriff** [comment]
Maybe:

- [Left] and [right] arrows to navigate between pages

- [Home] to navigate to the first page
- [End] to navigate to the last page
- [Up] and [Down] to navigate from one row to another (if rows are selectable - guess first row would need to be selected by default)

**Comment by gustavnavar** [comment]
This feature will require .Net Core 3.1 because it's necessary to use event's propagation stop.

I will add a new branch  for .Net Core 3.1 support.

**Comment by gustavnavar** [comment]
there is a new commit in the branch https://github.com/gustavnavar/Grid.Blazor/tree/net-core-3.1 including the keyboard navigation.

But no nuget package published yet.

**Comment by DrGriff** [comment]
Would you consider publishing the 3.1 version as a Beta NuGet package?  Is your intention to replace the 3.0 version once 3.1 is fully released by Microsoft?

**Comment by gustavnavar** [comment]
My intention is to publish a preview of the 3.1 version today or tomorrow.

And I don't think that I will produce any other update to the version 3.0

**Comment by gustavnavar** [comment]
Nuget packages implementing this changes has been released. They are for .Net Core 3.1-Preview3

- GridBlazor: 1.3.0-Preview3
- GridMvcCore: 2.11.0
- GridShared: 2.11.0

**Comment by DrGriff** [comment]
May I suggest one improvement that I think would really help?

If the ClientGrid is marked as `.Selectable(true)` then when the grid loads, the first row is automatically selected.

**Current behaviour**

1. Page loads with Grid
2. The [Up] and [Down] arrows don't work
3. The user has to manually select one row using the mouse to get these arrows to work
4. The user clicks the [Right] arrow, this moves us to the second page
5. The [Up] and [Down] arrows again don't work without having to click the grid

This still requires a swapping between the keyboard->mouse->keyboard.

I guess there is a choice in how this should be implemented:

1. The first row should automatically be selected when the page loads (unless the provided Grid State says otherwise)
2. The `.Selectable(true)` could have a new optional parameter that can be set to "true" to control this
3. A method is exposed that allows us to manually select a row, e.g. "Select(int rowOrdinal")
4. An alternative is for the consuming code to control this, allong the lines of this : [post](https://github.com/gustavnavar/Grid.Blazor/issues/40)

The concern would be if the automatic behaviour started to override other expected behaviour....

**Comment by gustavnavar** [comment]
GridBlazor 1.3.2 supports the configuration to automatically select the first row when a page loads.

There is a second parameter of the ```Selectable``` methos to control this behavior.

**Comment by dringwala** [comment]
I have issue with Left and Right arrows for page navigation. I have more columns on grid that it can fit on screen. With that, if i use left or right arrows, page scrolls to left or right without realizing page control also changes to left or right. I have added ctrl qualifier to navigate pages. 
This allows end user to scroll right or left on current page using arrow keys and also page switch using ctrl + [right/left] keys. 
If you provide me access to create pull request, I can push my changes up.

**Comment by gustavnavar** [comment]
You should be able to create a pull request, it is not blocked.

**Comment by gustavnavar** [comment]
The new version of GridBlazor package (1.3.3) implements the following keyboard navigation:
- [Ctrl] + [Left] and [Ctrl] + [Right] arrows navigate between pages
- [Ctrl] + [Home] key goes to the first page
- [Ctrl] + [End] key goes to the last page
- [Ctrl] + [Up] and [Ctrl] + [Down] arrows navigate from one row to another for grids where rows are selectable
- [Tab] key navigates among elements of a filter widget when it is visible
- [Esc] key minimises a filter widget when it is visible
- [Backspace] clear all filters

**Comment by Aelgorn** [comment]
This is low priority, but may I suggest using another sticky than [Ctrl], or provide the ability to override the bindings?

`[Ctrl] + [Left]`/ `[Ctrl] + [Right]` and `[Ctrl] + [Backspace]` are browser-implemented text editing bindings that allow to respectively skip a word backward/forward or delete the previous word

**Comment by gustavnavar** [comment]
GridBlazor 1.3.6 allows to change the modifier key used for keyboard navigation using the ```SetModifierKey``` method of the ```GridClient``` object:

```
    var client = new GridClient<Order>(HttpClient, url, query, false, "ordersGrid", Columns)
        .SetModifierKey(ModifierKey.ShiftKey);
```

The parameter options of the ```SetModifierKey``` method are:
- ```ModifierKey.CtrlKey``` (default value)
- ```ModifierKey.ShiftKey```
- ```ModifierKey.AltKey```
- ```ModifierKey.MetaKey```

The last 2 options can collide with the modifier keys of the browser. The recommended options are ```ModifierKey.CtrlKey``` and ```ModifierKey.ShiftKey```.

**Comment by gustavnavar** [comment]
Keyboard navigation currently has an impact on the grid behavior just after loading it. I someone want to leave his/her opinion, just add a comment on https://github.com/gustavnavar/Grid.Blazor/issues/63

**Comment by gustavnavar** [comment]
Versions before GridBlazor 1.3.9 had the keyboard navigation enabled by default. This feature requires to focus on the grid element, but it can create problems when used on pages with 2 or more grids. As a consequence, starting with version 1.3.9 it has to be explicitly configured for each grid that requires keyboard navigation. Users can enable keyboard navigation between pages using the ```SetKeyboard``` method of the ```GridClient``` object:

 ```c#
     var client = new GridClient<Order>( ... ).SetKeyboard(true);
```

The parameter default value is ```false```.
