### ISSUE TITLE
SetListFilter - ui improvments and shurtcuts

### ISSUE THREAD

**Issue by k-u-s** [gustavnavar/Grid.Blazor#320]
**Is your feature request related to a problem? Please describe.**
Here are couple of feature for list filter that i think could be usefull.

First is that if list filter has more then few options list expands indefinitely making it looks strange. 
Second i think it would be nice to have ability to quickly select/unselect all elements for situations when for eq you want to select 13 out of 15 elements it would help to click select all and then deselect just those 2 options. 
Last feature is ability to filter visible items by typing search phrase.

**Describe the solution you'd like**
Extend StListFilter method to parametrization
- Add custom class or height/max-height to params
- Add param that allows to display select/un-select all buttons.
- Add param that will display input that allows to filter list content (only filters displeyd items do not clear already selected values).

**Describe alternatives you've considered**
Custom filter.

**Additional context**

Current look:

![image](https://user-images.githubusercontent.com/7735824/141976188-a4a1bb19-1a9b-4d6e-99e5-d5cf46c76cd8.png)

Desired look:

![image](https://user-images.githubusercontent.com/7735824/141977079-19736138-a799-4209-9ab8-b0f5b6d94434.png)

I can implement it if you find it useful.

**Comment by gustavnavar** [comment]
I think it can be very usefull. Thanks for your collaboration.
