### ISSUE TITLE
Checkbox columns non proper rendered in CRUD

### ISSUE THREAD

**Issue by faina09** [gustavnavar/Grid.Blazor#321]
input type=checkbox should not apply class "form-control", but "form-check"
In bootstrap5 this is render in the CRUP pages as a small long textbox and not as a checkbox.   

There are no occurrences of bit fields in Grid.blazor crud samples, I add one in my project and add to function in class ColumnCollections the column definition like this `c.Add(o => o.IsThisRequired).Titled("Require this")`.  
This is still rendered as a checkbox in bootsrap3 - even if the applied class is non corrected, but not if last version bootsrap5 is used.

The correct class to apply if "form-check"

**Comment by gustavnavar** [comment]
Package 3.0.3 fixes this issue

**Comment by faina09** [comment]
it's ok, tnx!
