### ISSUE TITLE
[Question] GridCoreServer

### ISSUE THREAD

**Issue by jcantrel** [gustavnavar/Grid.Blazor#323]
I am trying to implement GridBlazor, but the documentation is not clear on GridCoreServer. It is used in the service, and has parameters, but even with the main four parts imported (@using GridBlazor, @using GridBlazor.Pages, @using GridShared, @using GridShared.Utility) I get an error in my service of "type or namespace name 'GridCoreServer' could not be found"

Having only recently started migrating our applications to Blazor I could be missing something obvious, but my research has only led me back to this repository.

**Comment by gustavnavar** [comment]
GridCoreServer is in package GridCore.Server.

If you download the sourcecode, you can compile the samples for each type of Blazor applications. The directories including the samples are describre [here](https://github.com/gustavnavar/Grid.Blazor#folder-description)
