### ISSUE TITLE
Unable to compile the code.

### ISSUE THREAD

**Issue by jaiprakasho** [gustavnavar/Grid.Blazor#324]
error CS0115: 'SubGridComponent<T>.OnParametersSetAsync()': no suitable method found to override

and a similar bunch of CS0155 errors coming.

Where am I going wrong?

**Comment by martinb69** [comment]
It compiles fine with Visual Studio 2022

**Comment by jaiprakasho** [comment]
Yes compiled fine with VS 2022 ...Had problem with VS2019
