### ISSUE TITLE
Arabic Localization - ar-EG

### ISSUE THREAD

**Issue by IslamHassanAli** [gustavnavar/Grid.Blazor#327]
Please , can you add Arabic Localization. 

Add | اضافة
All | الكل
And | و
Apply | تطبيق
Average | المتوسط
Back | رجوع
No | لا
Yes | نعم
Clear all filters | حذف   كل التصفية
Clear filter | حذف   التصفية
Code | كود
Code and confirmation code must be equal to delete this item | الكود   وتأكيد الكود يجب أن يكونوا متطابقين لحذف العنصر
Code and confirmation code must be equal to save this item | الكود   وتأكيد الكود يجب أن يكونوا متطابقين لحفظ العنصر
Confirm Code | تأكيد   الكود
Contains | تحتوي   على
Create item | اضافة   بيان
There are no items to display | لا   يوجد عناصر
Delete | حذف
Delete item | حذف   عنصر
Edit | تعديل
Ends with | ينتهي   ب
Equals | تساوي
Drop columns here for column extended sorting | اسحب   العمود لتمديد الترتيب
Files | الملفات
Filter this column | تصفية   بيانات العمود
Type | النوع
Value | القيمة
Greater than | أكبر   من
Greater than or equals | أكبر   من أو يساوي
Drop columns here for column grouping | أسحب   العمود هنا لعمل تجميع للبيانات
Is null | فارغ
Is not null | غير   فارغ
Items | العناصر
Less than | أقل   من
Less than or equals | أقل   من أو يساوي
Max | أكبر   قيمة
Min | أقل   قيمة
None | بدون
Not equals | لا   تساوي
Or | أو
Read item | عرض   العنصر
Save | حفظ
Search for ... | بحث   عن ...
Search phrase | جملة   البحث
Select | أختر
--- Select an item --- | أختر   عنصر
Show | عرض
Starts with | يبدأ   ب
Sum | المجموع
Update item | تعديل   عنصر
View | عرض
There was an error creating the new item | حدث   خطأ اثناء اضافة هذا العنصر
There was an error deleting this item | حدث   خطأ اثناء حذف هذا العنصر
There was an error updating this item | حدث   خطأ اثناء تعديل هذا العنصر
You must select the row you want to delete | يجب   اختيار العنصر المراد حذفه
You must select the row you want to view | يجب   اختيار العنصر المراد عرضه
You must select the row you want to edit | يجب   اختيار العنصر المراد تعديله

**Comment by IslamHassanAli** [comment]
[https://docs.google.com/spreadsheets/d/1_JGlYYpkVfbPgxpdCJJRJbHJkg9eNypl/edit?usp=sharing&ouid=107794691596334086798&rtpof=true&sd=true](https://docs.google.com/spreadsheets/d/1_JGlYYpkVfbPgxpdCJJRJbHJkg9eNypl/edit?usp=sharing&ouid=107794691596334086798&rtpof=true&sd=true)

**Comment by gustavnavar** [comment]
Could you send me the translation of "Go to". I forgot to add it to the documentation and it's used from version 3.0.3.

In the other hand, is this translation only valid for "ar-EG"? Or can also be used for generic "ar"?

**Comment by IslamHassanAli** [comment]
Go to |  أذهب إلى

And yes it can be used for generic "ar"

Thanks for your response

**Comment by gustavnavar** [comment]
Package 3.1.1 includes Arabic localization

**Comment by IslamHassanAli** [comment]
Thanks @gustavnavar
