### ISSUE TITLE
Excel export dropping leading zeroes

### ISSUE THREAD

**Issue by GodfreyHlongwane** [gustavnavar/Grid.Blazor#329]
**Describe the bug**
I am using Grid Blazor to display data from an SQL Database. All fields displayed are stored as varchar in the database. I have a field called serial number which is displayed as follows: 

![image](https://user-images.githubusercontent.com/48016139/150470501-fd154e36-fe9a-442e-848f-728fa991c40e.png)

upon exporting the field, the zero at the beginning of the string is lost. I tried formatting it without success

![image](https://user-images.githubusercontent.com/48016139/150470987-86981c2e-e5ea-49fa-b58b-102c3a34f6b4.png)

This is the view I get in excel after exporting:

![image](https://user-images.githubusercontent.com/48016139/150470677-d4f335ed-0ec7-40ea-bb28-afd6555405d6.png)

I expected the export to display data as is. Not sure if anyone has a solution available that can assist me.

I am running a Blazor.net project with GridCore 5.0.3

**Comment by gustavnavar** [comment]
You can apply the 000000000000 format to the D column directly in Excel

**Comment by tony-asu** [comment]
This might be fixed thanks to the fix for #362 

Assuming the data with leading 0's is a string
