### ISSUE TITLE
GoToPage option not coming at footer

### ISSUE THREAD

**Issue by pankajgt125** [gustavnavar/Grid.Blazor#330]
**Describe the bug**
for me at footer "GO to Page" option not coming at all

**To Reproduce**
grid is loading , pagination also enabled but "go to page" option not coming

**Expected behavior**
as per below link "go to page" option should come at footer section.
 https://gridblazor.azurewebsites.net/

**Screenshots**
![image](https://user-images.githubusercontent.com/53227644/151577813-5d59d22a-5026-41d4-bbdc-830516ebdaf4.png)

**Comment by gustavnavar** [comment]
This feature was added in version 3.0.3. What version of GridBlazor package are you using?

Another option, if you are using Blazor Wasm, maybe the library is not updated in the browser cache. Can you delete files and images stored in your browser?
