### ISSUE TITLE
Checkboxes reset on StateHasChanged

### ISSUE THREAD

**Issue by twisted89** [gustavnavar/Grid.Blazor#337]
There seems to be conflicting information on how to handle the checkbox column on state changes. 

Your documentation says to use "shouldRender", which prevents the checkboxes from resetting but completely breaks updating information on the rest of the page. Not really a solution. 

In the report here https://github.com/gustavnavar/Grid.Blazor/issues/178
You say there's no need to use "shouldRender" and it should work fine, but it doesn't.

Subscribing to RowCheckboxChanged and calling StateHasChanged(); allows my fields to update but all of the column checkboxes reset to unchecked.

I've tried using solutions suggested elsewhere such as Task.Yield() to no success. Can you please look into this and provide a working solution that doesn't break field updates outside of the grid?

**Comment by gustavnavar** [comment]
In version GridBlazor 3.2.10, the ```ExceptCheckedRows``` dictionary is only initialized when the ```GridComponent``` object is created. In previous versions it was initialized when the ```OnParametersSet``` was executed (when the component was initialized and when the parent component was re-rendered).

The initialization of this dictionary caused that all checkboxes where reset.
