### ISSUE TITLE
GridShared nuget packet is misbuilt

### ISSUE THREAD

**Issue by Splamy** [gustavnavar/Grid.Blazor#338]
**Describe the bug**
The `GridShared` project multitagets `netstarndard2.1`,`net5.0`,`net6.0` but the nuget package only has the libs for `netstarndard2.1` and `net5.0`.
This is causing some weird dependency problems in one of our blazor webassembly.

When I build the nuget package manually form source it's packed correctly with all 3 targets, so I don't know what's causing the problem with your published nuget package.

**Screenshots**
![nuget package explorer](https://user-images.githubusercontent.com/6502527/157878778-0710a659-4352-4119-a2d0-176c4721b590.png)

**Comment by gustavnavar** [comment]
Version 5.2.1 should contain all binaries

**Comment by Splamy** [comment]
Thanks
