### ISSUE TITLE
Add CSS classes override options

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [gustavnavar/Grid.Blazor#34]
**Is your feature request related to a problem? Please describe.**
The CSS classes of the grid are mostly hardcoded, there is no way to change them without modifying the source. In particularly, the `<table>` class itself is hardcoded as `table grid-table`:
https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazor/GridComponent.razor#L140

However, when working with Boostrap templates or just customizing the look of the table, it is mandatory to make changes to the classes., for example:
`<table id="user-list" class="table table-striped table-bordered table-td-valign-middle table-sticky-first-column text-nowrap m-0">`

All other `grid-*` classes should be overridable too.

**Describe the solution you'd like**
Instead of hardcoding CSS classes, use parameters: `TableCssClass`, `GridHeaderCssClass`, `GridCellCssClass`, `GridSubGridCssClass`, `GridRowCssClass` etc. 

**Additional context**
Same goes for being able to customize the `<table>` HTML `id`.

**Comment by ZimM-LostPolygon** [comment]
This will also fix https://github.com/gustavnavar/Grid.Blazor/issues/31 automatically.

**Comment by gustavnavar** [comment]
Nuget packages implementing this changes has been released. They are for .Net Core 3.1-Preview3

- GridBlazor: 1.3.0-Preview3-2
- GridMvcCore: 2.11.2
- GridShared: 2.11.2

Referring issue https://github.com/gustavnavar/Grid.Blazor/issues/31 you can use an striped grid as follows
- Blazor: 
    - Use ```SetStriped(true)``` method of ```GridClient``` object
    -  Adding a ```table-striped``` class to the table (for all grids except those containing subgrids)
- ASP.NET Core MVC:
    - Use ```SetStriped(true)``` method of ```GridServer``` object
    - Use ```SetStriped(true)``` method of ```Grid``` html helper
