### ISSUE TITLE
Sorting and filtering for component columns

### ISSUE THREAD

**Issue by comichael** [gustavnavar/Grid.Blazor#341]
As the documentation states, sorting and filtering will not work on custom columns.

I have a column rendered as an Input field Blazor component, with numeric values, and my client has requested filtering and sorting on this column.

It would be appreciated if this was implemented.

If it is unlikely that this will be done, could anyone point me in the right direction? Alternatively, if anyone has already done it, could you show some code samples?

**Comment by gustavnavar** [comment]
Maybe you can use a database view (https://github.com/gustavnavar/Grid.Blazor/issues/39)

Could you describe how this column is related to the database fields?
