### ISSUE TITLE
Make RenderValueAs Columns searchable

### ISSUE THREAD

**Issue by martinscholz83** [gustavnavar/Grid.Blazor#343]
**Is your feature request related to a problem? Please describe.**
I you render a column with `RenderValueAs`, this column is not searchable by the rendered value.
For example
```C#
c.Add(o => o.ServerProtocol).Titled("Server Protocol").Sanitized(false).RenderValueAs(o => {
                return o.ServerProtocol switch {
                    0 => "Unkonwn",
                    1 => "SOAP",
                    2 => "gRPC",
                    _ => "Unknown",
                };
            });
```

**Describe the solution you'd like**
Any custom search method on this cell, or in general make custom rendered values searchable. Maybe there is some way already and I just don't know.

**Comment by gustavnavar** [comment]
Filtering, sorting and searching are performed by the database  depending on the column definition (in your case is based on ```o => o.ServerProtocol```) 

The best way to make it work is to define a database view as describe [here](https://github.com/gustavnavar/Grid.Blazor/issues/39)
