### ISSUE TITLE
Multiple filters not working

### ISSUE THREAD

**Issue by martinscholz83** [gustavnavar/Grid.Blazor#344]
**Describe the bug**
If you create multiple filters with `AND` or `OR`, only the first filter will apply.
This happens to all kind of columns, string, number, bool, ...

**To Reproduce**

**Expected behavior**
Both filters should apply.

**Screenshots**

<img width="248" alt="Bildschirmfoto 2022-04-28 um 13 06 14" src="https://user-images.githubusercontent.com/19551763/165738984-414473a7-1ea1-49df-8f14-bbd3c3627a6c.png">

and after apply

<img width="309" alt="Bildschirmfoto 2022-04-28 um 13 06 47" src="https://user-images.githubusercontent.com/19551763/165739082-702fcdaa-4916-4a4e-9d6a-0a2dd41c9827.png">
**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome, safari

**Smartphone (please complete the following information):**

**Additional context**

**Comment by gustavnavar** [comment]
I can not reproduce this error. I've used several filters on the demo web and no issues where detected https://gridblazor.azurewebsites.net/

**Comment by mattiaslundborg** [comment]
I'm having the same issue. I add multiple filters to one column but when pressing 'apply' it only saves the first filter. Exactly as this issue.

Did you solve this problem/issue @martinscholz83 ?

@gustavnavar i'm setting '.Filterable(true)' to my GridClient, am i missing something else for it to work for multiple filters?

Thanks
/Mattias

**Comment by shyftkenney** [comment]
We are seeing the same issue.

**Comment by mattiaslundborg** [comment]
@shyftkenney what do you mean with component? I have my component:

<GridComponent T="TaskModel" Grid="@_grid"></GridComponent>

and my "_grid" has all my columns.

**Comment by gustavnavar** [comment]
The GridClient column definition used on the razor page and the GridServer column definition must be the same.

The samples use static column definition to use it in both GridClient and GridServer constructors.

**Comment by martinscholz83** [comment]
That means if you don't configure all members of a Model in your GridClient you add to GridServer constructor this will fail?

For example

```C#
class MyModel {
    public string Member1 {get;set;}
    public string Member2 {get;set;}
    public string Member3 {get;set;}
}
...
...
Action<IGridColumnCollection<MyModel>> columns = c =>
        {
            c.Add(o => o.Member1);
            c.Add(o => o.Member2);
            
        };
...
...
var items = new List<MyModel>();
// fill items
var server = new GridServer<Setting>(items, ....
```

**Comment by gustavnavar** [comment]
Are you using Blazor WebAssembly or Blazor Server?

How do you configure the GridClient object?  Using the same column definition?
````
Action<IGridColumnCollection<MyModel>> columns = c =>
{
    c.Add(o => o.Member1);
    c.Add(o => o.Member2);        
};
...
...
var client = new GridClient<Setting>(httpClient, url, query, false, "settingsGrid", columns, locale)
```

**Comment by martinscholz83** [comment]
We use Blazor Server. There was an issue in my example. It should be
```
var server = new GridServer<MyModel>(items, ....
```
MyModel should just demonstrate the case not using all members. It's not the real class we use.
This is how we create the client
```
var client = new GridClient<MyModel>(q => _service.GetSettingsGridRows(columns, q), query, false, "settingsGrid", columns).Searchable(true, false, true).Sortable().Filterable().Selectable(true, false, true).ChangePageSize(true); ;
```

**Comment by martinscholz83** [comment]
Here is test project you can use for reproducing the issue. https://github.com/martinscholz83/GridTest

**Comment by martinscholz83** [comment]
You will see adding a second filter for the CustomerID column will fail.

**Comment by martinscholz83** [comment]
That was fast :). Fix is working for me!
