### ISSUE TITLE
General improvements to filtering

### ISSUE THREAD

**Issue by DrGriff** [gustavnavar/Grid.Blazor#35]
Following are a few ideas for improving the column filtering function:

- **Filtering Type**:  I would suggest that "Contains" is more useful than "Equals" (for strings) because it allows users to type in just a partial string.
- **Filtering Type**:  To help with keyboard navigation, when the Filter component displays, the cursor should be within this field, allowing the user to Tab from one control to another.
- **[Esc]**:  Having expanded the filter, the "Escape" button should minimise it (currently, one has to click back on the filtering icon).
- **Clear all**:  There should be a mechanism to clear all existing filters applied to the table.  Again, this should be accessible to keyboard users as well as mouse users.

**Comment by gustavnavar** [comment]
Nuget packages implementing the 3 first changes has been released. They are for .Net Core 3.1-Preview3.

- GridBlazor: 1.3.0-Preview3
- GridMvcCore: 2.11.0
- GridShared: 2.11.0

The last change regarding clearing all filters is pending.

**Comment by DrGriff** [comment]
Having upgraded to:

```
 <PackageReference Include="GridBlazor" Version="1.3.0-preview3" />
 <PackageReference Include="GridMvcCore" Version="2.11.0" />
 <PackageReference Include="GridShared" Version="2.11.0" />
```

When I navigate to the page that contains my grid, I get the following error:

> blazor.server.js:15 [2019-11-29T10:52:58.788Z] Error: Microsoft.JSInterop.JSException: Could not find 'gridJsFunctions' in 'window'.
> Error: Could not find 'gridJsFunctions' in 'window'.
>     at https://localhost:44323/_framework/blazor.server.js:8:30748
>     at Array.forEach (<anonymous>)
>     at p (https://localhost:44323/_framework/blazor.server.js:8:30709)
>     at https://localhost:44323/_framework/blazor.server.js:8:31416
>     at new Promise (<anonymous>)
>     at e.beginInvokeJSFromDotNet (https://localhost:44323/_framework/blazor.server.js:8:31390)
>     at https://localhost:44323/_framework/blazor.server.js:1:19202
>     at Array.forEach (<anonymous>)
>     at e.invokeClientMethod (https://localhost:44323/_framework/blazor.server.js:1:19173)
>     at e.processIncomingData (https://localhost:44323/_framework/blazor.server.js:1:17165)
>    at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
>    at Microsoft.JSInterop.JSRuntimeExtensions.InvokeVoidAsync(IJSRuntime jsRuntime, String identifier, Object[] args)
>    at GridBlazor.GridComponentBase`1.OnAfterRenderAsync(Boolean firstRender)
>    at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

**Comment by gustavnavar** [comment]
I added  the following comment to the Readme file on the .net core 3.1 branch, but it's clear that is not enough:

**Important**: Blazor Server App require these changes on to the _Host.cshtml file for .Net Core 3.1:
```
    <link href="_content/GridBlazor/css/gridblazor.css" rel="stylesheet" />
    <script src="_content/GridBlazor/js/gridblazor.js"></script>
```

Sorry about this

**Comment by gustavnavar** [comment]
A new button to clear all filters has been added in GridBalzor 1.3.3.

It is also accessible pressing the "Backspace" key.

**Comment by Aelgorn** [comment]
After updating, pressing on backspace while inside of the search box clears the filters and restores the state fo the search box to whatever it was before modifying it.
Might I suggest instead of using the "Backspace" key alone, to use "Ctrl", or another combination?

**Comment by gustavnavar** [comment]
GridBlazor v. 1.3.4 supports "Ctrl" + "Backspace" to clear all filters.

**Comment by rdeherder** [comment]
> **Important**: Blazor Server App require these changes on to the _Host.cshtml file for .Net Core 3.1:
> 
> ```
>     <link href="_content/GridBlazor/css/gridblazor.min.css" rel="stylesheet" />
>     <script src="_content/GridBlazor/js/gridblazor.js"></script>
> ```

This also needs to be added for Blazor Server .NET 7 to resolve this exception:

Microsoft.JSInterop.JSException: Could not find 'gridJsFunctions.isDateTimeLocalSupported' ('gridJsFunctions' was undefined).
Error: Could not find 'gridJsFunctions.isDateTimeLocalSupported' ('gridJsFunctions' was undefined).

I did not find this in the documentation for the ServerSide version.

**Comment by gustavnavar** [comment]
Hi,

 

it is commented here: 

https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Installation.md#installation

 

Best,

Gus

 

De: rdeherder ***@***.***> 
Enviado el: dijous, 13 d’abril de 2023 17:16
Para: gustavnavar/Grid.Blazor ***@***.***>
CC: Gustavo Navarro ***@***.***>; State change ***@***.***>
Asunto: Re: [gustavnavar/Grid.Blazor] General improvements to filtering (#35)

 

Important: Blazor Server App require these changes on to the _Host.cshtml file for .Net Core 3.1:

    <link href="_content/GridBlazor/css/gridblazor.min.css" rel="stylesheet" />
    <script src="_content/GridBlazor/js/gridblazor.js"></script>

This also needs to be added for Blazor Server .NET 7 to resolve this exception:

Microsoft.JSInterop.JSException: Could not find 'gridJsFunctions.isDateTimeLocalSupported' ('gridJsFunctions' was undefined).
Error: Could not find 'gridJsFunctions.isDateTimeLocalSupported' ('gridJsFunctions' was undefined).

I did not find this in the documentation for the ServerSide version.
