### ISSUE TITLE
[Question] How to use with my own API of another protocol than json (gRPC)?

### ISSUE THREAD

**Issue by Dunge** [gustavnavar/Grid.Blazor#350]
So you have 3 modes, one using your custom GridCore back-end, one using the OData standard, but both are JSON format that needs a server-side back-end controller to expose the data. You also have the "local data" mode that ultimately runs the GridCore module on the WASM client but requires the entity framework repository to be local too.

My application is a WASM client that connects to the server via a gRPC channel. It handle all authentication and security needs and I wish to pass my data through it. I already have my own method to launch the query which return a data set on which I can pass any parameters. I wish I would not have to revert to creating a normal json HTTP ASP Controller for handling the grid queries.

I managed to "hack" my way around by using the "local data" sample and  work around the IQueryable to pass my parameters that way:

Service:
```
public class ComponentService
{
    private readonly gRPCClient _client;

    public ComponentService(gRPCClient client)
    {
        _client = client;
    }

    public async Task<ItemsDTO<Component>> GetComponentGridRows(Action<IGridColumnCollection<Component>> columns, QueryDictionary<StringValues> query, ComponentType type, string differentThanVersion)
    {
        var server = new GridCoreServer<Component>(new List<Component>().AsQueryable(), query, true, "componentGrid", columns, 10);

        var items = await server.GetItemsToDisplayAsync(async t => await _client.GetComponents(type, differentThanVersion));
        return items;
    }
}
```

Grid Client:
```
GridClient = new GridClient<Component>(q => _componentService.GetComponentGridRows(columns, q, SelectedComponentType, LatestVersion.Version), query, false, "componentGrid", columns)
```

As you can see, I pass my own special query parameters to the `GetComponentGridRows` method which in turn is passed to my gRPC query parameters in `GetItemsToDisplayAsync`. This actually work.

The problem is the fake `IQueryable` I had to create as the first parameters of GridCoreServer (`new List<Component>().AsQueryable()`). Due to this, all the queryable parameters coming from the client grid widget itself (paging, sorting, filtering) get ignored.

Obviously, I can't return a IQueryable through the gRPC channel, only a pure resulting list. The Repository isn't on the client side, it's on the server side. I could probably decode the IQueryable parameters and pass it to my method (skip, take, etc) one my one, but I don't think it's a good direction to go. I could also have the GridCoreServer living on my server replying an ItemDTO via this protocol, but the GridClient wouldn't be capable of handling it.

Any suggestion?

**Comment by gustavnavar** [comment]
I´m adding support for gRPC protocol between the WASM client and the server executing GridCoreServer. It's currently working fine. But I will need some days to deploy a new package, write some samples and update the documentation

**Comment by gustavnavar** [comment]
GridBlazor 3.3.0 and GridCore 5.3.0 support gRPC.

There is no documentation yet. But samples are available:
- https://github.com/gustavnavar/Grid.Blazor/tree/master/GridBlazorGrpc.Client
- https://github.com/gustavnavar/Grid.Blazor/tree/master/GridBlazorGrpc.Server
- https://github.com/gustavnavar/Grid.Blazor/tree/master/GridBlazorGrpc.Shared

**Comment by Dunge** [comment]
Great work, absolutely impressive you added full support less than one week after I created the issue! I'll close this now since it fullfil me request perfectly.
