### ISSUE TITLE
Component columns render nothing

### ISSUE THREAD

**Issue by Dunge** [gustavnavar/Grid.Blazor#351]
My desire is to display a progress bar in one of my columns based on data that comes elsewhere than the grid query, and only use the grid entity's id to match up. Nothing fancy like a CRUD editor as in the samples.

Based on [this documentation page](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_local/Custom_columns.md) I added a component column in my grid:

`Columns.Add().RenderComponentAs(typeof(TaskProgress));`

I then created a .razor file with my component and added a `Item` [Parameter] of the type of my Grid entity as documented. Strangely it told me the parameter needs to be public and not protected as in the sample..

Even with the most basic content (static "\<h3>test\</h3>" text), nothing appears in the grid. Component renders fine when I put it elsewhere in my page.

Any suggestion on how to debug why it is not showing up?

**Comment by Dunge** [comment]
Ok, this is something that is explained in the [Render button, checkbox, etc. in a grid cell](https://github.com/gustavnavar/Grid.Blazor/blob/990ab514facc48237427ffd29381097e83ae8fe7/docs/blazor_local/Render_button_checkbox_etc_in_a_grid_cell.md) page but not the [Custom columns](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_local/Custom_columns.md) page in the section mentioning it.

It's simply a matter the your component must `@implements ICustomGridComponent<T>`.

I suggest you add a quick note in the column doc page in order to prevent others to fall in the same hole. I'll leave this issue open for that, feel free to close!

**Comment by gustavnavar** [comment]
Thanks for your suggestion, The documentation has been updated.
