### ISSUE TITLE
Totals column calculated by other totals

### ISSUE THREAD

**Issue by comichael** [gustavnavar/Grid.Blazor#356]
I need to calculate the overall performance factor (total planned hours vs total actual hours) based on search / filtering - e.g what is currently shown in the grid.

Each grid row has fields "Planned Hours" and "Actual Hours". In the "Totals" / summary, I have the totals needed. I just need to add a simple calculation based on those  totals, and put it in another total field called "Performance Factor". 

Is there a way to do that?

**Comment by gustavnavar** [comment]
Package version 3.4.0 supports this feature.

You can find more info [here](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/Totals.md#calculated-totals)

The samples also include this functionality

**Comment by comichael** [comment]
> Package version 3.4.0 supports this feature.

That is awesome. Thanks a lot for taking time to implement this feature.
