### ISSUE TITLE
Searching by strings concatenation

### ISSUE THREAD

**Issue by DariuszRKozlowski** [gustavnavar/Grid.Blazor#357]
Hi,
Using Blazor, I have a model which contains, among other things, two properties: FirstName and LastName. As a result, I receive a grid with two separated columns with first and last name. Searching feature for the records is enabled.
Lets assume that grid contains a record with first name: John and last name: Smith. When I search for "John", the record is found, when I search for "Smith" - the record is also found. But when I am trying to search for "John Smith", I receive: "There are no items to display".
I guess why it happens, but I would like to ask if there is any workaround to create a column with concatenation of first and last name (this column should be hidden) and enable to search by both values (get the result for: "John Smith"). I read the documentation and tried to add "Not connected column", but it does not work (I found the information that sorting and filtering will not work, but there was nothing about searching). Because the data comes from database, I would like to avoid adding a new column in database with redundant informations from other columns. 
Do You have any tips, ideas or implemented workaround for this kind of problem?

Best regards
Dariusz

**Comment by gustavnavar** [comment]
A way  to make it work is to define a database view as described [here](https://github.com/gustavnavar/Grid.Blazor/issues/18#issuecomment-541836268)
