### ISSUE TITLE
I have a grid for wich i use Syncfusion.Blazor.Grids  i want to change to Grid:blazor

### ISSUE THREAD

**Issue by pilotshamn** [gustavnavar/Grid.Blazor#358]
Hello this is more like a question
I have a grid for wich i use Syncfusion.Blazor.Grids
now I want o use an opensource solution.
Is it possible to do the same thing in Grid.Blazor as I do in Syncfusion,I include some code from my Syncfusion project se attached file
[questiongridblazor.pdf](https://github.com/gustavnavar/Grid.Blazor/files/9568026/questiongridblazor.pdf)
Th

**Comment by gustavnavar** [comment]
I don't understand what you describe in the attached file.

You can see all GridBlazor features in the [demo](https://gridblazor.azurewebsites.net/) and the [documentation](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/Documentation.md).

**Comment by pilotshamn** [comment]
Thanks for your answer i will try to be more specific I fave a function that fetch a number of Objects via HttpClient looks like this:  public static async Task<List<LeglistNoArray>> getResrobotForCache(bool to).
How can use this from Grid.Blazor to fill a grouped grid with strings and DateTimes . Or where in the documentation can i find this describe (newbie to this)
Thanks

**Comment by gustavnavar** [comment]
You can use the local data model. This is the documentation:
https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_local/Documentation.md

And here you can find many examples:
https://github.com/gustavnavar/Grid.Blazor/tree/master/GridBlazorStandalone
