### ISSUE TITLE
Make three state sorting optional

### ISSUE THREAD

**Issue by tony-asu** [gustavnavar/Grid.Blazor#365]
**Is your feature request related to a problem? Please describe.**
I need to implement two state sorting on an existing set of grids

**Describe the solution you'd like**
To pass an optional variable into the sort function to allow toggling between two and three state sorting.

**Describe alternatives you've considered**
Currently, I'm setting the column's InitialDirection in the OnSortChangedEvent, as this results in 2 state sorting, and setting the InitialDirection any other way caused issues with how the grid was initially sorted.  This seems less than ideal, but it works

```
    private async Task SortChanged(object sender, SortEventArgs e)
    {
        _grid.Columns.GetByName(e.ColumnName).InitialDirection = GridSortDirection.Ascending;
        await Task.CompletedTask;
    }
```

**Comment by gustavnavar** [comment]
Package version 3.5.0 includes this feature.


You can see the documentation [here](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/Sorting.md#sorting-header-behavior)
