### ISSUE TITLE
how to Add BlazorGrid .NET 6 Core MVC Existing Project

### ISSUE THREAD

**Issue by ManishVadukul** [gustavnavar/Grid.Blazor#369]
Hi 
I have used GridMVC in my .NET 6 core mvc project. It is working great. But now i want to use blazor grid into my .net 6 core mvc existing project.

Could you please send me configuration for .NET 6 Core MVC and please send me one BlazorGrid example too.

Thanks in advance.

Kind regards,
Manish

**Comment by gustavnavar** [comment]
There is a sample [here](https://github.com/gustavnavar/Grid.Blazor/tree/master/GridMvc.Demo)
