### ISSUE TITLE
Configurable visibility of section 'Go To Page'

### ISSUE THREAD

**Issue by peterM** [gustavnavar/Grid.Blazor#371]
Is here possibility to hide whole section 'Go to' ?

https://github.com/gustavnavar/Grid.Blazor/blob/ce6feec4849bad88e05b325da4c50ffe35ff9f09/GridBlazor/Pages/GridPagerComponent.razor#L64

**Comment by gustavnavar** [comment]
Package version 4.0.4 implements this feature

**Comment by peterM** [comment]
perfect... thanks

**Comment by peterM** [comment]
try to set in c# property 

```csharp
GridComponent.Grid.Pager.GoToVisibility = true;
```

**Comment by BahdanauYa** [comment]
> 

no, doesn't show up

**Comment by peterM** [comment]
only update what i see in this file is decoration with if statement.

```razor
        @if (GridComponent.Grid.Pager.GoToVisibility)
        {
            <div class="grid-goto-page form-group">
                <label class="control-label"><b>@Strings.Goto</b></label>
            <div>
                <input class="form-control grid-goto-page-input" @bind="_currentPage" @onkeyup="GoToKeyup" @onblur="GoToBlur" @onclick:stopPropagation />
            </div>
        </div>
        }
```

**Comment by gustavnavar** [comment]
Is there any exception issued by the  GridPagerComponent?

**Comment by BahdanauYa** [comment]
I set GridClient and used GridODataClient (not GridServer). I don't see any exceptions.

```
<GridComponent GridCellCssClass="this-cell-style" T="SomeDto" Grid="@_grid"></GridComponent>
......
private IGridClient<SomeDto> _client;
private CGrid<SomeDto> _grid;
....
_client = new GridODataClient<SomeDto>(httpClient, url, query, false, "someGrid", Columns, 20, CultureInfo.CurrentCulture)
                .ChangePageSize(true)
                .ClearFiltersButton(true)
                .Searchable()
                .Selectable(true)
                .SetStriped(true)
                .WithMultipleFilters()
                .WithGridItemsCount()
                .ODataCrud(false, false, false, false)
                .SetHeaderCrudButtons(true)
                .SetCrudButtonLabels("Add", "View", "View", "Delete")
                .HandleServerErrors(false, true);
            _grid = _client.Grid;
            _grid.Pager.GoToVisibility = true; // tried on new version
```

            
This code worked on 4.0.1
but now I see only Show in table footer
![1_2RdNRoDJmqfArWaViXal-g](https://github.com/gustavnavar/Grid.Blazor/assets/2437371/3fd2f36a-eaac-42b8-850c-72fc52918371)

**Comment by peterM** [comment]
do you use also `GridServer`.. if yes try to set it also there ? Other than that i do not know what can cause it .. unfortunately i am not able to try it personally.

**Comment by gustavnavar** [comment]
I can not reproduce your issue. I've just tested your grid configuration and it works fine:
![Captura (195)](https://github.com/gustavnavar/Grid.Blazor/assets/30131949/03579868-0384-4bae-841f-c6c409649333)

I don't understand what's going on.
