### ISSUE TITLE
Demo Blazor server-side (http://gridblazor.azurewebsites.net) returns 502

### ISSUE THREAD

**Issue by XristophD** [gustavnavar/Grid.Blazor#374]
**Describe the bug**
The Demo-Website is currently reporting back a 502. 

**To Reproduce**
1. Go to http://gridblazor.azurewebsites.net
2. See error

**Expected behavior**
Website should load with examples. 

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser Edge
 - Version: current

**Comment by gustavnavar** [comment]
Thanks for the info. It worlks again!
