### ISSUE TITLE
Export html content

### ISSUE THREAD

**Issue by DDolG** [gustavnavar/Grid.Blazor#376]
Add column with href. 
c.Add(o => o.MainBarCode).Titled("BarCode").Encoded(false).Sanitized(false)
            .RenderValueAs(o => $"<b><a class='modal_link' href='/Home/Edit/{o.MainBarCode}'>{o.MainBarCode}</a></b>");
When export to excel, the href is view in cell:
![image](https://user-images.githubusercontent.com/35914802/208471799-c94487a5-9a49-4251-9c71-b4ed2329a7c6.png)
But I'm waited only number.

**Comment by mattiaslundborg** [comment]
I'm having the same issue. Has this been solved?

**Comment by gustavnavar** [comment]
Package 3.5.1 implements a new RenderExcelAs method in column definition to customize excel columns format.

You can construct a custom display value of the column only for the exported file using the RenderExcelAs method:

```
    Columns.Add(o => o.Employees.LastName)
       .RenderExcelAs(o => o.Employees.FirstName + " " + o.Employees.LastName)
```

**Comment by DDolG** [comment]
Thank you very!
Admiro tu ingeniosa biblioteca.
