### ISSUE TITLE
TextFilterComponent IndexOutOfRangeException 

### ISSUE THREAD

**Issue by lxgxrto** [gustavnavar/Grid.Blazor#378]
**Describe the bug**
Hey All, 

I've been using the package for a while and I've came across with this exception (IndexOutOfRangeException) when trying to add more than one filter value to a column text.

I've debugged this locally and found out that for some reason the TextFilterComponent is loosing its `_filters` state when typing a value in the input text

**Screenshots**
I noticed that each time something is typed in the input it is triggering a re-render so that the component is loosing its current state because is calling the `OnParametersSet` method, adding a validation (in blue) solves the issue but I'm not sure this is the correct way to solve this
![image](https://user-images.githubusercontent.com/9524153/212365462-9031c451-9be7-468e-a4ab-2f690c88d375.png)

**Project info:**
 - SDK: Microsoft.NET.Sdk.Razor
 - TargetFramework: net6.0-windows
 - GridBlazor: 3.4.0
 - GridCore: 5.4.2

**Comment by gustavnavar** [comment]
Package 3.5.1 implements a new RenderExcelAs method in column definition to customize excel columns format.

You can construct a custom display value of the column only for the exported file using the RenderExcelAs method:

```
    Columns.Add(o => o.Employees.LastName)
       .RenderExcelAs(o => o.Employees.FirstName + " " + o.Employees.LastName)
```
