### ISSUE TITLE
Provide overloaded RenderComponentAs() with async callbacks

### ISSUE THREAD

**Issue by Cipery** [gustavnavar/Grid.Blazor#38]
Hi,

is there a reason why you don't allow 
`new List<Func<object, Task>>`
in RenderComponentAs(..) method in columns definition?

**Comment by Aelgorn** [comment]
Would be pretty useful to have. On my end I made this extension as a duct tape solution with Linq:

```csharp
public static class ActionExtensions
{
    public static List<Action<T>> ToActions<T, TResult>(this List<Func<T, TResult>> functions)
    {
        return functions.Select(f => (Action<T>)((obj) => { f(obj); })).ToList();
    }
}
```

**Comment by gustavnavar** [comment]
Hi,

I added ```new List<Action<object>>``` because I needed it for event handlers to navigate to other pages. 

I haven't found a situation where I need an async callback yet. What do you need it for? 

Anyway, I can check the option to use ```Func<object, Task>>```.

**Comment by Cipery** [comment]
My use case is:

Grid that has multiple columns, one of them is column with button(s). User clicks on button -> async background calculation is done, which mutates the data that are displayed in grid -> then, grid data is updated from db and refreshed on screen.

**Comment by DrGriff** [comment]
I got around this by using the Object parameter.

For my example, I wanted to have multiple buttons displayed in a single grid column.  I therefore created a `GridButtonParams` class with multiple properties (e.g. "Text", "CSS" _etc_) - one of them being an `Action<object>` for the button click event, though I guess it could be a `Func<object, Task>` if you want it async.

I then have another component `GridActions` which uses this:
`private List<GridButtonParams>? ButtonParameters => this.Object as List<GridButtonParams>;`

So my code to add multiple buttons would just be:

```
var gridButtons = new List<GridButtonParams>
{
    new GridButtonParams
    {
        ButtonText = "Edit",
        \\ other properties
        OnClickActionToExecute = this.ShowModalEdit,
    },
    new GridButtonParams
    {
        ButtonText = "Delete",
        \\ other properties
        OnClickActionToExecute = this.ShowModalDelete,
    },
};
c.Add().RenderComponentAs<GridActions<MyEntity>>(null, gridButtons);
```
If you use Generics, then the GridActions component can be used with any grid.

**Comment by Cipery** [comment]
Thanks for the ideas @DrGriff , I might use that!

**Comment by gustavnavar** [comment]
Nuget packages implementing this changes has been released. They are for .Net Core 3.1-Preview3

- GridBlazor: 1.3.0-Preview3-2
- GridMvcCore: 2.11.2
- GridShared: 2.11.2

You can find a sample here: https://gridblazor.azurewebsites.net/editrows

There is a new parameter of ```RenderComponentAs(..)``` of type ```IList<Func<object,Task>>```. **ButtonDbUpdate** uses it.
