### ISSUE TITLE
CheckBox Check all 

### ISSUE THREAD

**Issue by MarkEskander** [gustavnavar/Grid.Blazor#380]
Again thank you very much for this awesome Grid that made our lives much easier.

I just would like to control the check all header. to check all items in ONE page and not All items in all pages. 
so page 1 everything is checked, page 2, some items are checked, page 3 nothing ..etc

Thanks in advance.

**Comment by gustavnavar** [comment]
I've been reviewing how to implement this feature, but it requires major changes. I'm sorry but I can not implement it now.
