### ISSUE TITLE
GridHeaderComponent is null when I press apply button on a custom filter

### ISSUE THREAD

**Issue by AlexeyBoyko** [gustavnavar/Grid.Blazor#384]
Hello, I am facing quite the same problem as described in this closed issue: https://github.com/gustavnavar/Grid.Blazor/issues/87
I am using the latest version of GridBlazor (3.5.2) and strictly follow the documented instructions. 
Could you please check if this old issue had resumed at some point after version 1.3.17 (where it was obviously fixed)?

**Comment by AlexeyBoyko** [comment]
By the way, I've made a comparison of the code introduced by this commit (https://github.com/gustavnavar/Grid.Blazor/commit/65b0caa14a4586c685ce5d6606f2a47001234555) which meant to fix the #87 issue and it seems that the current state of respective code isn't much different, except for the the variable _sequence which was eliminated since and replaced with explicit numbers. So, if it is broken then it must be for some other reason...

**Comment by AlexeyBoyko** [comment]
P.S. Just in case, my app is server-side Blazor, while in the original issue it was probably client side WASM (judging by the link to documentation provided in the question).

**Comment by gustavnavar** [comment]
I've tested some examples with custom filters in a server-side Blazor project. But they work fine.

By the way there is published sample [here](https://gridblazor.azurewebsites.net/gridsample). The Customer column uses a custom filter with no errors.

Could you send a sample project including a grid that produces the error?

**Comment by AlexeyBoyko** [comment]
Thank you for the answer. I attach page's razor and cs files and the filter widget component. 
[dropDownFilter.zip](https://github.com/gustavnavar/Grid.Blazor/files/11079005/dropDownFilter.zip)

**Comment by gustavnavar** [comment]
You are using UserGroup as generic type parameter of the DropdownFilter class in the page Users.razor.cs:
```
_customFilters.Add(filterWidgetName, typeof(DropdownFilter<UserGroup>));
```

You must use UserViewModel as generic type parameter:
```
 _customFilters.Add(filterWidgetName, typeof(DropdownFilter<UserViewModel>));
```

**Comment by gustavnavar** [comment]
By the way, I recommend using a new database context and a new repository for the GridCoreServer constructor, mainly for CRUD support.

 Read from this [commentary](https://github.com/gustavnavar/Grid.Blazor/issues/25#issuecomment-553740363)

**Comment by AlexeyBoyko** [comment]
Thank you kindly, it works!
