### ISSUE TITLE
Totals rounding

### ISSUE THREAD

**Issue by eXicRa** [gustavnavar/Grid.Blazor#386]
Is it possible to round the totals?
So I could round the totals I calculated but not the predefined "Sum" and "Average". If I disable the predefined one, I got a null exception for e.g. SumValue.

So it would be nice to disable only the predefined totals from displaying, than I could easily calculate I want and round myself.

 .Calculate("Sum", x => Math.Round(c.Get("TestCol").SumValue.Number.Value,2))

![image](https://user-images.githubusercontent.com/30087059/234116955-e6021ef1-56bb-4a8d-9e37-c1ae060e62e9.png)

**Comment by gustavnavar** [comment]
You can use format for a column. For example:
```
c.Add(o => o.Freight)
    .Format("{0:#,##0.000}")
    .Sum(true).Average(true);
```
The format will apply to all column values, including the totals.

**Comment by eXicRa** [comment]
Thanks a lot, this helped me. Great work with this component.
