### ISSUE TITLE
Totals System.AggregateException when using search

### ISSUE THREAD

**Issue by eXicRa** [gustavnavar/Grid.Blazor#387]
**Describe the bug**
Getting System.AggregateException in Private.CoreLib.dll when ItemsDisplayed property "items" is null and columns with type "number" or "datetime" have totals with "Min" or "Max". 

With "Sum" it its working fine and the search is working correctly and displaying the value "0.00"

To reproduce: 
- DateTime Col or Number Col
- Search for something that is not in your data so you get a empty list back

**Comment by gustavnavar** [comment]
Could you describe the version of GridBlazor, GridMvcCore are you using? And what type of Blazor (e.g. WASM, server-side, etc.)?

**Comment by gustavnavar** [comment]
GridCore 6.0.3 should fix this issue
