### ISSUE TITLE
Join two columns in DB to one columns on Grid

### ISSUE THREAD

**Issue by quangdat88** [gustavnavar/Grid.Blazor#39]
Hi, 
How I can join two columns on database (exp: FirstName and LastName) to one columns on grid (exp: FullName). And When this Grid filter via FullName => filter via FirstName or LastName ??

**Comment by gustavnavar** [comment]
Hi,

With EF Core 3.0 the best option is to use keyless entities.

See this comment:
https://github.com/gustavnavar/Grid.Blazor/issues/18#issuecomment-541836268

**Comment by faina09** [comment]
I think you can also simply use a `[NotMapped]` field in the class defining the entity, like this:
`public string FullName => String.Concat(FirstName, " ", LastName);` that is obviously read only.

**Comment by gustavnavar** [comment]
I think that using a ```[NotMapped]``` field worked with Entity Framework 2.x.

But if you use Entity Framework 3.x the field will be shown on the grid but the filter will not work
