### ISSUE TITLE
Error when table filter is invalid

### ISSUE THREAD

**Issue by BahdanauYa** [gustavnavar/Grid.Blazor#394]
Actual for the date column when filter value is empty and you click Apply 
and for columns of numbers when you enter letters and click Apply.

.HandleServerErrors(false, false)  is not a solution, it's just hiding the problem

Expected Behavior: no error, invalid filter value cleared and not applied

![1_2RdNRoDJmqfArWaViXal-g](https://github.com/gustavnavar/Grid.Blazor/assets/2437371/53f2a81f-2b7d-482e-aaed-67c1e7fdadd3)
![1_2RdNRoDJmqfArWaViXal-g](https://github.com/gustavnavar/Grid.Blazor/assets/2437371/50c5c827-e21f-49a7-a11c-ce94599742f9)

**Comment by gustavnavar** [comment]
It only happens in the case of OData back-end.

When GridMvcCore is used it doesn't return any error:

**Comment by BahdanauYa** [comment]
Anyway, this is a possibility of a crash.
Maybe it's possible to change control behavior - don't send invalid data from ui control (letters for number field and null/empty for Date) to backend

**Comment by gustavnavar** [comment]
GridBlazor 4.0.6 does not send invalid data when using OData back-end
