### ISSUE TITLE
Bulgarian language inaccuracies

### ISSUE THREAD

**Issue by MarinaRadusheva** [gustavnavar/Grid.Blazor#396]
Some Bulgarian translations concerning the pagination need to be corrected.

'Items' as in items shown per page is now translated "Елементи" but should be "Елемента".
'Current' as in current page is not translated at all. Should be "текуща".

**Screenshots**
![bgTranslation](https://github.com/gustavnavar/Grid.Blazor/assets/74533584/e019f4f7-dc37-4430-b3ae-daa675a9b3c0)

**Comment by gustavnavar** [comment]
Package 4.1.0 includes these corrections
