### ISSUE TITLE
Request for adding localization languages.

### ISSUE THREAD

**Issue by lpyedge** [gustavnavar/Grid.Blazor#398]
Request for adding localization languages. 
I have compiled an Excel spreadsheet containing Simplified Chinese, Traditional Chinese, and Japanese.
I hope it can be added to this project.

[Blazor.Grid  Localization.xlsx](https://github.com/gustavnavar/Grid.Blazor/files/13360238/Blazor.Grid.Localization.xlsx)

**Comment by gustavnavar** [comment]
Hello,

one word is missing:
- Height

Could you send me its translation?

Thks.

**Comment by lpyedge** [comment]
I have create a pull request.
https://github.com/gustavnavar/Grid.Blazor/pull/399

**Comment by gustavnavar** [comment]
Package version 4.1.1 includes these translations
