### ISSUE TITLE
Database-side sorting/filtering

### ISSUE THREAD

**Issue by dradovic** [gustavnavar/Grid.Blazor#4]
How would one implement database-side filtering/sorting? In your example, would we have to parse the `query` values and then pass it them to the `repository`? Obviously `repository.GetAll` wouldn't scale if that's a table containing a lot of rows.

**Comment by gustavnavar** [comment]
You don't have to parse any query. It is all managed by the component and hidden to users. So the same sample should scale ok for large tables.

Let me explain how it works. The component has two parts:
- a front-end (GridClient and CGrid objects)
- and a back-end (ServerClient and SGrid objects) 

The front-end of the compoment sends a query object including all the required info to the back-end. This query object is different depending is you use "Blazor server-side" or "Blazor client-side". The query object is:
- a Dictionary object for Blazor server-side projects
- a query string for Blazor client-side projects
But in both case it includes the same information. It includes all paging, sorting and filtering information that you select on the grid interface.

The back-end side of the component uses the query object and applies it to the IQueryable object (e.g. repository.GetAll in the example) to get another IQueryable that includes all paging, sorting and filtering. 

It is the ORM who manages the final IQueryable object and sends a SQL query to the database. Then the database executes the query and gets a "page-size" size number of items. So the database is who really manages filtering, sorting and paging. These items are sent back to the back-end part of the component.

The back-end gets just a "page-size" number of items from the database as a list and combines it with info related to paging in a new object that is send back to the front-end side of componet who presents the grid.

As you can see the back-end of the component never receives all items from the database table if you use a good ORM. And it never sends all the table content to the front-end.

**Comment by dradovic** [comment]
Very good. This is the way I was hoping it would work. Thank you very much for sharing this component with the world.

**Comment by DrGriff** [comment]
I am seeing multiple calls for SELECT COUNT(*) 

I use a ViewModel to not expose my DB entites.  So in my service I have:

`IQuerable<MyEntity> things = context.Things.AsNoTracking().AsQueryable();`
`var thingsVM = things.Select(t => new ThingVM { P1 = t.P1, P2 = t.P2});`
`var server = new GridServer<ThingVM>(thingsVM, new QueryCollection(query), true, "thingsGrid", columns, 10)`

When I run the SQL Profiler, I see one call to sp_executesql where we have the filtered query, which is exactly what I hoped to see, but proceeding that I see multiple calls to "SELECT COUNT(*) FROM ....", where I would hope to see just a single call.

Anything I'm doing wrong?

**Comment by gustavnavar** [comment]
I´ve removed some count() calls that are not necessary anymore. 

There are new version of nuget packages that solve this issue. You will need both:
- GridBlazor v.1.0.2
- GridMvcCore 2.8.11
