### ISSUE TITLE
Errors when using Grouping

### ISSUE THREAD

**Issue by DrGriff** [gustavnavar/Grid.Blazor#41]
Navigate to the [Groupable](https://gridblazor.azurewebsites.net/groupable) demo.

On a Windows 10 64bit computer

- **Microsoft's Edge**: I can't drag the column headings to enable grouping
- **Firefox**: I can't drag the column headings to enable grouping

**Chrome**

1. Drag the column "Company"
2. Drag the column "Contact" (grouping with both)
3. Drag the column "Freight" (Grouping with all three)
4. Click the [X] to remove "Company" (the first added)
5. Click the [X] to remove "Contract" (the second)

This last step consistently fails for me with:

> Error: There was an unhandled exception on the current circuit, so this circuit will be terminated. For more details turn on detailed exceptions in 'CircuitOptions.DetailedErrors'.

**Comment by gustavnavar** [comment]
Nuget packages to solve this issue has been released. They are for .Net Core 3.1-Preview3.

- GridBlazor: 1.3.0-Preview3
- GridMvcCore: 2.11.0
- GridShared: 2.11.0

**Comment by DrGriff** [comment]
Has the [demo](https://gridblazor.azurewebsites.net/groupable) been updated?  I still don't seem to be able to dran'n'drop with FireFox or Edge.

**Comment by gustavnavar** [comment]
It is updated. 

But you are right, drag'n'drop only works on Chrome and Edge for Chromium.

**Comment by gustavnavar** [comment]
GridBlazor 1.3.0-preview3-1 package fixes the Firefox issue.
