### ISSUE TITLE
Incorrect HttpClient usage

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [gustavnavar/Grid.Blazor#42]
See this commit:
https://github.com/gustavnavar/Grid.Blazor/commit/6bf353c8e292fe3eeef33964bac0da9053004874#diff-f373f8e72b8bbfc8c8f7236251b4081fR700

Creating new instances of `HttpClient` is a big NO-NO, don't do this, use IHttpClientFactory instead:
https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/

**Comment by gustavnavar** [comment]
This can be an issue on ASP.Net MVC applications where the ```HttpClient``` is created by the server.

But in this case ```HttpClient``` is only used by Blazor WebAssembly apps where it is created by the browser. It could be an issue for Blazor Server apps, but this code is not used in this case.

I haven't found any article referring issues of creating ```HttpClient``` on Blazor WebAssembly. I would like to understand if this can be an issue on this type of apps. If it is the case I will implement a more complex solution like ```IHttpClientFactory```.

Anyone has info about this?

**Comment by gustavnavar** [comment]
One more article about Blazor Server app and ```IHttpClientFactory``` : 
https://wellsb.com/csharp/aspnet/blazor-httpclientfactory-and-web-api

But nothing new about Blazor WebAssembly

**Comment by gustavnavar** [comment]
GridBlazor 1.3.0 package includes an improvement of ```HttpClient``` utilization
