### ISSUE TITLE
Grid not rendering html inside cells

### ISSUE THREAD

**Issue by v2kiran** [gustavnavar/Grid.Blazor#5]
**Describe the bug**
The html code used with the 'rendervalueas' method shows up as a string instead of as html code.

**To Reproduce**
In the razor page define a grid data collection as:
```csharp
public static Action<IGridColumnCollection<Node>> Columns = c =>
    {
        c.Add(o => o.NodeName).RenderValueAs(o => $"<b><a href='api/node/getnodedetail/{o.NodeName}'>Detail</a></b>");
        c.Add(o => o.IP);
        c.Add(o => o.Status);
        c.Add(o => o.CName);
        c.Add(o => o.CCount);
    };
```

**Actual behavior**
```html
<td class=" grid-cell" style="" data-name="NodeName"><!--!-->
    <!--!-->&lt;b&gt;&lt;a href='api/node/getnodedetail/node1'&gt;Detail&lt;/a&gt;&lt;/b&gt;<!--!-->
</td>
```

**Expected behavior**
The cell value should be bold and should be a link. 

**Desktop (please complete the following information):**
 - OS: windows 10 - 1903 update
 - Browser chrome
 - Version 74.0.3729.169

**Additional context**
Thank you for making this project. Works great and nice documentation too :) !

**Comment by gustavnavar** [comment]
You have to add the Encoded(false) and Sanitized(false) methods if you use html content:

```c#
c.Add(o => o.NodeName).Encoded(false).Sanitized(false).RenderValueAs(o => $"<b><a href='api/node/getnodedetail/{o.NodeName}'>Detail</a></b>");
```

**Comment by v2kiran** [comment]
awesome! that worked :).

I have another question about setting conditional css class to a column. 
It seems currently we can only set a class for the whole column and not based on a cell value.

for the rows I am able to conditionally assign a css class like so:
```csharp
SetRowCssClasses(item => item.Status == "Failure" ? "label label--error" : string.Empty)
```

if this isn't as straightforward as my previous question :) let me know I can open this as a new issue.

**Comment by gustavnavar** [comment]
This is not as easy as the previous one. 

This kind of conditional assignment for columns is not implemented.

Could you open a new issue for this enhancement?

**Comment by v2kiran** [comment]
sure thing!
