### ISSUE TITLE
Groupable: Issue when collapsing a group

### ISSUE THREAD

**Issue by Aelgorn** [gustavnavar/Grid.Blazor#50]
Using .net core 3.1 and having added the js and min.css lines in _Host.cshtml, when I try grouping by column, it works, but collapsing the group only works for a flash until the table reopens it. My current configuration on both client and server is:
```
.Sortable()
.Groupable()
.WithPaging(100)
.Searchable()
.Filterable()
.WithMultipleFilters()
.SetStriped(true);
```

**Screenshots**
![groupable](https://user-images.githubusercontent.com/14635636/69989994-d5df5780-1512-11ea-999d-d038d544bab3.gif)

**Desktop:**
 - OS: Windows
 - Browser: Both Chrome and Firefox

**Comment by gustavnavar** [comment]
GridBlazor 1.3.1 package fix this issue
