### ISSUE TITLE
GridClient to support async dataservice calls

### ISSUE THREAD

**Issue by pvanroos** [gustavnavar/Grid.Blazor#51]
On a Blazor Server app (3.1), when instantiating the GridClient, it expects a data service with a synchronous call to retrieve data as first method parameter.  Can you allow async method call in the lamba?

**Comment by gustavnavar** [comment]
GridBlazor 1.3.2 supports both sync and async method calls for the data service.

You can use these parameters to call the ```GridClient``` constructor:
- async: ```Func<QueryDictionary<StringValues>, Task<ItemsDTO<T>>>```
-  sync : ```Func<QueryDictionary<StringValues>, ItemsDTO<T>>```
