### ISSUE TITLE
Passing Grid data type as generic object?

### ISSUE THREAD

**Issue by timbze** [gustavnavar/Grid.Blazor#53]
**Is your feature request related to a problem? Please describe.**
I am trying to create a generic button component, but I can not get it working with implementing ICustomGridComponent.
Below is my code, I would like to be able to use an interface or dynamic object instead of Person type, but doing that causes render error. Maybe there is a way to do it that I just don't realize yet...

```
@using GridBlazor
@using GridShared.Columns
@implements ICustomGridComponent<Person>
@inject NavigationManager navigationManager

<button class='btn btn-sm btn-primary' @onclick="MyClickHandler">Edit</button>

@code {
    [Parameter]
    public Person Item { get; set; }

    [Parameter]
    public CGrid<Person> Grid { get; set; }
    
    private void MyClickHandler(MouseEventArgs e)
    {
        navigationManager.NavigateTo($"/editorder/{ Item.Id.ToString() }");
    }
}
```

**Describe the solution you'd like**
I'd like to be able to create a razor component for Grid that I can use a generic type.

**Additional context**
https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Passing_grid_state_as_parameter.md

**Comment by gustavnavar** [comment]
Have you look at this https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Render_button_checkbox_etc_in_a_grid_cell.md?

Maybe optional ```Object``` parameter is what you need.
