### ISSUE TITLE
Norwegian translation

### ISSUE THREAD

**Issue by TorW** [gustavnavar/Grid.Blazor#55]
Hi. 

Here is Norwegian bokmål (nb-NO) translation for your component:

There are no items to display | Ingen elementer å vise
Filter this column | Filtrer denne kolonnen
Type | Type
Value | Verdi
Apply | Aktiver
Clear filter | Tøm filter
Equals | Er lik
Starts with | Starter med
Contains | Inneholder
Ends with | Slutter med
Greater than | Større enn
Less than | Mindre enn
Greater than or equals | Større eller lik
Less than or equals | Mindre eller lik
Yes | Ja
No | Nei
Items | Elementer
Search for ... | Søk etter…
Sum | Sum
Average | Gjennomsnitt
Max | Maks
Min | Min

**Comment by gustavnavar** [comment]
There are other values that require translation. Could you send the translation for them?

* Add
* And
* Back
* Clear all filters
* Create item
* Delete
* Delete item
* Edit
* Drop columns here for column extended sorting
* Drop columns here for column grouping
* Or
* Read item
* Save
* --- Select an item ---
* Show
* Update item
* View

**Comment by TorW** [comment]
Add | Legg til
And | Og
Back | Tilbake
Clear all filters | Tøm filtre
Create item | Opprett element
Delete | Slett
Delete item | Slett element
Edit | Endre
Drop columns here for column   extended sorting | Slipp kolonner her for utvidet sortering
Drop columns here for column   grouping | Slipp kolonner her for gruppering
Or | Eller
Read item | Les element
Save | Lagre
--- Select an item --- | -- Velg et element --
Show | Vis
Update item | Oppdater element
View | Vis

**Comment by gustavnavar** [comment]
GridBlazor v. 1.3.4 and GridMvcCore v. 2.11.4 support Norwegian bokmål.
