### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by Mrxx99** [gustavnavar/Grid.Blazor#57]
**Describe the bug**
The demo page seems to be broken, as no interaction (e.g. navigating to different page, filtering, sorting or even opening the menu on smaller screens) work. (Tested with different browsers and devices)

**To Reproduce**
go to the demo page: [gridblazor.azurewebsites.net](https://gridblazor.azurewebsites.net)
Click anywhere and see that nothing happens.
Also trying to resize the screen will give message the following message: Could not reconnect to the server. Reload the page to restore functionality.

**Comment by gustavnavar** [comment]
The ```CheckboxCell``` component of the demo was causing the issue. It's already fixed.
