### ISSUE TITLE
Conditional CSS for columns

### ISSUE THREAD

**Issue by v2kiran** [gustavnavar/Grid.Blazor#6]
**Is your feature request related to a problem? Please describe.**
It would be great to conditionally assign a css class to a column so that we can set different classes  based on the column or cell value.

**Describe the solution you'd like**
lets say i have a column named **"Status"** .
This column column can have a value of "success" or "failure"
In code we should be able to do something like this
```csharp
if ( c.status == "success")
{
    cssClass = "green"
}
Else
{
   cssClass = "red"
}
```

**Describe alternatives you've considered**
setting a css class for row works but i think it is too distracting to consider.

**Comment by gustavnavar** [comment]
I've just added conditional CSS for columns/cells to the source and uploaded to Nuget as v0.3.2

You should use:

```c#
     Columns.Add(x => x.Number).SetCellCssClassesContraint(x => x.Number < 0 ? "red" : "black");
```

**Comment by v2kiran** [comment]
Works perfectly! Thank you for adding this feature so quickly. 
Appreciate it

**Comment by gustavnavar** [comment]
Good to know !!
