### ISSUE TITLE
Unable to focus on any element inside grid cell

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [gustavnavar/Grid.Blazor#61]
**Describe the bug**
It is not possible anymore to focus on any element inside the grid cell, the focus is immediately reset. This is a clear regression, it worked without issues in previous versions. The issue is not browser dependent.

**To Reproduce**
1. Have a `<input type="text">` inside a grid cell.
2. Click on that input.
3. Notice that the focus is immediately reset, making it almost impossible to type anything in that input. Also, the viewport is scrolled to focus the entire grid.

**Expected behavior**
Focus should not reset without a good reason.

**Screenshots**
I repeatedly click on the text input, focus gets immediately reset.
![2019-12-30_15-23-18](https://user-images.githubusercontent.com/928550/71586065-226d8100-2b19-11ea-9c73-04c9f9db48d5.gif)

**Additional context**
The focus is reset because of the call to `GridComponent<T>.SetFocus()` that originates from `GridComponent<T>.GridComponentClick()`. Commenting `GridComponent<T>.SetFocus()` seems to fix the issue completely.

**Comment by gustavnavar** [comment]
This behavior is a trade-off to get keyboard navigation.

You have to stop ```omclick``` propagation now:
```c#
    <input type="text" @onclick:stopPropagation>
```

**Comment by ZimM-LostPolygon** [comment]
I don't see the connection. How is keyboard navigation related to resetting the focus on mouse lick? I was able to use Tab for keyboard navigation just fine before. It's counterproductive to go and add `@onclick:stopPropagation` everywhere, especially since some components are used outside of the grid.
Is there a way to disable the "keyboard navigation" completely, so components can focus normally?

**Comment by gustavnavar** [comment]
GridBlazor package 1.3.8 will allow using ```<input type="text">``` inside a grid cell without using event stop propagation.
