### ISSUE TITLE
Grid component resets focus when calling GridComponent.UpdateGrid()

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [gustavnavar/Grid.Blazor#62]
**Describe the bug**
Continuation of bug https://github.com/gustavnavar/Grid.Blazor/issues/61. I have an external "quick filter" implementation, which consists of `<input type=text>` _outside_ of the grid component (not inside the grid cell). As the text is typed, I call `GridComponent.UpdateGrid()` to filter out the values.

**To Reproduce**
1. Call `GridComponent.UpdateGrid()`.
2. Grid is immediately focused even if the focus was on some other component.

**Expected behavior**
Focus should not reset when calling `GridComponent.UpdateGrid()`.

**Additional context**
Line in question is https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazor/Pages/GridComponent.razor.cs#L656
Not sure what sense does it makes to call `GridComponentClick` when updating the grid, clearly updating the grid doesn't necessarily mean user clicking the mouse. Commenting out this line seems to fix the issue for me.

**Comment by gustavnavar** [comment]
This issue is consequence of  https://github.com/gustavnavar/Grid.Blazor/issues/63.

I will close it.

**Comment by ZimM-LostPolygon** [comment]
@gustavnavar Hm, how is it a consequence of #63? This isn't happening on page load, it can happen anytime when UpdateGrid is called.

**Comment by gustavnavar** [comment]
A solution implemented to fix that issue will also fix this one.
