### ISSUE TITLE
Focus is automatically set to the grid on page load

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [gustavnavar/Grid.Blazor#63]
**Describe the bug**
Continuation of bug #61. Immediately after the page is loaded, the grid component focuses itself, resulting in a page scroll and losing whatever focus was set by the user.

**To Reproduce**
1. Add `GridComponent` to the page.
2. Immediately after the page is loaded, the grid gets focused.

**Expected behavior**
The grid should not focus automatically when the page is loaded. There is no reason to do so, and it prevents the user from focusing something else on load.

**Additional context**
The call originates from https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazor/Pages/GridComponent.razor.cs#L165
Commenting the line seems to fix the issue for me.
Not sure what this behaviour is for, but it contradicts basic user experience expectations. The page should not scroll without any action from the user. Plus, it will fail if there are more than two grids on a page - which one will get focused?

**Comment by timbze** [comment]
I agree with this. I have a grid further down on the page, and as it loads it jumps down to the grid.

**Comment by gustavnavar** [comment]
The reason to get the focus on the grid is to be able to use the keyboard for navigation. If the grid compoment has not the focus, keyboard navigation does not work. 

The are people who requested this behavior that it seems to be in contradiction with your user experience expectations: https://github.com/gustavnavar/Grid.Blazor/issues/32

My personal point of view is that both user expiriences can be desirabled. So the only option that I see is to add a method to the component to enable or disable the automatic focus on the grid after component load:
- if automatic focus is enabled, keyboard navigation will work after grid is enabled
- if automatic focus is disabled, the grid will require the user will focus on the grid, either clicking on it or using tab key, to be able to use keyboard navigation.

I will wait to see other user opinions to implement this feature.

**Comment by timbze** [comment]
@gustavnavar I agree. For those who mainly use the grid on the page, and use keyboard navigation for sure, they would want it to be focused automatically. I think it would be good to add a method so those who do not want it this way can disable automatic focus.

**Comment by ZimM-LostPolygon** [comment]
@gustavnavar People actually using keyboard navigation inside a web page are extremely rare. I believe the automatic focus needs to be disabled by default. Especially since it's basically undefined behavior when there are multiple grids on a single page. 

Also, I think it makes sense to add an option to disable keyboard navigation completely.

**Comment by gustavnavar** [comment]
GridBlazor 1.3.9 package fix this issue.

The initial plan was to enable/disable autofocus, but there was too many cases to cover and I didn't get an stable solution. So I've had to implement a feature to enable/disable keyboard navigation.

You can enable keyboard navigation between pages using the ```SetKeyboard``` method of the ```GridClient``` object:

```c#
    var client = new GridClient<Order>(HttpClient, url, query, false, "ordersGrid", Columns).SetKeyboard(true);
```

The parameter default value is ```false```.

**Comment by timbze** [comment]
@gustavnavar Thank you so much. Appreciate your hard work on this project.
