### ISSUE TITLE
Extended sort using ctrl-click

### ISSUE THREAD

**Issue by rcpacheco** [gustavnavar/Grid.Blazor#68]
Let me say they I really like the current extended sort by draging the column names, gives a lot of visibility. Nevertheless, from what I see, if grouping is enabled no extended sorting can be used. Is it really so? If so, may those two functionalities be independent and non excluding? If not, an option could be to use ctrl-click to add additional sort columns.  What do you think about this topic. Thanks for the great work with GridBlazor!!

**Comment by gustavnavar** [comment]
Grouping always includes extended sorting. Grouping performs an extended sorting of the grid rows as defined by the draged columns as a first step. After that, it groups the visible rows of the grid.

So when grouping is enabled, extended sorting is used implicetly. I can not see any way to make grouping indendent of extender sorting.

**Comment by rcpacheco** [comment]
Thanks a lot. I was not aware that it both where active at the same time. I will give it a try to understand how it works.
