### ISSUE TITLE
Allow data transformation through the processing of the request

### ISSUE THREAD

**Issue by ChrisProlls** [gustavnavar/Grid.Blazor#69]
We are searching a way to do data transformation through your grid. I'll will explain myself.
We have a table called `UseCase`, but we want to display a `UseCaseViewModel` because of some functionnal rework of our `UseCase` model which needs others SQL requests.
All grid objects are created under the `UseCaseViewModel` type because that's the good object we want to display, but all sorting, paging and filtering functionnality should be applied to the `UseCase` model because that's the DB model.
We tried someting like that
```csharp
this.myRepo.DbSet<UseCase>().Select(useCase => new UseCaseViewModel(useCase));
```

And we pass this to the `GridServer` during initilisation, but LINQ complains during the call to `ItemsToDisplay` about `OrderByDescending(u => new UseCaseViewModel(u).MyProp)` which LINQ cannot translate properly to SQL. And that's right because the `Select` statement should be applied at the end, just before `ToList` and not at the very beginning.
We've seen that you developed an extensible system with objects of type `IGridItemsProcessor`, is it possible to use this system ? Have you another idea about our issue ?

**Comment by gustavnavar** [comment]
EF Core 3.0 doesn't allow to local execution. All queries must be executed on the database server. Previous versions of EF executed on the client the parts of  LINQ that it couldn't translate to SQL.

If you want to test that it works with local execution you can change it to:
```
this.myRepo.DbSet<UseCase>().ToList().Select(useCase => new UseCaseViewModel(useCase));
```
but of course there will be an impact on performance if this table is large enough. How long will be this table?

```IGridItemsProcessor``` interface is used internally for filtering, sorting, etc,  and there is no way to add a GridItemsProcessor.

Can you show me detail of both models to see if there is any other option?

**Comment by ChrisProlls** [comment]
We've changed the model and now we directly interact with the database model and not a second model specific for the view.
It's not really what I expected from a code architectural point of view, but it guarantee the performance of our application :)
I'm closing this.

Thanks for your reply :)
