### ISSUE TITLE
Doc for json format

### ISSUE THREAD

**Issue by janellesnowy** [gustavnavar/Grid.Blazor#7]
Hi, I'm trying to run blazor client without the server. What is the json format expected from the url? I can't decipher from the docs.

**Comment by gustavnavar** [comment]
The back-end side is required. It's that part of the compoment that applies filtering, sorting, searching and paging to the IQueryable object and sends it to the data base throght Entity Framework. 

You can find more details in #4

**Comment by janellesnowy** [comment]
I see. I cannot just use the client front end with my own endpoint?

**Comment by gustavnavar** [comment]
Yes, you can use the front end with another endpoint. You will have to develop the functionality implemented in the GridMvcCore Packagem.

As I told you the interface between GridBlazor and  GridMvcCore  was not intended as an open interface, so it was not documented. But I will add the query string and ItemsDTO details to the documentation

**Comment by gustavnavar** [comment]
I have added the API documentation in ![](https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/API.md)
