### ISSUE TITLE
Grid does not reload after to close a modal window.

### ISSUE THREAD

**Issue by pcecamacho** [gustavnavar/Grid.Blazor#70]
We have a grid with buttons on it. When a user clicks in a button, a modal window appears which updates some data. When the modal window is closed, the back-end side saves the information in the database. We then run exactly the same code that we used to load the grid (version 1.3.0-preview3) but the grid is no refreshing now using the version 1.3.9.

We updated to this new version to use SetKeyboard feature.
The code that we are using is:

![Edit1](https://user-images.githubusercontent.com/59876094/72350142-3d60f900-36b4-11ea-8bfc-fba14117d119.png)

Where GetGridInformationAsync is loading the Grid when the page is loaded (in OnInitializedAsync) and when the modal window is closed after to update the information.

![Edit2](https://user-images.githubusercontent.com/59876094/72350341-a8aacb00-36b4-11ea-9434-1eeff9d537e5.png)

Have you an idea about our issue ?

FYI: when the modal window is closed and we see that the grid is no displayed updated, we click inside the grid, so, this one is displayed correctly, no process is executed in back-end.

**Comment by gustavnavar** [comment]
My recommendation is to call `the ```UpgradeGrid``` method of the component object from ```EditConfirmationModalClosedAsync```.  It will rerender the grid instead of recreate it. Maybe there is a confusion because ```CGrid```, ```GridClient``` and ```GridComponent``` objects have  a method with the same ```UpdateGrid```, and it can seem that the 3 methods do the same. 

It was true in old versions, but it is not anymore:
- ``UpgradeGrid``` method of  the ```GridClient``` object only calls the ```UpgradeGrid``` method of the  ```CGrid``` object. 
- ```UpgradeGrid``` method of  the ```GridComponent``` object calls the ```UpgradeGrid```  method of the ```CGrid``` object and do more stuff to make new content visible just rerendering the component.

So I think it's not necessary to call ```GetGridInformationAsync ``` when you close the modal.

You can use a reference to the GridComponent when the page is loaded:
```c#
    <GridComponent @ref="MyComponent" T="Channel" Grid="@_grid"></GridComponent>
```
And then the code of ```EditConfirmationModalClosedAsync``` should contain:
```c#
    await MyComponent.UpdateGrid();
```

**Comment by pcecamacho** [comment]
Your recommendation is working fine. Thank you so much.
