### ISSUE TITLE
Working with Grid filters. [Blazor]

### ISSUE THREAD

**Issue by dazinator** [gustavnavar/Grid.Blazor#71]
**Is your feature request related to a problem? Please describe.**

I'm trying to work out how I work with filters dynamically.
The issue I have is that:

1. We don't want to display the filter icon in the column header, because we want the user to be able to add some filters for hidden columns, or basically, server side only filters. If the column is not displayed, then there is no opportunity for a user to click the filter icon in the column header, so this flow doesn't make sense for us.
2. Based on point above, we decided we'd use CSS to hide the filter icon in column headers. We'd then create a custom component to sit outside (and above) the grid, that a user can interact with to "add" filters to the grid, and to see which filters are currently active / applied.

So we are now trying to develop this component, and this leads me to some questions:

1. We want to have an "Add Filter" button and corresponding UI in our own component, so we'd need to allow the user to pick the Column, and the Type of filters applicable for that column type, how best to get that information?
2. Once a user selects the column, and the type of filter to apply, they will click our "Apply" button - we will need to implement some code to then apply that filter to the grid. Should we use `grid.AddFilter()` or `AddFilterParameter()` for that? Also, for server side only filters (i.e we don't want to display a column, we just want to apply a filter on the server side) would we still need to add a fake column with the same name and hide it from the UI to get this to work? Or can we apply a filter to the grid for a column that doesn't exist?
3. How best to get access to the list of current / actively applied filters? (So that we can render something that lets the user see which filters are active.)

I've looked at some of the tests around filters and after a first pass I am a bit confused because there is a lot too it - I am wondering if you could offer some helping guidance!

Many Thanks

**Comment by gustavnavar** [comment]
You can use a reference  to the ```GridComponent```:
```c#
    <GridComponent @ref="MyComponent" T="Order" Grid="@_grid"></GridComponent>
```

and use the following methods to add remove filters:
- ```MyComponent.AddFilter(IGridColumn column, FilterCollection filters)```
- ```MyComponent.RemoveFilter(IGridColumn column)```

You can also get the current filters, sorting, paging, etc. with:
```c#
   ((CGrid<Order>)MyComponent.Grid).Query
```
You can find information about what contains the ```Query``` object here: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/API.md
The part that will be interisting for you is the description of the ```grid-filter``` parameter.

**Comment by dazinator** [comment]
Is it necessary to call UpdateGrid() after AddFilter() ? e.g:

```csharp
await _grid.AddFilter(Column, new FilterCollection(filterValue.FilterType.ToString("d"), filterValue.FilterValue));

await _grid.UpdateGrid();
```

**Comment by gustavnavar** [comment]
The code that you show is calling methods of the ```CGrid``` object. It is not the recommended way to manage filters, paging, etc.

The recommended way to work is at component level. The AddFilter() / RemoveFilter() methods of this object call the AddFilter() / RemoveFilter() methods of the ```CGrid``` object and other stuff.

If you call methods of ``CGrid``` object you will have to call the ```UpgradeGrid``` method, and maybe others.

But it you call the methods of the ```GridComponent``` object, you will only have to call AddFilter and RemoveFilter methods.

**Comment by dazinator** [comment]
Understood thank you. I was actually calling those methods at the component level already as AddFilter and UpdateGrid also exist at Component level! But thanks for clarifying!

I've managed to get a simple example together that adds a filter, and also renders all the active filters. To render all the active filters I am doing this:

```
    @foreach (var filter in _grid.Grid.Settings.FilterSettings.FilteredColumns)
    {
        <p>@filter.ColumnName - @filter.FilterType - @filter.FilterValue</p>
    }


```

This seems to work. One thing to note is that as my component sits outside the grid, if I do use the grids own mechanism to add a filter via a column header, the filter is added, but my component is not notified to re-render. This won't be a problem for me as we will be disabling the grids inherent ability to drive creating / adding new filters, but just an FYI in case you wanted to add some EventCallback mechanism, or Events for FilterAdded etc etc so external components can respond to changes.

Last note: You may have already documented this, in which case please ignore as I am yet to read all the documentation, but I noticed as I add filters, the representation of the query string changes. I can see what the query string looks like  by adding this markup:


```

<p>Filter Query:  @String.Join(",", _grid.Grid.Settings.FilterSettings.Query.ToArray().Select(a => a.Key + ":" + (string)a.Value ?? ""))</p>
    <p>Grid Query: @String.Join(",", _grid.Grid.Settings.ToQuery().ToArray().Select(a => a.Key + ":" + (string)a.Value ?? ""))</p>
```

When the page loads, I noted I can restore all the filter state from the query string in the current URI, but I had to add code like this:

```
        var uri = NavigationManager.ToAbsoluteUri(MyNavigationManager.Uri);
        var uriQuery = QueryHelpers.ParseQuery(uri.Query);
        var query = new QueryDictionary<StringValues>();
        if (uriQuery.TryGetValue("grid-filter", out var param))
        {
            query.Add("grid-filter", param);
        }
    
        string url = MyNavigationManager.BaseUri + "api/SampleData/";
        var client = new GridClient<WeatherInfo>
            (HttpClient, url, query, false, "weatherGrid", ColumnCollections.WeatherColumns)
            .ChangePageSize(true)
            .Sortable()
            .Filterable()
            .WithMultipleFilters();
        _gridComponent = client.Grid;
        await client.UpdateGrid();
```

Is that the right way to re-init the grid state on page load from the query string, or is there some simpler helper method I should be using?

**Comment by gustavnavar** [comment]
You are right. It is a better option  to work with the ```_grid.Grid.Settings.FilterSettings.FilteredColumns``` object than to work with ```Query``` object. ```FilteredColumns``` is build from ```Query``` and you will avoid to parse the query string. 

I will look how to add event callbacks. It can be an interesting improvement.

```GridBlazor``` is not working with query strings from the url. But ```GridMvcCore``` (the component for ASP.NET Core MVC applications) works with query strings. The reason of  using an object named ```Query``` in ```GridBlazor``` is that it is a migration of ```GridMvcCore```  for Blazor. So many object names are common in both projects. But as I told you ```GridBlazor``` state is not in the query string.

In fact both project have a method to serialize the grid state:
- GridBlazor: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Passing_grid_state_as_parameter.md
- GridMvcCore: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/dotnetcore/Passing_grid_state_as_parameter.md

**Comment by timbze** [comment]
Great discussion here, helped me out today (mostly), probably be good to add some of this to docs.

My only issue yet is, I want to filter a hidden column, but seems nothing happens when I add a filter to a column that is hidden... Any pointers to help me?

**Comment by gustavnavar** [comment]
Hidden columns are build to get column values on the grid and be able to access them from javascript code in ASP.NET Core MVC projects or c# in Blazor ones.

But they have not any manipulation feature processing enabled (e.g. sorting, grouping, filtering, etc.). This is because there is no way to configure them from the grid. Of course if you develop an external component to configure filtering or grouping you can set them up on hidden columns, but intenal processing is not currently working.

**Comment by gustavnavar** [comment]
I will verify the feasibility to add  manipulation feature processing on hidden columns.

**Comment by timbze** [comment]
Ok, I can do it on the data level as well. That's what I'll do for now. Not sure how important it is to be able to do this.

**Comment by gustavnavar** [comment]
GridBlazor v. 1.3.11 support  manipulation feature processing (e.g. sorting, grouping, filtering, etc.) on hidden columns. Of course it onlycan be manipulated from external components.

At the same time it also contains events for the ```GridComponent``` object: 
https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Events.md

The sample project has implemented event handling on the "All features" page:
https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorServerSide/Pages/GridSample.razor
This sample writes on the console the changes done using the grid filters, sorting, etc.

**Comment by dazinator** [comment]
@gustavnavar - I noticed you allow multiple filters to apply to the same column.
Do you support conjunctions? i.e whether the filters in the collection should use AND or OR conjunction?

**Comment by gustavnavar** [comment]
Yes, conjunctions are supported. If you have more than one filter on a column, you must specify the condition adding a new ```ColumnFilterValue``` item to the ```_grid.Grid.Settings.FilterSettings.FilteredColumns``` list. 

The ```ColumnFilterValue``` for the condition must be as follows:
```c#
    var condition = new ColumnFilterValue(columnName, GridFilterType.Condition, gridFilterCondition);
```
where gridFilterCondition can be one of the following values:
- GridFilterCondition.And
- GridFilterCondition.Or

**Comment by ChhaganSinha** [comment]
> You can use a reference to the `GridComponent`:
> 
> ```cs
>     <GridComponent @ref="MyComponent" T="Order" Grid="@_grid"></GridComponent>
> ```
> 
> and use the following methods to add and remove filters:
> 
> * `MyComponent.AddFilter(IGridColumn column, FilterCollection filters)`
> * `MyComponent.RemoveFilter(IGridColumn column)`
> 
> You can also get the current filters, sorting, paging, etc. with:
> 
> ```cs
>    ((CGrid<Order>)MyComponent.Grid).Query
> ```
> 
> You can find information about what contains the `Query` object here: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/API.md The part that will be interisting for you is the description of the `grid-filter` parameter.

Hi...will it work for odata backend? I have to filter data Yearwise based on "CreatedOn" column here is my sample code

`<div class="form-group row">
    <label for="colFormLabel" class="col-md-2 col-form-label" style="font-weight:700">Select Year</label>
    <div class="col-md-10">
        <select onchange="@ChangeYear" class="form-select" aria-label="Default select example">
            @if (Years != null)
            {
                foreach (var year in Years.OrderByDescending(y => y))
                {
                    if (year == Year)
                    {
                        <option value="@year" selected>@year</option>
                    }
                    else
                    {
                        <option value="@year">@year</option>
                    }
                }
            }
        </select>

    </div>
</div>
<div class="pcoded-content">
    <div class="row">   
        <div class="col-sm-12 col-md-12 col-xl-12">
            <DrillDown_Summary Total="total" Hits="hits" Reported="reported" PronePercent="pronePercent">
            </DrillDown_Summary>
        </div>
    </div>
</div>

<div style="overflow: hidden;width: 100vw;max-width: 95vw;margin-left: calc(50% - 48vw);">
    <GridComponent @ref="_gridComponent" T="CampaignLog" Grid="@_grid"></GridComponent>
</div>

@code {

    [Parameter]
    public int Id { get; set; }
    private List<CampaignLog> CampaignLogs = new List<CampaignLog>();
    private int total;
    private int hits;
    private int reported;
    private decimal pronePercent;

    private GridComponent<CampaignLog> _gridComponent;
    private CGrid<CampaignLog> _grid;
    private Task _task;
    private GridODataClient<CampaignLog> _client;
    private bool _eventHooked = false;
    private List<int> Years;
    public int Year { get; set; } = DateTime.Now.Year;

    Action<IGridColumnCollection<CampaignLog>> columns = c =>
    {
        c.Add(o => o.Id).Titled("LogID").SetWidth("30px").Css("table-bordered");
        c.Add(o => o.Camp.Id).Titled("CampID").SetWidth("30px").Css("table-bordered");
        c.Add(o => o.Camp.Name).Css("table-bordered").Titled("Campaign Name"); ;
        c.Add(o => o.CampignType).Css("table-bordered").SetWidth("60px");
        c.Add(o => o.Camp.Category).Css("table-bordered").SetWidth("60px").Titled("Category");
        c.Add(o => o.IsHit).Css("table-bordered");
        c.Add(o => o.IsReported).Css("table-bordered");
        c.Add(o => o.CreatedOn).Css("table-bordered");

    };

    protected override void OnAfterRender(bool firstRender)
    {
        _gridComponent.AfterRefreshGrid += AfterRefreshGrid;
    }

    private async Task AfterRefreshGrid()
    {  

        var grid = _gridComponent.Grid as CGrid<CampaignLog>;

        if (grid != null)
        {
            Calculate(grid);

            StateHasChanged();
        }

        await Task.CompletedTask;
    }


    protected override async Task OnParametersSetAsync()
    {
        string url = $"Odata/Campaignlog?t={authState.TenantIdentifier}";
        var query = new QueryDictionary<StringValues>();
        try
        {
            var client = new GridODataClient<CampaignLog>(HttpClient, url, query, false, "ordersGrid", columns, 50)
            .ChangePageSize(true)
            .Filterable()
            .ClearFiltersButton(true)
            .SetStriped(true)
            .WithMultipleFilters()
            .WithGridItemsCount()
            .Searchable(true, false, false);

            _grid = client.Grid;
            _task = client.UpdateGrid();
        }
        catch (Exception ex)
        {
            logger.LogCritical(ex, ex.Message);
        }

        await _task.ContinueWith(async (st) =>
        {
            Calculate(_grid);
            await Task.CompletedTask;
        });
        Years = await client.GetCampaignLogYears();
    }
void ChangeYear(ChangeEventArgs e)
    {
        Year = Convert.ToInt32(e.Value);
        //_gridComponent.AddFilter(CreatedOn, Year);
        //_gridComponent.RemoveFilter(Column);
}
`

**Comment by ChhaganSinha** [comment]
> You can use a reference to the `GridComponent`:
> 
> ```cs
>     <GridComponent @ref="MyComponent" T="Order" Grid="@_grid"></GridComponent>
> ```
> 
> and use the following methods to add and remove filters:
> 
> * `MyComponent.AddFilter(IGridColumn column, FilterCollection filters)`
> * `MyComponent.RemoveFilter(IGridColumn column)`
> 
> You can also get the current filters, sorting, paging, etc. with:
> 
> ```cs
>    ((CGrid<Order>)MyComponent.Grid).Query
> ```
> 
> You can find information about what contains the `Query` object here: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/API.md The part that will be interisting for you is the description of the `grid-filter` parameter.

Hi..  how can i add "OR" condition using AddFilter method here is my sample code

```
 var filter = new FilterCollection();
        filter.Add("GreaterThanOrEquals", start);
        filter.Add("LessThan", end);
        IGridColumn column = _gridComponent.Grid.Columns.FirstOrDefault(c => c.FieldName == "CreatedOn");

        await _gridComponent.AddFilter(column, filter);
        await _gridComponent.UpdateGrid();
```

here i have to filter data for this 2 condition with with greater "GreaterThanOrEquals" or "LessThan".
please reply. 
thank you..
