### ISSUE TITLE
GridServer, Guid column, ItemsToDisplay threw an exception of type 'System.ArgumentException'

### ISSUE THREAD

**Issue by dazinator** [gustavnavar/Grid.Blazor#73]
**Describe the bug**
On the server side, i'm using GridServer<T> to return the grid model to the UI.

```
 var server = new GridServer<TenantInfoDto>(allTenants, Request.Query,
                true, "tenantsGrid", GridBlazorComponent.Columns, 3)
                .Sortable();

return Ok(server.ItemsToDisplay); // this throws when a filter is applied to a guid property.
```

Where Column defintion is:

```
 public static Action<IGridColumnCollection<TenantInfoDto>> Columns = c =>
    {
        c.Add(o => o.Id).SetFilterWidgetType("TextFilter");
        c.Add(o => o.Name).SetFilterWidgetType("TextFilter");
        c.Add(o => o.Hostname).SetFilterWidgetType("TextFilter");
        c.Add(o => o.Guid).SetFilterWidgetType("TextFilter");
        c.Add(o => o.IsConfigured, true).SetFilterWidgetType("TextFilter");
    };

```

On the client side, when I apply a filter for the GUID column, it calls the server side API, and causes an exception with message: "Method 'System.String ToUpper()' declared on type 'System.String' cannot be called with instance of type 'System.Guid'"

**To Reproduce**
As above, apply a filter to a GUID column, and use GridServer<T> to return items for display.

**Expected behavior**
Filter on GUID column shouldn't cause exception.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by gustavnavar** [comment]
Guid  are not currently supported for filtering: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Filtering.md

You should define the columns as follows:
```c#
    public static Action<IGridColumnCollection<TenantInfoDto>> Columns = c =>
    {
        c.Add(o => o.Id).SetFilterWidgetType("TextFilter");
        c.Add(o => o.Name).SetFilterWidgetType("TextFilter");
        c.Add(o => o.Hostname).SetFilterWidgetType("TextFilter");
        c.Add().RenderValueAs(o => o.Guid.ToString());
        c.Add(o => o.IsConfigured, true).SetFilterWidgetType("TextFilter");
    };
```

**Comment by gustavnavar** [comment]
I will check the feasibility to add Guid for filtering.

**Comment by gustavnavar** [comment]
Theses new versions of packages support filtering on Guid columns:
- GridBlazor 1.3.13  
- GridMvcCore 2.11.11 

You have to update both packages.

And you have to defines columns as follows:
```c#
public static Action<IGridColumnCollection<TenantInfoDto>> Columns = c =>
    {
        c.Add(o => o.Id).SetFilterWidgetType("TextFilter");
        c.Add(o => o.Name).SetFilterWidgetType("TextFilter");
        c.Add(o => o.Hostname).SetFilterWidgetType("TextFilter");
        c.Add(o => o.Guid).SetFilterWidgetType("TextFilter");
        c.Add(o => o.IsConfigured, true).SetFilterWidgetType("TextFilter");
    };
```
