### ISSUE TITLE
Error in Date Time filter

### ISSUE THREAD

**Issue by pcecamacho** [gustavnavar/Grid.Blazor#75]
**Describe the bug**
Conversion failed when converting date and/or time from character string.

**To Reproduce**
1. Go to the grid with one date time column at least
2. Define a filter in the date time column, include a date
![Filter](https://user-images.githubusercontent.com/59876094/73023277-94c43f00-3e01-11ea-8d50-bfb3d685a062.png)

3. Click in Apply button

Conversion failed when converting date and/or time from character string.

![image](https://user-images.githubusercontent.com/59876094/73023755-8f1b2900-3e02-11ea-82e1-aad2f77d11e3.png)

**Expected behavior**
The Grid should be displayed filtered by the date time column.

**Screenshots**
![image](https://user-images.githubusercontent.com/59876094/73023938-e9b48500-3e02-11ea-8449-070c8109da64.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser chrome

**Additional context**
Version used in my sample:
 * Blazored.Modal Version="3.0.0" 
 * GridBlazor Version="1.3.10" 
 * GridMvcCore Version="2.11.8" 
 * GridShared Version="2.11.8" 

In the database the following query is executed when the error is thrown:
_SELECT COUNT(*)
FROM [Orders] AS [o]
WHERE [o].[OrderDate] IS NOT NULL AND ([o].[OrderDate] = '1996-07-16T00:00:00.000**0000**')_

If you uses only the following value the query works:
1996-07-16T00:00:00.000

Thank you in advance for your help.

**Comment by gustavnavar** [comment]
I just executed the GridBlazorServerSide sample to reproduce this issue. But I get no exception.
 
The SQL Server Profiler shows this message:
```sql
exec sp_executesql N'SELECT [t].[OrderID], [t].[CustomerID], [t].[EmployeeID], [t].[Freight], [t].[OrderDate], [t].[RequiredDate], [t].[ShipAddress], [t].[ShipCity], [t].[ShipCountry], [t].[ShipName], [t].[ShipPostalCode], [t].[ShipRegion], [t].[ShipVia], [t].[ShippedDate], [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[IsVip], [c].[Phone], [c].[PostalCode], [c].[Region], [e].[EmployeeID], [e].[Address], [e].[BirthDate], [e].[City], [e].[Country], [e].[Extension], [e].[FirstName], [e].[HireDate], [e].[HomePhone], [e].[LastName], [e].[Notes], [e].[Photo], [e].[PhotoPath], [e].[PostalCode], [e].[Region], [e].[ReportsTo], [e].[Title], [e].[TitleOfCourtesy], [s].[ShipperID], [s].[CompanyName], [s].[Phone]
FROM (
    SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[Freight], [o].[OrderDate], [o].[RequiredDate], [o].[ShipAddress], [o].[ShipCity], [o].[ShipCountry], [o].[ShipName], [o].[ShipPostalCode], [o].[ShipRegion], [o].[ShipVia], [o].[ShippedDate]
    FROM [Orders] AS [o]
    WHERE [o].[OrderDate] IS NOT NULL AND ([o].[OrderDate] = ''2020-01-10T00:00:00.0000000'')
    ORDER BY (SELECT 1)
    OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY
) AS [t]
INNER JOIN [Customers] AS [c] ON [t].[CustomerID] = [c].[CustomerID]
INNER JOIN [Employees] AS [e] ON [t].[EmployeeID] = [e].[EmployeeID]
LEFT JOIN [Shippers] AS [s] ON [t].[ShipVia] = [s].[ShipperID]',N'@__p_0 int,@__p_1 int',@__p_0=0,@__p_1=10
```

As you can see the date value is 2020-01-10T00:00:00.0000000 and I get no errors.

I've also executed the SQL statement that gives you the error on SQL Server Management Console with no issues:
```sql
SELECT COUNT(*)
FROM [Orders] AS [o]
WHERE [o].[OrderDate] IS NOT NULL AND ([o].[OrderDate] = '1996-07-16T00:00:00.0000000')
```
Can you run this SQL statement on SQL Server Management Console?

**Comment by pcecamacho** [comment]
Yes, I executed the SQL statement in  SQL Server Management Studio.
![image](https://user-images.githubusercontent.com/59876094/73076387-66437400-3e94-11ea-9f66-6aebde3a348f.png)

The database versions that I am using is: 

- Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0
- Microsoft SQL Server 2014 (SP3-CU4) (KB4500181) - 12.0.6329.1 

The data in the tables are:
![image](https://user-images.githubusercontent.com/59876094/73076660-ee297e00-3e94-11ea-8410-b8c7aea0d19d.png)

When I execute the following SQL statement (just with 000 zeros) 
![image](https://user-images.githubusercontent.com/59876094/73076798-3cd71800-3e95-11ea-8cca-68bd66a52527.png)

SYSDATETIME and SYSUTCDATETIME have more fractional seconds precision than GETDATE and GETUTCDATE in my case the filter parameter has more fractional seconds precision where my DB no work.

Thought?

**Comment by gustavnavar** [comment]
It seems that yours database has DateTime fields created as "datetime":
https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime-transact-sql?view=sql-server-ver15

instead of "datetime2":
https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql?view=sql-server-ver15

**Comment by pcecamacho** [comment]
It's unlikely we'd update to DateTime2.  What would it take for the Grid to support both? Please

**Comment by gustavnavar** [comment]
It's EF Core thats does the translation, not the Grid. 

If the database design is not changed , then the application model shoud be. Something like:
```c#
    modelBuilder.Entity<Order>()
        .Property(sample => sample.OrderDate)
        .HasColumnType("datetime");
```
in the ```OnModelCreating``` method of ```DbContext``` class should work.

**Comment by pcecamacho** [comment]
Yes, it is working. Thank you.
