### ISSUE TITLE
Datetime filter taking in account the time as parameter.

### ISSUE THREAD

**Issue by pcecamacho** [gustavnavar/Grid.Blazor#78]
We are using the Grid Component to display a list of transactions, each transaction is recorded taking in account the date and time. (2019-11-20 16:20:36.597).

We are displaying the record time in the grid and one filter was configured over that column:

![image](https://user-images.githubusercontent.com/59876094/73199267-e8d56900-410a-11ea-85f1-5e426e3b208e.png)

It was mentioned that it would be nice to be able to filter taking in account the  **time** no only the _date_. Is that possible?

**Comment by gustavnavar** [comment]
This feature requires a datetime picker component for Blazor. The available ones only allow to pick the date, but not the time. Even the datetime picker components developed with Javascript that i know only allow to select hours and minuts, but not seconds.

So it will require time to develop a datetime picker as you request. I will leave this request as opened until I can find an feasible solution.

**Comment by rcpacheco** [comment]
We use in some apps w2ui  and it has a nice alterative to handle date and
time fields. It may give you some ideas
http://w2ui.com/web/docs/1.5/form/fields-date

**Comment by pcecamacho** [comment]
Hello
One comment, if you may develop the date/time filter using the date + "hour" + "mins" will be great.
Because we can work with that using the conditional >= and < in order to take account the seconds.

Sample  in the query: (fieldDateTime >= '2020-01-20 11:20:00'    AND  fieldDateTime < '2020-01-20 11:21:00')

**Comment by pcecamacho** [comment]
Please, do you have any update for this feature? Do you think that this is possible?

**Comment by gustavnavar** [comment]
I've uploaded new package versions that support data time on the filter widget.

You have to add the column using the ```SetFilterWidgetType``` method of the ```GridColumn``` object using the parameter value "DateTimeLocal":

```c#
    c.Add(o => o.OrderDate).SetFilterWidgetType("DateTimeLocal");
```

This link contains more info https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Using_datetime_filter.md.

**Comment by pcecamacho** [comment]
Thank you. This is working fine.
