### ISSUE TITLE
Add Not equal option in the Integer Filter (NumberFilterWidget)

### ISSUE THREAD

**Issue by pcecamacho** [gustavnavar/Grid.Blazor#79]
Is it possible to add to "NumberFilterWidget" filter the option "**Not Equal**" option?

![image](https://user-images.githubusercontent.com/59876094/73200556-69956480-410d-11ea-9e93-310baf8feaae.png)

**Comment by gustavnavar** [comment]
GridBlazor 1.3.14 and GridMvcCore 2.11.12 support this feature. you must update both.
