### ISSUE TITLE
Hide other filter widget when opening a filter

### ISSUE THREAD

**Issue by AltarBeastiful** [gustavnavar/Grid.Blazor#81]
On one of our project we use a grid with filtering. We usually use at least 4-5 filters and it takes a lot of clicks to set them up and I can find myself opening a few filtering window.
That's fine but problem arise when I want to check the current filtered values. I click a few filters and quickly the widgets overlap unless I close them first.

This is pretty click intensive if I want to check more than 2 filters and close them at the same time.
It quickly feels untidy.

**Describe the solution you'd like**
A better approach would be to close other filter window when I click on a new one.
If I open a filter widget and start to input text and click on another window, my text could be canceled.

**Describe alternatives you've considered**
An alternative would be to prevent close other filtering widget if nothing has been entered. 
And prevent other filtering window from opening if I have entered some text in a filter window.

**Additional context**
![image](https://user-images.githubusercontent.com/3317699/73376757-40680600-42be-11ea-8651-ad3a9c781553.png)

**Comment by gustavnavar** [comment]
I will add this feature in the following release.

**Comment by gustavnavar** [comment]
GridBlazor 1.3.15 supports this feature

**Comment by AltarBeastiful** [comment]
Thanks a bunch for the quick answer. I'll test it out next week and give feedback !
