### ISSUE TITLE
How to get a datasource/ filtered data of the grid after filter applied in a controller or in javascript?

### ISSUE THREAD

**Issue by shairmina** [gustavnavar/Grid.Blazor#82]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gustavnavar** [comment]
Can you explain with more detail your question? Are you working with Blazor Server-apps? Or Blazor WA? Or ASP.Net MVC?

**Comment by shairmina** [comment]
Thanks for you reply! Actually I am using GridMVCCore for Asp.Net Core MVC. For your reference, 


I need to get all the records (at least list of Id's of the records) from grid after all filters applied and pass it to the controller. I think there is no option to edit in the grid. If I edit a row using a popup window, is there any way to update the particular row without refreshing the grid again. Please let me know if you have any question.



    On Thursday, January 30, 2020, 5:05:51 p.m. EST, Gustavo Navarro <notifications@github.com> wrote:  
 
 
Can you explain with more detail your question? Are you working with Blazor Server-apps? Or Blazor WA? Or ASP.Net MVC?

**Comment by gustavnavar** [comment]
I think that the best way to do it is to use the "client side object model" https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/dotnetcore/Client_side_object_model.md because you will have all filters and sorting info on javascript.

You will also need a third action on the controller very similar to the one returning the grid visible records. In this case instead of returning a ```PartialView``` object it will return a json with the grid data:

```c#
[HttpGet]
    public ActionResult Orders()
    {
        var repository = new OrdersRepository(_context);
        var model = new SGrid<Order>(repository.GetAll(), HttpContext.Request.Query, false, GridPager.DefaultAjaxPagerViewName);
        return View(model);
    }
    
    [HttpPost]
    public ActionResult GetOrdersGridRows()
    {
        var repository = new OrdersRepository(_context);
        var model = new SGrid<Order>(repository.GetAll(), HttpContext.Request.Query, false, GridPager.DefaultAjaxPagerViewName);
        return PartialView("_OrdersGrid", model);
    }

    [HttpPost]
    public JsonResult GetOrderRows()
    {
        var repository = new OrdersRepository(_context);
        var model = new SGrid<Order>(repository.GetAll(), HttpContext.Request.Query, true, GridPager.DefaultAjaxPagerViewName);
        return Json(model.ItemsToDisplay);
    }
```

And finally you will have to add a javascript similar to:

```javascript
    <script>
        function getRawData() {
                var dfd = new $.Deferred();
                var gridUrl = pageGrids.ordersGrid.getGridUrl("/Home/GetOrderRows", pageGrids.ordersGrid.gridColumnFilters, pageGrids.ordersGrid.gridExtSort, pageGrids.ordersGrid.gridSearch, pageGrids.ordersGrid.pageSize);

                $.ajax({
                    url: gridUrl,
                    type: "POST",
                    contentType: "application/json; charset=utf-8",
                    data: pageGrids.ordersGrid.data,
                    headers: {
                        "RequestVerificationToken": pageGrids.ordersGrid.token
                    }
                })
                .done(function (response) {
                   // your code here
                })
                .always(function (response) {
                    dfd.resolve(response);
                });

                return dfd.promise();
            }

        $(function () {
            pageGrids.ordersGrid.ajaxify({
                getPagedData: "/Home/GetOrdersGridRows"
            });
        });
    </script>
```

With this solution you that you will have the data twice on your html page:
- one returned by the 2nd action of the controller (/Home/GetOrdersGridRows in the sample). This data is returned completely rendered to the grid view
- another returned by the 3nd action of the controller (/Home/GetOrdersRows in the sample). This one it the the one that you can query in javascript and be shown by a popup window to edit. 

If you edit a record on the popup window, you will have to call this code to refresh the grid visible records:

```javascript
    pageGrids.ordersGrid.loadPage();
```

**Comment by gustavnavar** [comment]
Another option is to use GridBlazor component. This article explaint how to use blazor components in Asp.Net Core MVC:
https://chrissainty.com/using-blazor-components-in-an-existing-mvc-application/
In this case you should use GridBlazor  in server-side mode. 

GridBlazor component has more features such as CRUD https://gridblazor.azurewebsites.net/crud

**Comment by shairmina** [comment]
Hey,
Thanks for all you help! The grid paging, sorting, filtering work fine when I run my .net mvc core application in Visual studio 2017. But when I deploy it to IIS in my localhost and any webserver, the paging, sorting, filtering are not working. It is only showing the data in the grid.
Shairmina

    On Wednesday, February 19, 2020, 3:57:12 a.m. EST, Gustavo Navarro <notifications@github.com> wrote:  
 
 
Closed #82.

**Comment by gustavnavar** [comment]
It seems that javascript is not working well. Can you check if there is any error on the browser developer console?

**Comment by shairmina** [comment]
Thanks for your reply! I have checked that and also checked all java script files are loaded there. Even if when I click on a page number it calls  the self.loadPage  function in gridmvc-ajax.js but it fails to call the server method through ajax call.  The fail codeblock of that ajax call is not helpful at all to get a detail error message.

    On Tuesday, February 25, 2020, 12:49:07 p.m. EST, Gustavo Navarro <notifications@github.com> wrote:  
 
 
It seems that javascript is not working well. Can you check if there is any error on the browser developer console?

**Comment by gustavnavar** [comment]
Can you send me the javascript used on the view and the controller action code?

A print screen of javascript error on the browser console will also hrlp.

**Comment by gustavnavar** [comment]
Can you send me the code that you are using?
- the view including the javascript
- the controller actions

And a printscreen of the javascript console with the error that you get.

**Comment by shairmina** [comment]
Here you go. Hope it helps you. Let me know if you need anything else. Thanks!

1) Controller action     
   [HttpPost]        public ActionResult GetAllTimeCards(DateTime submitDateFrom, DateTime submitDateTo, Guid? site, string readers = null)
        {

            AdpTimeCardRepository repo = new AdpTimeCardRepository(_connectionString);

            if (!string.IsNullOrEmpty(readers))
                readers = readers.Trim();

            var returnList = repo.GetAllTimeCardsForDateRangeAndSite(submitDateFrom, submitDateTo, site, readers).Result;
            var data = new SGrid<AdpTimeCard>(returnList, HttpContext.Request.Query, false, GridPager.DefaultAjaxPagerViewName);

            return PartialView("_TimeCardsListView", data);

        }
2) Partial View

@using GridMvc
@model SGrid<TimeCard.Data.Model.AdpTimeCard>

@await Html.Grid(Model).Named("gridTimeCards").Columns(columns =>
{
columns.Add(card => card.ReaderNumber).Titled("Reader").Filterable(true);
columns.Add(card => card.BadgeId).Filterable(true);
columns.Add(card => card.TransferInDateTime);
columns.Add(card => card.TransferOutDateTime);
columns.Add(card => card.ActionCode).SetCellCssClassesContraint(card => card.IsActionCodeChangedByServer ? "grid_cell_yellow_color" : "")
           .Filterable(true);
columns.Add(card => card.ProjectNumber).Titled("Project");
    @*columns.Add()
.Encoded(false)
.Sanitized(false)
.SetWidth(30)
.RenderValueAs(card => @<button type="button" onclick="EditTimeCard('@card.CardNumber')"> Edit </button> );*@
}).WithPaging(6).Sortable().WithMultipleFilters().RenderAsync()

                        <script type="text/javascript">
                            $(function () {
                                var timeCard = new Object();

                                timeCard.SubmitDateFrom = $("#SubmitDateFrom").val();
                                timeCard.SubmitDateTo = $("#SubmitDateTo").val();
                                if ($("#SelectedSite").val() != '')
                                    timeCard.SelectedSite = $("#SelectedSite").val();
                                timeCard.Readers = $("#Readers").val();

                                pageGrids.gridTimeCards.ajaxify({
                                    getPagedData: "/TimeCardSubmit/GetAllTimeCards?submitDateFrom=" + timeCard.SubmitDateFrom + "&submitDateTo=" + timeCard.SubmitDateTo + "&site=" + timeCard.SelectedSite + "&readers=" + timeCard.Readers
                                });

                                //pageGrids.gridTimeCards.ajaxify({
                                //    getPagedData: "/TimeCardSubmit/GetAllTimeCards"
                                //});
                            });
                        </script>



3) Console is clean. No error messages or nothing there.
4) Where it is failing when deployed to IIS. When running under visual studio everything is good.






    On Wednesday, February 26, 2020, 10:56:57 a.m. EST, Gustavo Navarro <notifications@github.com> wrote:  
 
 
Can you send me the code that you are using?
   
   - the view including the javascript
   - the controller actions

And a printscreen of the javascript console with the error that you get.

**Comment by shairmina** [comment]
I have fixed the problem. So please don't waste your time. The problem was I was using the hard coded url which is fine when I run it under visual studio but not good when I deploy it  to a server. So now I am using @Url.Action method to build the url and it is working good. Thanks for all your help! I really appreciate that. 
    On Wednesday, February 26, 2020, 10:33:55 p.m. EST, Shairmina Shafi <shairminashafi@yahoo.com> wrote:  
 
  
Here you go. Hope it helps you. Let me know if you need anything else. Thanks!

1) Controller action     
   [HttpPost]        public ActionResult GetAllTimeCards(DateTime submitDateFrom, DateTime submitDateTo, Guid? site, string readers = null)
        {

            AdpTimeCardRepository repo = new AdpTimeCardRepository(_connectionString);

            if (!string.IsNullOrEmpty(readers))
                readers = readers.Trim();

            var returnList = repo.GetAllTimeCardsForDateRangeAndSite(submitDateFrom, submitDateTo, site, readers).Result;
            var data = new SGrid<AdpTimeCard>(returnList, HttpContext.Request.Query, false, GridPager.DefaultAjaxPagerViewName);

            return PartialView("_TimeCardsListView", data);

        }
2) Partial View

@using GridMvc
@model SGrid<TimeCard.Data.Model.AdpTimeCard>

@await Html.Grid(Model).Named("gridTimeCards").Columns(columns =>
{
columns.Add(card => card.ReaderNumber).Titled("Reader").Filterable(true);
columns.Add(card => card.BadgeId).Filterable(true);
columns.Add(card => card.TransferInDateTime);
columns.Add(card => card.TransferOutDateTime);
columns.Add(card => card.ActionCode).SetCellCssClassesContraint(card => card.IsActionCodeChangedByServer ? "grid_cell_yellow_color" : "")
           .Filterable(true);
columns.Add(card => card.ProjectNumber).Titled("Project");
    @*columns.Add()
.Encoded(false)
.Sanitized(false)
.SetWidth(30)
.RenderValueAs(card => @<button type="button" onclick="EditTimeCard('@card.CardNumber')"> Edit </button> );*@
}).WithPaging(6).Sortable().WithMultipleFilters().RenderAsync()

                        <script type="text/javascript">
                            $(function () {
                                var timeCard = new Object();

                                timeCard.SubmitDateFrom = $("#SubmitDateFrom").val();
                                timeCard.SubmitDateTo = $("#SubmitDateTo").val();
                                if ($("#SelectedSite").val() != '')
                                    timeCard.SelectedSite = $("#SelectedSite").val();
                                timeCard.Readers = $("#Readers").val();

                                pageGrids.gridTimeCards.ajaxify({
                                    getPagedData: "/TimeCardSubmit/GetAllTimeCards?submitDateFrom=" + timeCard.SubmitDateFrom + "&submitDateTo=" + timeCard.SubmitDateTo + "&site=" + timeCard.SelectedSite + "&readers=" + timeCard.Readers
                                });

                                //pageGrids.gridTimeCards.ajaxify({
                                //    getPagedData: "/TimeCardSubmit/GetAllTimeCards"
                                //});
                            });
                        </script>



3) Console is clean. No error messages or nothing there.
4) Where it is failing when deployed to IIS. When running under visual studio everything is good.






    On Wednesday, February 26, 2020, 10:56:57 a.m. EST, Gustavo Navarro <notifications@github.com> wrote:  
 
 
Can you send me the code that you are using?
   
   - the view including the javascript
   - the controller actions

And a printscreen of the javascript console with the error that you get.
