### ISSUE TITLE
Initial value to properties in auto/custom create forms

### ISSUE THREAD

**Issue by rcpacheco** [gustavnavar/Grid.Blazor#83]
Is it possible to pass an initial value for the fields in auto/custom create forms?

**Comment by gustavnavar** [comment]
You can define default values for the properties of the model class. An example for the demo is to define the ```Order``` class properties as:

```c#
    ...
    public int? EmployeeID { get; set; } = 5;
    public int? ShipVia { get; set; } = 3;
    public decimal? Freight { get; set; } = 20;
    ...
```

**Comment by rcpacheco** [comment]
The problem with that is that the values are always the same, and some tome is desirable to hace diferent values depending on the business context. For example, if I'm creating a machine for a specific plant, I would like to set the plantId in advance, and that plnt Id is only known  during execition time. I will try to explore options to reach this efect. Thanks a lot

**Comment by gustavnavar** [comment]
The  element that you need access is ```_item``` of the ```GridComponent<T>``` class. It's currenly a protected variable. It's very easy to create a public get property. 

You should check if the ```Grid.Mode``` value is ```GridMode.Create``` to make the required changes.

**Comment by BadarAljahwari** [comment]
Dears,
Sorry I have the same challenge , but I couldn't  implement the solution. Appreciated if you can explain more.
I try several things but I couldn't achieve it. I am using auto generated CRUD.
Thanks
