### ISSUE TITLE
DateTime filter 

### ISSUE THREAD

**Issue by beteyemane** [gustavnavar/Grid.Blazor#84]
I'm trying to filter a range of dates by adding a filter for a start date with the type GreaterThanOrEquals, and LessThanOrEquals for an end date, and then adding an And condition:

```csharp
_filters.Add(new Filter(GridFilterType.GreaterThanOrEquals.ToString("d"), startDate.ToString("dd/MM/yyyy")));`

_filters.Add(new Filter(GridFilterType.LessThanOrEquals.ToString("d"), endDate.ToString("dd/MM/yyyy")));`

 if (filters.Count() > 1)
            filters.Add(GridFilterType.Condition.ToString("d"), GridFilterCondition.And.ToString("d"));`
```

I have also set the locale to "en-GB".

```csharp
public static void Main(string[] args)
        {
            CultureInfo.CurrentCulture = new CultureInfo("en-GB");
        }

 var client = new GridClient<TenantInfoDto>(HttpClient, url, query, false, "ordersGrid", ColumnCollections.OrderColumns, CultureInfo.CurrentCulture)
```
And also formatted the date as "dd/MM/yyyy" in the ColumnCollection.
```csharp
public static Action<IGridColumnCollection<TenantInfoDto>> OrderColumns = c =>
        {
            c.Add(o => o.Date).SetFilterWidgetType("DateRangeFilter").Filterable(true).Format("{0:dd/MM/yyyy}");
        };
```
However, it's not returning the right results.

Is this a formatting issue? Or are we missing something?

**Comment by gustavnavar** [comment]
Can you try the following column definition?

```c#
    c.Add(o => o.Date.Date).SetFilterWidgetType("DateRangeFilter").Filterable(true).Format("{0:dd/MM/yyyy}");
```

**Comment by beteyemane** [comment]
Tried that, and that doesn't seem to work.

It looks like the problem is here:

![Grid](https://user-images.githubusercontent.com/44004811/73652283-79b5c280-467e-11ea-9f1b-2e5c6aeadecb.PNG)

We've tried to filter by two dates (05/02/2020 - 06/02/2020), and as you can see we have two results matching in our database but those results don't seem to return to the grid.

**Comment by gustavnavar** [comment]
Date filters must be defined with "yyyy'-'MM'-'dd" string format. 

Can you test the follwing filter definition?
```c#
    _filters.Add(new Filter(GridFilterType.GreaterThanOrEquals.ToString("d"), startDate.ToString("yyyy'-'MM'-'dd")));

    _filters.Add(new Filter(GridFilterType.LessThanOrEquals.ToString("d"), endDate.ToString("yyyy'-'MM'-'dd")));
```

**Comment by beteyemane** [comment]
That works, thanks!
