### ISSUE TITLE
How to aggregate grid-filter values when the queries are created manually

### ISSUE THREAD

**Issue by GriesmarThomas** [gustavnavar/Grid.Blazor#86]
Hello, 

I would like to get my entities filtered by at least two values.
For this, I want to use the API and the key "grid-filter". I don't want to use the filter columns already provided by default.

 ```
  
var myEntitites = myService.GetAll();

var queries = new QueryDictionary<StringValues>();
queries.Add("grid-filter", "ContextCustomerJourneyMapId__1__1047&CustomerTargetGroupId__1__1010");

var server = new GridServer<UseCase>(myEntities, new QueryCollection(queries),
                true, "useCasesGrid", columns)
                .Filterable()
                .WithPaging(_maxUseCasesDisplayed)
                .ExtSortable(true)
                .Sortable(true)
                .Filterable(true)
                .WithMultipleFilters()
                .Searchable(true, true);
```

This code doesn't retreive the result expected. Do you know if I can aggregate these parameters ? If yes, how ?

**Comment by gustavnavar** [comment]
You must create an array of strings including all filters, and after that create a ```StringValues``` object from the array:

```c#
    var query = new QueryDictionary<StringValues>();
    var values = new string[] {
        "ContextCustomerJourneyMapId__1__1047",
        "CustomerTargetGroupId__1__1010"
    };
    query.Add("grid-filter", new StringValues(values));
```

**Comment by GriesmarThomas** [comment]
Thank you, I have a last problem though. 
When I retreive the informations to display in the grid, I get the filtered element, but the grid doesn't refresh (there are still the element of the GetAll(). 
But after I click on another page of the grid, or after I reapply mt filter a second time, the grid is refreshed.
Where does it come from ?

**Comment by gustavnavar** [comment]
You have to call the ```UpdateGrid``` method of the ```GridComponent``` object.  

First. you have to to the GridComponent when the page is loaded:
```c#
    <GridComponent @ref="MyComponent" T="Channel" Grid="@_grid"></GridComponent>
```

And then you have call this statement to refresh the grid content:
```c#
    await MyComponent.UpdateGrid();
```

**Comment by GriesmarThomas** [comment]
Thank you, it works like a charm now.
