### ISSUE TITLE
Demo - Drop columns here for columns grouping

### ISSUE THREAD

**Issue by Spock1024** [gustavnavar/Grid.Blazor#89]
**Describe the bug**
A clear and concise description of what the bug is. **Grouping error**

**To Reproduce**
1. Go to '...' **Demo**
2. Click on '....' **Drag Date to grouping rectangle above table. Then drag Company to the same area. Dragging Contact instead of Company does not produce an error.**

**Expected behavior**

**Screenshots**
![2020-02-07 (1)](https://user-images.githubusercontent.com/60755826/74058529-da5d3c00-49ab-11ea-8400-8001644f99ec.png)
![2020-02-07 (2)](https://user-images.githubusercontent.com/60755826/74058563-ee08a280-49ab-11ea-926b-1e6199c883a3.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] **Windows 10 Pro**
 - Browser [e.g. chrome, safari] **Edge** 
 - Version [e.g. 22] **Version 79.0.309.71**

**Smartphone (please complete the following information):**

**Additional context**
First time test from this project. Downloaded 20200207, compiled and run using Visual Studio Community 2019 Version 16.4.4

**Comment by gustavnavar** [comment]
This error has been fixed in the last commits. 

There are also new GridBlazor and GridMvcCore packages (1.3.17 and 2.11.14) for this.
