### ISSUE TITLE
Add custom comparers for columns

### ISSUE THREAD

**Issue by ZimM-LostPolygon** [gustavnavar/Grid.Blazor#90]
**Is your feature request related to a problem? Please describe.**
I have a column with an indexed list of devices. `Device-1`, `Device-2`, etc. The problem is that GridBlazor uses default .NET string comparer. If the column is sorted, items seem to out-of-order for a human:
```
Device-1
Device-10
Device-11
Device-12
Device-13
Device-14
Device-15
Device-16
Device-17
Device-18
Device-19
Device-2
Device-21
Device-21
...
```

**Describe the solution you'd like**
Add an option to set a custom `IComparer` for a single column. 
Add an option to set a default custom `IComparer` for the entire grid.

Then it would be possible to use a library like https://github.com/tompazourek/NaturalSort.Extension for natural sorting.

**Additional context**

In my case, the data is not loaded directly from database, so there is no DB-side sorting involved.

`OrderBy` and `OrderByDescending` methods accept an IComparer as a second parameter.

![image](https://user-images.githubusercontent.com/928550/74110950-fec63d80-4b90-11ea-8218-83c669f7ab0a.png)

**Comment by gustavnavar** [comment]
I've updated a new package version that supports custom comparers for in-memory data grids.

You can enable it at coumn level by calling the ```Columns.Add``` method in the ```IGridColumnCollection``` interface using an ```IComparer<TKey>``` as a parameter:

```c#
    var comparer = new ....;

    .... 

    c.Add(o => o.Customer.CompanyName, comparer)
```
