### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by davidindra** [gustavnavar/Grid.Blazor#91]
Hi,
is it possible to include Czech translation? Needed strings here:

Add - Přidat
And - A
Apply - Potvrdit
Average - Průměr
Back - Zpět
No - Ne
Yes - Ano
Clear all filters - Smazat všechny filtry
Clear filter - Smazat filtr
Contains - Obsahuje
Create item - Vytvořit položku
There are no items to display - Nejsou k dispozici žádné položky
Delete - Odstranit
Delete item - Odstranit položku
Edit - Upravit
Ends with - Končí
Equals - Je stejný
Drop columns here for column extended sorting - Přetáhněte sloupce sem pro pokročilé řazení
Filter this column - Filtrovat sloupec
Type - Typ
Value - Hodnota
Greater than - Větší než
Greater than or equals - Větší než nebo rovno
Drop columns here for column grouping - Přetáhněte sloupce sem pro seskupování sloupců
Items - Položky
Less than - Menší než
Less than or equals - Menší než nebo rovno
Max - Max
Min - Min
Or - Nebo
Read item - Zobrazit položku
Save - Uložit
Search for ... - Vyhledat...
--- Select an item --- - --- Vyberte položku ---
Show - Zobrazit
Starts with - Začíná
Sum - Suma
Update item - Upravit položku
View - Zobrazit

Thanks!

**Comment by gustavnavar** [comment]
Hi,

I will need the translation of "Not equals".

Thanks!

**Comment by davidindra** [comment]
Not equals - není stejný

**Comment by davidindra** [comment]
Please, tell me when I can update Grid.Blazor including the translation :)

**Comment by gustavnavar** [comment]
The following package versions support it:
- GridBlazor version 1.3.18
- GridMvcCore Version 2.11.15

**Comment by davidindra** [comment]
Thank you a lot! :)
