### ISSUE TITLE
How to display hierarchy?

### ISSUE THREAD

**Issue by Oleg26Dev** [gustavnavar/Grid.Blazor#92]
Thank you for the great component.
How I can display hierarchy like File system?
For example, I open a folder

Folder
  - subfolder
       file
       file
   - - subfolder
         file
         file
  - file
file
file

**Comment by gustavnavar** [comment]
You can use subgrids in cascade. But I foresee 2 possible issues:
- I've never tested subgrids with more than 2 levels
- A file system will require a non-fixed number of levels

**Comment by win32nipuh** [comment]
I use subgrid and it works fine. I can use OnRowClicked for the master grid, but I need it for the subgrid. How can I assign function for it?

 OnRowClicked="@ItemDetails"
