### ISSUE TITLE
Search not working when column exists with nested property

### ISSUE THREAD

**Issue by timbze** [gustavnavar/Grid.Blazor#93]
I am using server-side Blazor grid, latest version.

**Describe the bug**
All data is displayed correctly, but text search is not filtering at all when I have a sub-level property. Here's what I mean, my columns code:
```csharp
Action<IGridColumnCollection<Truck>> columns = 
    {
        c.Add(t => t.description)
            .Titled("Description")
            .Filterable(true);

        c.Add(t => t.Owner_person.full_name)
            .Titled("Owner")
            .Filterable(true);
    }
```

When I do a search, the data get's reloaded, but nothing is filtered. When I remove t.Owner_person.full_name column, search works great.

**Additional context**
GridClient code
```csharp
var client = new GridClient<Truck>(q => truckAccess.GetGridRows(columns, q, gridName, 
    truckAccess.OptionsItemList()), query, false, gridName, columns)
        .Searchable()
        .SetStriped(true)
        .Sortable()
        .WithGridItemsCount()
        .WithMultipleFilters();
```

GridServer code
```csharp
Task<ItemsDTO<TModel>> GetGridRows()
{
var server = new GridServer<TModel>(itemList, new QueryCollection(query), true, gridName, columns)
    .Filterable()
    .Searchable()
    .Sortable()
    .WithMultipleFilters();

    return server.ItemsToDisplay;
}
```

**Comment by gustavnavar** [comment]
Could you show the model classes (Truck and Owner)?

**Comment by timbze** [comment]
Here's the relevant context:
```csharp
[Serializable]
public class Truck
{
    [Key]
    public int? truck_id { get; set; }
    public string? description { get; set; }
    [JsonIgnore]
    public Person Owner_person { get; set; } = new Person();
}

[Serializable]
public class Person
{
    [Key]
    public int? person_id { get; set; }
    public string? first_name { get; set; }
    public string? last_name { get; set; }
    public string? full_name => $"{ first_name } { last_name }";
}
```

**Comment by gustavnavar** [comment]
Entity Framework Core 3.0 requires all queries be executed in the database. Client query executed is not supported. 

The best option is to use "keyless entities": https://docs.microsoft.com/en-us/ef/core/modeling/keyless-entity-types

This subject has been discussed here: https://github.com/gustavnavar/Grid.Blazor/issues/39

**Comment by timbze** [comment]
I am actually not using EF. I'm using that attribute for Dapper

**Comment by timbze** [comment]
And I tried using person.first_name which had same issue.

**Comment by gustavnavar** [comment]
GridBlazor uses Linq and IQueriable<> extensively. All queries for searching, filtering, sorting are build with Linq. This is an example of Linq expresssion created for searching the word "aro" in a grid that includes class properties:

```c#
    {((((x..ToString().ToUpper().Contains("aro".ToUpper()) OrElse (x.description.HasValue AndAlso x.description.Value.ToString().ToUpper().Contains("aro".ToUpper()))) OrElse ((x.Owner_person.first_name != null) AndAlso x.Owner_person.first_name.ToUpper().Contains("aro".ToUpper()))) OrElse ((x.Owner_person.full_name != null) AndAlso x.Owner_person.full_name.ToUpper().Contains("aro".ToUpper()))))}
```

The ORM must translate all created Linq queries to SQL, and it seems that Dapper is not doing it properly.

I've not tested GridBlazor with Dapper, but there ara other people with similar problems:
https://dapper-tutorial.net/knowledge-base/38826292/how-to-use-dapper-with-linq

Can you test parts of the sample Linq expression to identify which one is causing an exception?

**Comment by timbze** [comment]
I have found that it is the nested property that causes the exception. It looks like expressions do not work on nested properties the same way.

https://social.technet.microsoft.com/wiki/contents/articles/26278.expression-trees-accessing-nested-properties.aspx

https://stackoverflow.com/questions/26766934/linq-query-for-a-nested-class

**Comment by gustavnavar** [comment]
Yes, it works with EF Core. 

The demo works on EF Core: https://gridblazor.azurewebsites.net/searchable

Company, Contact and IsVip are nested properties: https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorServerSide/ColumnCollections/ColumnCollections.cs
