### ISSUE TITLE
Validation before insert or update

### ISSUE THREAD

**Issue by matteoventuri7** [gustavnavar/Grid.Blazor#94]
I would like to integrate FluentValidation with Grid.Blazor.
I would like to register OnInsertEvent and OnUpdateEvent when I use Crud feature.

**Comment by gustavnavar** [comment]
I can add these events to the ´´´GridComponent´´´ object:
```c#
    public event Func<T, Task> BeforeInsert;
    public event Func<T, Task> BeforeUpdate;
    public event Func<T, Task> BeforeDelete;
```

So you should be able to register funcions like this one:
```c#
    private async Task BeforeInsert(T item)
        {
            ....
            await Task.CompletedTask;
        }
```

You will get the item to be validated as parameter and return a Task. Is that ok for you? Do you need any other parameter?

**Comment by gustavnavar** [comment]
The current used events are: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Events.md

**Comment by matteoventuri7** [comment]
Perfect! Thanks very much! Greate job!

**Comment by gustavnavar** [comment]
GridBlazor 1.3.20  and  GridMvcCore 2.11.17 support these events:
```c#
    public event Func<object, T, Task> BeforeInsert;
    public event Func<object, T, Task> BeforeUpdate
    public event Func<object, T, Task> BeforeDelete;
```
You can use them as follows:
```c#
    private async Task BeforeInsert(object sender, T item)
    {
        ....
        await Task.CompletedTask;
    }
```
The first pareameter is the ```GridComponent``` object and the second one the item to be validated.

**Comment by matteoventuri7** [comment]
I am trying to write validation code like this:
```C#
Task IGridRepository<Tdto>.BeforeInsert(object sender, Tdto item)
        {
            var valid = Validator.Validate(item);
            if (!valid.IsValid)
            {
                throw new ValidationException(valid.ToString());
            }

            return Task.CompletedTask;
        }
```
If validation fail, I read errors into console and a generic message error into web page.
How can i return something more specific? for example a dictionary field/error message.

**Comment by gustavnavar** [comment]
Whats your goal? To write the error in a log? Or to show an error message to the user on the screen?

**Comment by matteoventuri7** [comment]
show an error message to the user on the screen like Blazor default validation form or MVC default validation form.

**Comment by gustavnavar** [comment]
Understood. GridBlazor is doing that using annotations on the model class (see Range annotation here https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorServerSide/Models/OrderDetail.cs).

I will add a mechanism to allow you to access the error field on the CRUD forms that GridBlazor currently uses.

I will tell you as soon as it will be implemented.

**Comment by matteoventuri7** [comment]
Thanks.

**Comment by gustavnavar** [comment]
GridBlazor 1.3.21 support these events for CRUD:
```c#
    public event Func<GridCreateComponent<T>, T, Task<bool>> BeforeInsert;
    public event Func<GridUpdateComponent<T>, T, Task<bool>> BeforeUpdate;
    public event Func<GridDeleteComponent<T>, T, Task<bool>> BeforeDelete;
```

This page in the demo implements a validation for the ```Freight``` field: https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorServerSide/Pages/Crud.razor

The used validator in the demo is: https://github.com/gustavnavar/Grid.Blazor/blob/master/GridBlazorServerSide/Models/OrderValidator.cs

**Comment by matteoventuri7** [comment]
Thank you.

**Comment by faina09** [comment]
@gustavnavar this is working well but there are some limitations with respect to the FluentValidation{8.6.2} component:
- If there are multiple messages, these are displayed on *a single line* and not one on each line
- there is no validation message close to the failed field
- there is no red/green frame around the wrong/correct fields
I think these are very nice features; it is possible to have them in GridBlazor?
Thank you

I used a FluentValidation minimal sample, the output is here:
![fv](https://user-images.githubusercontent.com/5863701/82901558-66e13980-9f5e-11ea-85e3-57dee3e77c21.png)

**Comment by gustavnavar** [comment]
Version 1.6.6 implements form validation at field level:
https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_client/Events.md#events-and-crud-validation

There is a new property of the ```GridComponent``` object for error messages for each form field. It's name is ```ColumnErrors```.

This is an example for the insert validation event:
```c#
   @code {
        private async Task<bool> BeforeInsert(GridCreateComponent<Order> component, Order item)
        {
            var orderValidator = new OrderValidator();
            var valid = await orderValidator.ValidateAsync(item);

            if (!valid.IsValid)
            {
                component.Error = "Insert operation returned one or more errors";
                foreach (var error in valid.Errors)
                {
                    component.ColumnErrors.AddParameter(error.PropertyName, error.ErrorMessage);
                }
            }

            return valid.IsValid;
        }
    }
```

**Comment by faina09** [comment]
very nice! thank you
