### ISSUE TITLE
northwind demo database

### ISSUE THREAD

**Issue by Oleg26Dev** [gustavnavar/Grid.Blazor#95]
I have downloaded the demo database files
Grid.Blazor/GridMvc.Demo/App_Data/
but cannot attach to the SQL Server 2014 because of 2014 does not support this version.
Can I use any of fresher databases?

**Comment by gustavnavar** [comment]
I think you can create it using scripts

**Comment by gustavnavar** [comment]
After running this script https://github.com/microsoft/sql-server-samples/blob/master/samples/databases/northwind-pubs/instnwnd.sql , you must add a column to the Customers table with the name IsVip of type bit (NOT NULL) and default value 0.
