### ISSUE TITLE
Hide column after added it

### ISSUE THREAD

**Issue by matteoventuri7** [gustavnavar/Grid.Blazor#99]
Whene I add a column and i want to hide it i can use method Add:
```C#
Columns.Add(o => o.Id, true);
```
but if i want to hide column after, using method Get?
```C#
Columns.Get(o => o.Id)..........
```

**Comment by timbze** [comment]
You could look at the Columns.SetCellCssClassesContraint() method and using `d-none` CSS class, though maybe there would be another better way to do it, not sure: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Custom_columns.md

**Comment by matteoventuri7** [comment]
> You could look at the Columns.SetCellCssClassesContraint() method and using `d-none` CSS class, though maybe there would be another better way to do it, not sure: https://github.com/gustavnavar/Grid.Blazor/blob/master/docs/blazor_server/Custom_columns.md

No, SetCellCssClassesContraint applys css class on td.grid-cell and does not hide the column.

**Comment by timbze** [comment]
@matteoventuri7 Oh you're right, my bad. I will need this soon too on a project I am doing but didn't work on that part yet.

**Comment by gustavnavar** [comment]
Columns are created as "GridColumn" or "HiddenGridColumn" classes when Add method is used. There is no way to convert them on the fly.

**Comment by gustavnavar** [comment]
Thanks https://github.com/timbze! I think the solution you popossed is a good one. The "GridColumn" and "HiddenGridColumn" classes only differ on the "Hidden" property value nowadays. The difference between both classes has been removed over time. In fact may be "HiddenGridColumn" can be removed.

I will try to add your code on the next release. 

I will add the propossec change in the follown

**Comment by timbze** [comment]
Thank you @gustavnavar for your hard work on this superb project!

**Comment by gustavnavar** [comment]
GridBlazor 1.3.23 implements this solution: 
https://github.com/gustavnavar/Grid.Blazor/pull/106
